<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/nlu/session.proto

namespace Ondewo\Nlu;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * This message is a request to add the audio files specified
 *
 * Generated from protobuf message <code>ondewo.nlu.AddAudioFilesRequest</code>
 */
class AddAudioFilesRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Required. The project of this agent.
     * Format: <pre><code>projects/&lt;project_uuid&gt;/agent</code></pre>
     *
     * Generated from protobuf field <code>string parent = 1;</code>
     */
    protected $parent = '';
    /**
     * The unique identifier of the session for which the audio files should be listed
     * Format: <pre><code>projects/&lt;project_uuid&gt;/agent/sessions/&lt;session_uuid&gt;/&lt</code></pre>
     *
     * Generated from protobuf field <code>string session_id = 2;</code>
     */
    protected $session_id = '';
    /**
     * AudioFileResources to be added
     *
     * Generated from protobuf field <code>repeated .ondewo.nlu.AudioFileResource audio_file_resources = 3;</code>
     */
    private $audio_file_resources;
    /**
     * The unique identifier of the session step for which the audio files should be listed
     * Format: <pre><code>projects/&lt;project_uuid&gt;/agent/sessions/&lt;session_uuid&gt;/sessionsteps/&lt;session_step_uuid&gt;/&lt</code></pre>
     *
     * Generated from protobuf field <code>string session_step_id = 4;</code>
     */
    protected $session_step_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $parent
     *           Required. The project of this agent.
     *           Format: <pre><code>projects/&lt;project_uuid&gt;/agent</code></pre>
     *     @type string $session_id
     *           The unique identifier of the session for which the audio files should be listed
     *           Format: <pre><code>projects/&lt;project_uuid&gt;/agent/sessions/&lt;session_uuid&gt;/&lt</code></pre>
     *     @type \Ondewo\Nlu\AudioFileResource[] $audio_file_resources
     *           AudioFileResources to be added
     *     @type string $session_step_id
     *           The unique identifier of the session step for which the audio files should be listed
     *           Format: <pre><code>projects/&lt;project_uuid&gt;/agent/sessions/&lt;session_uuid&gt;/sessionsteps/&lt;session_step_uuid&gt;/&lt</code></pre>
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Nlu\Session::initOnce();
        parent::__construct($data);
    }

    /**
     * Required. The project of this agent.
     * Format: <pre><code>projects/&lt;project_uuid&gt;/agent</code></pre>
     *
     * Generated from protobuf field <code>string parent = 1;</code>
     * @return string
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * Required. The project of this agent.
     * Format: <pre><code>projects/&lt;project_uuid&gt;/agent</code></pre>
     *
     * Generated from protobuf field <code>string parent = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setParent($var)
    {
        GPBUtil::checkString($var, True);
        $this->parent = $var;

        return $this;
    }

    /**
     * The unique identifier of the session for which the audio files should be listed
     * Format: <pre><code>projects/&lt;project_uuid&gt;/agent/sessions/&lt;session_uuid&gt;/&lt</code></pre>
     *
     * Generated from protobuf field <code>string session_id = 2;</code>
     * @return string
     */
    public function getSessionId()
    {
        return $this->session_id;
    }

    /**
     * The unique identifier of the session for which the audio files should be listed
     * Format: <pre><code>projects/&lt;project_uuid&gt;/agent/sessions/&lt;session_uuid&gt;/&lt</code></pre>
     *
     * Generated from protobuf field <code>string session_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSessionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->session_id = $var;

        return $this;
    }

    /**
     * AudioFileResources to be added
     *
     * Generated from protobuf field <code>repeated .ondewo.nlu.AudioFileResource audio_file_resources = 3;</code>
     * @return RepeatedField<\Ondewo\Nlu\AudioFileResource>
     */
    public function getAudioFileResources()
    {
        return $this->audio_file_resources;
    }

    /**
     * AudioFileResources to be added
     *
     * Generated from protobuf field <code>repeated .ondewo.nlu.AudioFileResource audio_file_resources = 3;</code>
     * @param \Ondewo\Nlu\AudioFileResource[] $var
     * @return $this
     */
    public function setAudioFileResources($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Ondewo\Nlu\AudioFileResource::class);
        $this->audio_file_resources = $arr;

        return $this;
    }

    /**
     * The unique identifier of the session step for which the audio files should be listed
     * Format: <pre><code>projects/&lt;project_uuid&gt;/agent/sessions/&lt;session_uuid&gt;/sessionsteps/&lt;session_step_uuid&gt;/&lt</code></pre>
     *
     * Generated from protobuf field <code>string session_step_id = 4;</code>
     * @return string
     */
    public function getSessionStepId()
    {
        return $this->session_step_id;
    }

    /**
     * The unique identifier of the session step for which the audio files should be listed
     * Format: <pre><code>projects/&lt;project_uuid&gt;/agent/sessions/&lt;session_uuid&gt;/sessionsteps/&lt;session_step_uuid&gt;/&lt</code></pre>
     *
     * Generated from protobuf field <code>string session_step_id = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSessionStepId($var)
    {
        GPBUtil::checkString($var, True);
        $this->session_step_id = $var;

        return $this;
    }

}

