<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/nlu/llm_evaluation.proto

namespace Ondewo\Nlu;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Request to apply an A/B rollout: promotes the chosen variant's config to the
 * project's classifier default, stops the experiment and writes the audit
 * decision. Idempotent — re-applying the same already-applied experiment returns
 * the existing decision rather than promoting twice.
 *
 * Generated from protobuf message <code>ondewo.nlu.ApplyLlmEvaluationAbRolloutRequest</code>
 */
class ApplyLlmEvaluationAbRolloutRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Resource name of the experiment to roll out.
     * Format: <code>projects/&lt;project_uuid&gt;/agent/llmEvaluationAbExperiments/&lt;experiment_uuid&gt;</code>.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Required. Variant slug whose config to promote to the project classifier
     * default. The operator's explicit choice; the server applies exactly this
     * variant.
     *
     * Generated from protobuf field <code>string variant_id = 2;</code>
     */
    protected $variant_id = '';
    /**
     * The metric the decision was made on, recorded on the audit decision.
     *
     * Generated from protobuf field <code>.ondewo.nlu.LlmEvaluationAbOptimizeMetric optimize_metric = 3;</code>
     */
    protected $optimize_metric = 0;
    /**
     * Project owning the experiment.
     * Format: <code>projects/&lt;project_uuid&gt;/agent</code>.
     *
     * Generated from protobuf field <code>string parent = 4;</code>
     */
    protected $parent = '';
    /**
     * BCP-47 language-code scope (required).
     *
     * Generated from protobuf field <code>string language_code = 5;</code>
     */
    protected $language_code = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           Resource name of the experiment to roll out.
     *           Format: <code>projects/&lt;project_uuid&gt;/agent/llmEvaluationAbExperiments/&lt;experiment_uuid&gt;</code>.
     *     @type string $variant_id
     *           Required. Variant slug whose config to promote to the project classifier
     *           default. The operator's explicit choice; the server applies exactly this
     *           variant.
     *     @type int $optimize_metric
     *           The metric the decision was made on, recorded on the audit decision.
     *     @type string $parent
     *           Project owning the experiment.
     *           Format: <code>projects/&lt;project_uuid&gt;/agent</code>.
     *     @type string $language_code
     *           BCP-47 language-code scope (required).
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Nlu\LlmEvaluation::initOnce();
        parent::__construct($data);
    }

    /**
     * Resource name of the experiment to roll out.
     * Format: <code>projects/&lt;project_uuid&gt;/agent/llmEvaluationAbExperiments/&lt;experiment_uuid&gt;</code>.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Resource name of the experiment to roll out.
     * Format: <code>projects/&lt;project_uuid&gt;/agent/llmEvaluationAbExperiments/&lt;experiment_uuid&gt;</code>.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Required. Variant slug whose config to promote to the project classifier
     * default. The operator's explicit choice; the server applies exactly this
     * variant.
     *
     * Generated from protobuf field <code>string variant_id = 2;</code>
     * @return string
     */
    public function getVariantId()
    {
        return $this->variant_id;
    }

    /**
     * Required. Variant slug whose config to promote to the project classifier
     * default. The operator's explicit choice; the server applies exactly this
     * variant.
     *
     * Generated from protobuf field <code>string variant_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setVariantId($var)
    {
        GPBUtil::checkString($var, True);
        $this->variant_id = $var;

        return $this;
    }

    /**
     * The metric the decision was made on, recorded on the audit decision.
     *
     * Generated from protobuf field <code>.ondewo.nlu.LlmEvaluationAbOptimizeMetric optimize_metric = 3;</code>
     * @return int
     */
    public function getOptimizeMetric()
    {
        return $this->optimize_metric;
    }

    /**
     * The metric the decision was made on, recorded on the audit decision.
     *
     * Generated from protobuf field <code>.ondewo.nlu.LlmEvaluationAbOptimizeMetric optimize_metric = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setOptimizeMetric($var)
    {
        GPBUtil::checkEnum($var, \Ondewo\Nlu\LlmEvaluationAbOptimizeMetric::class);
        $this->optimize_metric = $var;

        return $this;
    }

    /**
     * Project owning the experiment.
     * Format: <code>projects/&lt;project_uuid&gt;/agent</code>.
     *
     * Generated from protobuf field <code>string parent = 4;</code>
     * @return string
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * Project owning the experiment.
     * Format: <code>projects/&lt;project_uuid&gt;/agent</code>.
     *
     * Generated from protobuf field <code>string parent = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setParent($var)
    {
        GPBUtil::checkString($var, True);
        $this->parent = $var;

        return $this;
    }

    /**
     * BCP-47 language-code scope (required).
     *
     * Generated from protobuf field <code>string language_code = 5;</code>
     * @return string
     */
    public function getLanguageCode()
    {
        return $this->language_code;
    }

    /**
     * BCP-47 language-code scope (required).
     *
     * Generated from protobuf field <code>string language_code = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setLanguageCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->language_code = $var;

        return $this;
    }

}

