<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/nlu/entity_type.proto

namespace Ondewo\Nlu;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * This message is a request to create a batch entities
 *
 * Generated from protobuf message <code>ondewo.nlu.BatchCreateEntitiesRequest</code>
 */
class BatchCreateEntitiesRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The create entity requests in a batch
     *
     * Generated from protobuf field <code>repeated .ondewo.nlu.CreateEntityRequest create_entity_requests = 1;</code>
     */
    private $create_entity_requests;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Ondewo\Nlu\CreateEntityRequest[] $create_entity_requests
     *           The create entity requests in a batch
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Nlu\EntityType::initOnce();
        parent::__construct($data);
    }

    /**
     * The create entity requests in a batch
     *
     * Generated from protobuf field <code>repeated .ondewo.nlu.CreateEntityRequest create_entity_requests = 1;</code>
     * @return RepeatedField<\Ondewo\Nlu\CreateEntityRequest>
     */
    public function getCreateEntityRequests()
    {
        return $this->create_entity_requests;
    }

    /**
     * The create entity requests in a batch
     *
     * Generated from protobuf field <code>repeated .ondewo.nlu.CreateEntityRequest create_entity_requests = 1;</code>
     * @param \Ondewo\Nlu\CreateEntityRequest[] $var
     * @return $this
     */
    public function setCreateEntityRequests($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Ondewo\Nlu\CreateEntityRequest::class);
        $this->create_entity_requests = $arr;

        return $this;
    }

}

