<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/nlu/session.proto

namespace Ondewo\Nlu;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Message used to filter sessions based on contextual information
 *
 * Generated from protobuf message <code>ondewo.nlu.ContextFilter</code>
 */
class ContextFilter extends \Google\Protobuf\Internal\Message
{
    /**
     * name of the context
     *
     * Generated from protobuf field <code>string context_name = 1;</code>
     */
    protected $context_name = '';
    /**
     * name of the key of the context parameter
     *
     * Generated from protobuf field <code>string key = 2;</code>
     */
    protected $key = '';
    /**
     * value of the parameter
     *
     * Generated from protobuf field <code>string value = 3;</code>
     */
    protected $value = '';
    /**
     * comparison operator to use for filtering
     *
     * Generated from protobuf field <code>.ondewo.nlu.ComparisonOperator operator = 4;</code>
     */
    protected $operator = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $context_name
     *           name of the context
     *     @type string $key
     *           name of the key of the context parameter
     *     @type string $value
     *           value of the parameter
     *     @type int $operator
     *           comparison operator to use for filtering
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Nlu\Session::initOnce();
        parent::__construct($data);
    }

    /**
     * name of the context
     *
     * Generated from protobuf field <code>string context_name = 1;</code>
     * @return string
     */
    public function getContextName()
    {
        return $this->context_name;
    }

    /**
     * name of the context
     *
     * Generated from protobuf field <code>string context_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setContextName($var)
    {
        GPBUtil::checkString($var, True);
        $this->context_name = $var;

        return $this;
    }

    /**
     * name of the key of the context parameter
     *
     * Generated from protobuf field <code>string key = 2;</code>
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * name of the key of the context parameter
     *
     * Generated from protobuf field <code>string key = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->key = $var;

        return $this;
    }

    /**
     * value of the parameter
     *
     * Generated from protobuf field <code>string value = 3;</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * value of the parameter
     *
     * Generated from protobuf field <code>string value = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->value = $var;

        return $this;
    }

    /**
     * comparison operator to use for filtering
     *
     * Generated from protobuf field <code>.ondewo.nlu.ComparisonOperator operator = 4;</code>
     * @return int
     */
    public function getOperator()
    {
        return $this->operator;
    }

    /**
     * comparison operator to use for filtering
     *
     * Generated from protobuf field <code>.ondewo.nlu.ComparisonOperator operator = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setOperator($var)
    {
        GPBUtil::checkEnum($var, \Ondewo\Nlu\ComparisonOperator::class);
        $this->operator = $var;

        return $this;
    }

}

