<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/nlu/session.proto

namespace Ondewo\Nlu;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Request to persist a session review for a given session.
 * As a side effect, training data in ondewo-cai may also be updated.
 *
 * Generated from protobuf message <code>ondewo.nlu.CreateSessionReviewRequest</code>
 */
class CreateSessionReviewRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The unique identifier for the session under review
     * Format: <pre><code>projects/&lt;project_uuid&gt;/agent/sessions/&lt;session_uuid&gt;</code></pre>
     *
     * Generated from protobuf field <code>string session_id = 1;</code>
     */
    protected $session_id = '';
    /**
     * Optional: The unique identifier of the parent review
     * Format: <pre><code>projects/&lt;project_uuid&gt;/agent/sessions/&lt;session_uuid&gt;/reviews/&lt;session_review_uuid&gt;</code></pre>
     *
     * Generated from protobuf field <code>string parent_review_id = 2;</code>
     */
    protected $parent_review_id = '';
    /**
     * The reviews for all steps in the session
     *
     * Generated from protobuf field <code>.ondewo.nlu.SessionReview session_review = 3;</code>
     */
    protected $session_review = null;
    /**
     * Represents the options for views of a session_review.
     * A session_review can be a sizable object. Therefore, we provide a resource view that does not return all data
     *
     * Generated from protobuf field <code>.ondewo.nlu.SessionReview.View session_review_view = 4;</code>
     */
    protected $session_review_view = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $session_id
     *           The unique identifier for the session under review
     *           Format: <pre><code>projects/&lt;project_uuid&gt;/agent/sessions/&lt;session_uuid&gt;</code></pre>
     *     @type string $parent_review_id
     *           Optional: The unique identifier of the parent review
     *           Format: <pre><code>projects/&lt;project_uuid&gt;/agent/sessions/&lt;session_uuid&gt;/reviews/&lt;session_review_uuid&gt;</code></pre>
     *     @type \Ondewo\Nlu\SessionReview $session_review
     *           The reviews for all steps in the session
     *     @type int $session_review_view
     *           Represents the options for views of a session_review.
     *           A session_review can be a sizable object. Therefore, we provide a resource view that does not return all data
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Nlu\Session::initOnce();
        parent::__construct($data);
    }

    /**
     * The unique identifier for the session under review
     * Format: <pre><code>projects/&lt;project_uuid&gt;/agent/sessions/&lt;session_uuid&gt;</code></pre>
     *
     * Generated from protobuf field <code>string session_id = 1;</code>
     * @return string
     */
    public function getSessionId()
    {
        return $this->session_id;
    }

    /**
     * The unique identifier for the session under review
     * Format: <pre><code>projects/&lt;project_uuid&gt;/agent/sessions/&lt;session_uuid&gt;</code></pre>
     *
     * Generated from protobuf field <code>string session_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSessionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->session_id = $var;

        return $this;
    }

    /**
     * Optional: The unique identifier of the parent review
     * Format: <pre><code>projects/&lt;project_uuid&gt;/agent/sessions/&lt;session_uuid&gt;/reviews/&lt;session_review_uuid&gt;</code></pre>
     *
     * Generated from protobuf field <code>string parent_review_id = 2;</code>
     * @return string
     */
    public function getParentReviewId()
    {
        return $this->parent_review_id;
    }

    /**
     * Optional: The unique identifier of the parent review
     * Format: <pre><code>projects/&lt;project_uuid&gt;/agent/sessions/&lt;session_uuid&gt;/reviews/&lt;session_review_uuid&gt;</code></pre>
     *
     * Generated from protobuf field <code>string parent_review_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setParentReviewId($var)
    {
        GPBUtil::checkString($var, True);
        $this->parent_review_id = $var;

        return $this;
    }

    /**
     * The reviews for all steps in the session
     *
     * Generated from protobuf field <code>.ondewo.nlu.SessionReview session_review = 3;</code>
     * @return \Ondewo\Nlu\SessionReview|null
     */
    public function getSessionReview()
    {
        return $this->session_review;
    }

    public function hasSessionReview()
    {
        return isset($this->session_review);
    }

    public function clearSessionReview()
    {
        unset($this->session_review);
    }

    /**
     * The reviews for all steps in the session
     *
     * Generated from protobuf field <code>.ondewo.nlu.SessionReview session_review = 3;</code>
     * @param \Ondewo\Nlu\SessionReview $var
     * @return $this
     */
    public function setSessionReview($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Nlu\SessionReview::class);
        $this->session_review = $var;

        return $this;
    }

    /**
     * Represents the options for views of a session_review.
     * A session_review can be a sizable object. Therefore, we provide a resource view that does not return all data
     *
     * Generated from protobuf field <code>.ondewo.nlu.SessionReview.View session_review_view = 4;</code>
     * @return int
     */
    public function getSessionReviewView()
    {
        return $this->session_review_view;
    }

    /**
     * Represents the options for views of a session_review.
     * A session_review can be a sizable object. Therefore, we provide a resource view that does not return all data
     *
     * Generated from protobuf field <code>.ondewo.nlu.SessionReview.View session_review_view = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setSessionReviewView($var)
    {
        GPBUtil::checkEnum($var, \Ondewo\Nlu\SessionReview\View::class);
        $this->session_review_view = $var;

        return $this;
    }

}

