<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/nlu/llm_evaluation.proto

namespace Ondewo\Nlu;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Request to create a new schedule.
 *
 * Generated from protobuf message <code>ondewo.nlu.CreateLlmEvaluationScheduleRequest</code>
 */
class CreateLlmEvaluationScheduleRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Schedule payload (name / audit / last-next-run fields are server-populated).
     *
     * Generated from protobuf field <code>.ondewo.nlu.LlmEvaluationSchedule llm_evaluation_schedule = 1;</code>
     */
    protected $llm_evaluation_schedule = null;
    /**
     * Project owning the schedule.
     * Format: <code>projects/&lt;project_uuid&gt;/agent</code>.
     *
     * Generated from protobuf field <code>string parent = 2;</code>
     */
    protected $parent = '';
    /**
     * BCP-47 language-code scope (required).
     *
     * Generated from protobuf field <code>string language_code = 3;</code>
     */
    protected $language_code = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Ondewo\Nlu\LlmEvaluationSchedule $llm_evaluation_schedule
     *           Schedule payload (name / audit / last-next-run fields are server-populated).
     *     @type string $parent
     *           Project owning the schedule.
     *           Format: <code>projects/&lt;project_uuid&gt;/agent</code>.
     *     @type string $language_code
     *           BCP-47 language-code scope (required).
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Nlu\LlmEvaluation::initOnce();
        parent::__construct($data);
    }

    /**
     * Schedule payload (name / audit / last-next-run fields are server-populated).
     *
     * Generated from protobuf field <code>.ondewo.nlu.LlmEvaluationSchedule llm_evaluation_schedule = 1;</code>
     * @return \Ondewo\Nlu\LlmEvaluationSchedule|null
     */
    public function getLlmEvaluationSchedule()
    {
        return $this->llm_evaluation_schedule;
    }

    public function hasLlmEvaluationSchedule()
    {
        return isset($this->llm_evaluation_schedule);
    }

    public function clearLlmEvaluationSchedule()
    {
        unset($this->llm_evaluation_schedule);
    }

    /**
     * Schedule payload (name / audit / last-next-run fields are server-populated).
     *
     * Generated from protobuf field <code>.ondewo.nlu.LlmEvaluationSchedule llm_evaluation_schedule = 1;</code>
     * @param \Ondewo\Nlu\LlmEvaluationSchedule $var
     * @return $this
     */
    public function setLlmEvaluationSchedule($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Nlu\LlmEvaluationSchedule::class);
        $this->llm_evaluation_schedule = $var;

        return $this;
    }

    /**
     * Project owning the schedule.
     * Format: <code>projects/&lt;project_uuid&gt;/agent</code>.
     *
     * Generated from protobuf field <code>string parent = 2;</code>
     * @return string
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * Project owning the schedule.
     * Format: <code>projects/&lt;project_uuid&gt;/agent</code>.
     *
     * Generated from protobuf field <code>string parent = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setParent($var)
    {
        GPBUtil::checkString($var, True);
        $this->parent = $var;

        return $this;
    }

    /**
     * BCP-47 language-code scope (required).
     *
     * Generated from protobuf field <code>string language_code = 3;</code>
     * @return string
     */
    public function getLanguageCode()
    {
        return $this->language_code;
    }

    /**
     * BCP-47 language-code scope (required).
     *
     * Generated from protobuf field <code>string language_code = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setLanguageCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->language_code = $var;

        return $this;
    }

}

