<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/nlu/aiservices.proto

namespace Ondewo\Nlu;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * This message contains the configuration of data enrichment
 *
 * Generated from protobuf message <code>ondewo.nlu.DataEnrichmentConfig</code>
 */
class DataEnrichmentConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Entity augmenter configuration
     *
     * Generated from protobuf field <code>.ondewo.nlu.EntityEnrichmentConfig entity_enrichment = 1;</code>
     */
    protected $entity_enrichment = null;
    /**
     * Thesaurus augmenter configuration
     *
     * Generated from protobuf field <code>.ondewo.nlu.ThesaurusEnrichmentConfig thesaurus_enrichment = 2;</code>
     */
    protected $thesaurus_enrichment = null;
    /**
     * Word2Vec augmenter configuration
     *
     * Generated from protobuf field <code>.ondewo.nlu.Word2VecEnrichmentConfig word2vec_enrichment = 3;</code>
     */
    protected $word2vec_enrichment = null;
    /**
     * WordNet augmenter configuration
     *
     * Generated from protobuf field <code>.ondewo.nlu.WordNetAugEnrichmentConfig word_net_enrichment = 4;</code>
     */
    protected $word_net_enrichment = null;
    /**
     * GPT2 augmenter configuration
     *
     * Generated from protobuf field <code>.ondewo.nlu.GPT2EnrichmentConfig gpt2_enrichment = 5;</code>
     */
    protected $gpt2_enrichment = null;
    /**
     * GloVe augmenter configuration
     *
     * Generated from protobuf field <code>.ondewo.nlu.GloVeEnrichmentConfig glove_enrichment = 6;</code>
     */
    protected $glove_enrichment = null;
    /**
     * BERT augmenter configuration
     *
     * Generated from protobuf field <code>.ondewo.nlu.BertAugEnrichmentConfig bert_enrichment = 8;</code>
     */
    protected $bert_enrichment = null;
    /**
     * XLNet augmenter configuration
     *
     * Generated from protobuf field <code>.ondewo.nlu.XLNetAugEnrichmentConfig xlnet_enrichment = 9;</code>
     */
    protected $xlnet_enrichment = null;
    /**
     * Large language model (LLM) augmenter configuration
     *
     * Generated from protobuf field <code>.ondewo.nlu.LlmEnrichmentConfig llm_enrichment = 10;</code>
     */
    protected $llm_enrichment = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Ondewo\Nlu\EntityEnrichmentConfig $entity_enrichment
     *           Entity augmenter configuration
     *     @type \Ondewo\Nlu\ThesaurusEnrichmentConfig $thesaurus_enrichment
     *           Thesaurus augmenter configuration
     *     @type \Ondewo\Nlu\Word2VecEnrichmentConfig $word2vec_enrichment
     *           Word2Vec augmenter configuration
     *     @type \Ondewo\Nlu\WordNetAugEnrichmentConfig $word_net_enrichment
     *           WordNet augmenter configuration
     *     @type \Ondewo\Nlu\GPT2EnrichmentConfig $gpt2_enrichment
     *           GPT2 augmenter configuration
     *     @type \Ondewo\Nlu\GloVeEnrichmentConfig $glove_enrichment
     *           GloVe augmenter configuration
     *     @type \Ondewo\Nlu\BertAugEnrichmentConfig $bert_enrichment
     *           BERT augmenter configuration
     *     @type \Ondewo\Nlu\XLNetAugEnrichmentConfig $xlnet_enrichment
     *           XLNet augmenter configuration
     *     @type \Ondewo\Nlu\LlmEnrichmentConfig $llm_enrichment
     *           Large language model (LLM) augmenter configuration
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Nlu\Aiservices::initOnce();
        parent::__construct($data);
    }

    /**
     * Entity augmenter configuration
     *
     * Generated from protobuf field <code>.ondewo.nlu.EntityEnrichmentConfig entity_enrichment = 1;</code>
     * @return \Ondewo\Nlu\EntityEnrichmentConfig|null
     */
    public function getEntityEnrichment()
    {
        return $this->entity_enrichment;
    }

    public function hasEntityEnrichment()
    {
        return isset($this->entity_enrichment);
    }

    public function clearEntityEnrichment()
    {
        unset($this->entity_enrichment);
    }

    /**
     * Entity augmenter configuration
     *
     * Generated from protobuf field <code>.ondewo.nlu.EntityEnrichmentConfig entity_enrichment = 1;</code>
     * @param \Ondewo\Nlu\EntityEnrichmentConfig $var
     * @return $this
     */
    public function setEntityEnrichment($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Nlu\EntityEnrichmentConfig::class);
        $this->entity_enrichment = $var;

        return $this;
    }

    /**
     * Thesaurus augmenter configuration
     *
     * Generated from protobuf field <code>.ondewo.nlu.ThesaurusEnrichmentConfig thesaurus_enrichment = 2;</code>
     * @return \Ondewo\Nlu\ThesaurusEnrichmentConfig|null
     */
    public function getThesaurusEnrichment()
    {
        return $this->thesaurus_enrichment;
    }

    public function hasThesaurusEnrichment()
    {
        return isset($this->thesaurus_enrichment);
    }

    public function clearThesaurusEnrichment()
    {
        unset($this->thesaurus_enrichment);
    }

    /**
     * Thesaurus augmenter configuration
     *
     * Generated from protobuf field <code>.ondewo.nlu.ThesaurusEnrichmentConfig thesaurus_enrichment = 2;</code>
     * @param \Ondewo\Nlu\ThesaurusEnrichmentConfig $var
     * @return $this
     */
    public function setThesaurusEnrichment($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Nlu\ThesaurusEnrichmentConfig::class);
        $this->thesaurus_enrichment = $var;

        return $this;
    }

    /**
     * Word2Vec augmenter configuration
     *
     * Generated from protobuf field <code>.ondewo.nlu.Word2VecEnrichmentConfig word2vec_enrichment = 3;</code>
     * @return \Ondewo\Nlu\Word2VecEnrichmentConfig|null
     */
    public function getWord2VecEnrichment()
    {
        return $this->word2vec_enrichment;
    }

    public function hasWord2VecEnrichment()
    {
        return isset($this->word2vec_enrichment);
    }

    public function clearWord2VecEnrichment()
    {
        unset($this->word2vec_enrichment);
    }

    /**
     * Word2Vec augmenter configuration
     *
     * Generated from protobuf field <code>.ondewo.nlu.Word2VecEnrichmentConfig word2vec_enrichment = 3;</code>
     * @param \Ondewo\Nlu\Word2VecEnrichmentConfig $var
     * @return $this
     */
    public function setWord2VecEnrichment($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Nlu\Word2VecEnrichmentConfig::class);
        $this->word2vec_enrichment = $var;

        return $this;
    }

    /**
     * WordNet augmenter configuration
     *
     * Generated from protobuf field <code>.ondewo.nlu.WordNetAugEnrichmentConfig word_net_enrichment = 4;</code>
     * @return \Ondewo\Nlu\WordNetAugEnrichmentConfig|null
     */
    public function getWordNetEnrichment()
    {
        return $this->word_net_enrichment;
    }

    public function hasWordNetEnrichment()
    {
        return isset($this->word_net_enrichment);
    }

    public function clearWordNetEnrichment()
    {
        unset($this->word_net_enrichment);
    }

    /**
     * WordNet augmenter configuration
     *
     * Generated from protobuf field <code>.ondewo.nlu.WordNetAugEnrichmentConfig word_net_enrichment = 4;</code>
     * @param \Ondewo\Nlu\WordNetAugEnrichmentConfig $var
     * @return $this
     */
    public function setWordNetEnrichment($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Nlu\WordNetAugEnrichmentConfig::class);
        $this->word_net_enrichment = $var;

        return $this;
    }

    /**
     * GPT2 augmenter configuration
     *
     * Generated from protobuf field <code>.ondewo.nlu.GPT2EnrichmentConfig gpt2_enrichment = 5;</code>
     * @return \Ondewo\Nlu\GPT2EnrichmentConfig|null
     */
    public function getGpt2Enrichment()
    {
        return $this->gpt2_enrichment;
    }

    public function hasGpt2Enrichment()
    {
        return isset($this->gpt2_enrichment);
    }

    public function clearGpt2Enrichment()
    {
        unset($this->gpt2_enrichment);
    }

    /**
     * GPT2 augmenter configuration
     *
     * Generated from protobuf field <code>.ondewo.nlu.GPT2EnrichmentConfig gpt2_enrichment = 5;</code>
     * @param \Ondewo\Nlu\GPT2EnrichmentConfig $var
     * @return $this
     */
    public function setGpt2Enrichment($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Nlu\GPT2EnrichmentConfig::class);
        $this->gpt2_enrichment = $var;

        return $this;
    }

    /**
     * GloVe augmenter configuration
     *
     * Generated from protobuf field <code>.ondewo.nlu.GloVeEnrichmentConfig glove_enrichment = 6;</code>
     * @return \Ondewo\Nlu\GloVeEnrichmentConfig|null
     */
    public function getGloveEnrichment()
    {
        return $this->glove_enrichment;
    }

    public function hasGloveEnrichment()
    {
        return isset($this->glove_enrichment);
    }

    public function clearGloveEnrichment()
    {
        unset($this->glove_enrichment);
    }

    /**
     * GloVe augmenter configuration
     *
     * Generated from protobuf field <code>.ondewo.nlu.GloVeEnrichmentConfig glove_enrichment = 6;</code>
     * @param \Ondewo\Nlu\GloVeEnrichmentConfig $var
     * @return $this
     */
    public function setGloveEnrichment($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Nlu\GloVeEnrichmentConfig::class);
        $this->glove_enrichment = $var;

        return $this;
    }

    /**
     * BERT augmenter configuration
     *
     * Generated from protobuf field <code>.ondewo.nlu.BertAugEnrichmentConfig bert_enrichment = 8;</code>
     * @return \Ondewo\Nlu\BertAugEnrichmentConfig|null
     */
    public function getBertEnrichment()
    {
        return $this->bert_enrichment;
    }

    public function hasBertEnrichment()
    {
        return isset($this->bert_enrichment);
    }

    public function clearBertEnrichment()
    {
        unset($this->bert_enrichment);
    }

    /**
     * BERT augmenter configuration
     *
     * Generated from protobuf field <code>.ondewo.nlu.BertAugEnrichmentConfig bert_enrichment = 8;</code>
     * @param \Ondewo\Nlu\BertAugEnrichmentConfig $var
     * @return $this
     */
    public function setBertEnrichment($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Nlu\BertAugEnrichmentConfig::class);
        $this->bert_enrichment = $var;

        return $this;
    }

    /**
     * XLNet augmenter configuration
     *
     * Generated from protobuf field <code>.ondewo.nlu.XLNetAugEnrichmentConfig xlnet_enrichment = 9;</code>
     * @return \Ondewo\Nlu\XLNetAugEnrichmentConfig|null
     */
    public function getXlnetEnrichment()
    {
        return $this->xlnet_enrichment;
    }

    public function hasXlnetEnrichment()
    {
        return isset($this->xlnet_enrichment);
    }

    public function clearXlnetEnrichment()
    {
        unset($this->xlnet_enrichment);
    }

    /**
     * XLNet augmenter configuration
     *
     * Generated from protobuf field <code>.ondewo.nlu.XLNetAugEnrichmentConfig xlnet_enrichment = 9;</code>
     * @param \Ondewo\Nlu\XLNetAugEnrichmentConfig $var
     * @return $this
     */
    public function setXlnetEnrichment($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Nlu\XLNetAugEnrichmentConfig::class);
        $this->xlnet_enrichment = $var;

        return $this;
    }

    /**
     * Large language model (LLM) augmenter configuration
     *
     * Generated from protobuf field <code>.ondewo.nlu.LlmEnrichmentConfig llm_enrichment = 10;</code>
     * @return \Ondewo\Nlu\LlmEnrichmentConfig|null
     */
    public function getLlmEnrichment()
    {
        return $this->llm_enrichment;
    }

    public function hasLlmEnrichment()
    {
        return isset($this->llm_enrichment);
    }

    public function clearLlmEnrichment()
    {
        unset($this->llm_enrichment);
    }

    /**
     * Large language model (LLM) augmenter configuration
     *
     * Generated from protobuf field <code>.ondewo.nlu.LlmEnrichmentConfig llm_enrichment = 10;</code>
     * @param \Ondewo\Nlu\LlmEnrichmentConfig $var
     * @return $this
     */
    public function setLlmEnrichment($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Nlu\LlmEnrichmentConfig::class);
        $this->llm_enrichment = $var;

        return $this;
    }

}

