<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/nlu/user.proto

namespace Ondewo\Nlu;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Request to delete server role
 *
 * Generated from protobuf message <code>ondewo.nlu.DeleteServerRoleRequest</code>
 */
class DeleteServerRoleRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * role is identified by role id, if empty will throw an error in the backend
     *
     * Generated from protobuf field <code>uint32 role_id = 1;</code>
     */
    protected $role_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $role_id
     *           role is identified by role id, if empty will throw an error in the backend
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Nlu\User::initOnce();
        parent::__construct($data);
    }

    /**
     * role is identified by role id, if empty will throw an error in the backend
     *
     * Generated from protobuf field <code>uint32 role_id = 1;</code>
     * @return int
     */
    public function getRoleId()
    {
        return $this->role_id;
    }

    /**
     * role is identified by role id, if empty will throw an error in the backend
     *
     * Generated from protobuf field <code>uint32 role_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setRoleId($var)
    {
        GPBUtil::checkUint32($var);
        $this->role_id = $var;

        return $this;
    }

}

