<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/nlu/entity_type.proto

namespace Ondewo\Nlu;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * This message is for the entity status
 *
 * Generated from protobuf message <code>ondewo.nlu.EntityStatus</code>
 */
class EntityStatus extends \Google\Protobuf\Internal\Message
{
    protected $entity_or_status;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Ondewo\Nlu\EntityType\Entity $entity
     *           The entity
     *     @type string $error_message
     *           Error message
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Nlu\EntityType::initOnce();
        parent::__construct($data);
    }

    /**
     * The entity
     *
     * Generated from protobuf field <code>.ondewo.nlu.EntityType.Entity entity = 1;</code>
     * @return \Ondewo\Nlu\EntityType\Entity|null
     */
    public function getEntity()
    {
        return $this->readOneof(1);
    }

    public function hasEntity()
    {
        return $this->hasOneof(1);
    }

    /**
     * The entity
     *
     * Generated from protobuf field <code>.ondewo.nlu.EntityType.Entity entity = 1;</code>
     * @param \Ondewo\Nlu\EntityType\Entity $var
     * @return $this
     */
    public function setEntity($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Nlu\EntityType\Entity::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Error message
     *
     * Generated from protobuf field <code>string error_message = 2;</code>
     * @return string
     */
    public function getErrorMessage()
    {
        return $this->readOneof(2);
    }

    public function hasErrorMessage()
    {
        return $this->hasOneof(2);
    }

    /**
     * Error message
     *
     * Generated from protobuf field <code>string error_message = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setErrorMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getEntityOrStatus()
    {
        return $this->whichOneof("entity_or_status");
    }

}

