<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/nlu/session.proto

namespace Ondewo\Nlu;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * A key + up/down counts breakdown bucket (by language / intent / author type / ...).
 * A feedback-native filter for feedback list + analytics requests, complementing SessionFilter (which
 * filters the parent sessions). All set fields are AND-combined; repeated fields are OR-within-field.
 *
 * Generated from protobuf message <code>ondewo.nlu.FeedbackFilter</code>
 */
class FeedbackFilter extends \Google\Protobuf\Internal\Message
{
    /**
     * Keep only feedback with one of these ratings (thumbs up / down / unspecified).
     *
     * Generated from protobuf field <code>repeated .ondewo.nlu.FeedbackRating ratings = 1;</code>
     */
    private $ratings;
    /**
     * Keep only feedback left by one of these author types.
     *
     * Generated from protobuf field <code>repeated .ondewo.nlu.FeedbackAuthorType author_types = 2;</code>
     */
    private $author_types;
    /**
     * When set, keep only feedback that has (true) or lacks (false) a free-text comment.
     *
     * Generated from protobuf field <code>optional bool has_comment = 3;</code>
     */
    protected $has_comment = null;
    /**
     * Keep only feedback created at or after this time (feedback created_at, not session time).
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp earliest = 4;</code>
     */
    protected $earliest = null;
    /**
     * Keep only feedback created at or before this time.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp latest = 5;</code>
     */
    protected $latest = null;
    /**
     * Keep only feedback whose criterion is one of these.
     *
     * Generated from protobuf field <code>repeated string criteria = 6;</code>
     */
    private $criteria;
    /**
     * Keep only feedback whose language code is one of these.
     *
     * Generated from protobuf field <code>repeated string language_codes = 7;</code>
     */
    private $language_codes;
    /**
     * Keep only feedback whose authenticated annotator is one of these user ids.
     *
     * Generated from protobuf field <code>repeated string annotator_user_ids = 8;</code>
     */
    private $annotator_user_ids;
    /**
     * Keep only feedback whose channel origin id is one of these.
     *
     * Generated from protobuf field <code>repeated string origin_ids = 9;</code>
     */
    private $origin_ids;
    /**
     * When set, keep only feedback with a numeric score at or above this value.
     *
     * Generated from protobuf field <code>optional float score_min = 10;</code>
     */
    protected $score_min = null;
    /**
     * When set, keep only feedback with a numeric score at or below this value.
     *
     * Generated from protobuf field <code>optional float score_max = 11;</code>
     */
    protected $score_max = null;
    /**
     * Restrict to session-level or step-level feedback (unspecified means both).
     *
     * Generated from protobuf field <code>.ondewo.nlu.FeedbackScope scope = 12;</code>
     */
    protected $scope = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int[] $ratings
     *           Keep only feedback with one of these ratings (thumbs up / down / unspecified).
     *     @type int[] $author_types
     *           Keep only feedback left by one of these author types.
     *     @type bool $has_comment
     *           When set, keep only feedback that has (true) or lacks (false) a free-text comment.
     *     @type \Google\Protobuf\Timestamp $earliest
     *           Keep only feedback created at or after this time (feedback created_at, not session time).
     *     @type \Google\Protobuf\Timestamp $latest
     *           Keep only feedback created at or before this time.
     *     @type string[] $criteria
     *           Keep only feedback whose criterion is one of these.
     *     @type string[] $language_codes
     *           Keep only feedback whose language code is one of these.
     *     @type string[] $annotator_user_ids
     *           Keep only feedback whose authenticated annotator is one of these user ids.
     *     @type string[] $origin_ids
     *           Keep only feedback whose channel origin id is one of these.
     *     @type float $score_min
     *           When set, keep only feedback with a numeric score at or above this value.
     *     @type float $score_max
     *           When set, keep only feedback with a numeric score at or below this value.
     *     @type int $scope
     *           Restrict to session-level or step-level feedback (unspecified means both).
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Nlu\Session::initOnce();
        parent::__construct($data);
    }

    /**
     * Keep only feedback with one of these ratings (thumbs up / down / unspecified).
     *
     * Generated from protobuf field <code>repeated .ondewo.nlu.FeedbackRating ratings = 1;</code>
     * @return RepeatedField<int>
     */
    public function getRatings()
    {
        return $this->ratings;
    }

    /**
     * Keep only feedback with one of these ratings (thumbs up / down / unspecified).
     *
     * Generated from protobuf field <code>repeated .ondewo.nlu.FeedbackRating ratings = 1;</code>
     * @param int[] $var
     * @return $this
     */
    public function setRatings($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Ondewo\Nlu\FeedbackRating::class);
        $this->ratings = $arr;

        return $this;
    }

    /**
     * Keep only feedback left by one of these author types.
     *
     * Generated from protobuf field <code>repeated .ondewo.nlu.FeedbackAuthorType author_types = 2;</code>
     * @return RepeatedField<int>
     */
    public function getAuthorTypes()
    {
        return $this->author_types;
    }

    /**
     * Keep only feedback left by one of these author types.
     *
     * Generated from protobuf field <code>repeated .ondewo.nlu.FeedbackAuthorType author_types = 2;</code>
     * @param int[] $var
     * @return $this
     */
    public function setAuthorTypes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Ondewo\Nlu\FeedbackAuthorType::class);
        $this->author_types = $arr;

        return $this;
    }

    /**
     * When set, keep only feedback that has (true) or lacks (false) a free-text comment.
     *
     * Generated from protobuf field <code>optional bool has_comment = 3;</code>
     * @return bool
     */
    public function getHasComment()
    {
        return isset($this->has_comment) ? $this->has_comment : false;
    }

    public function hasHasComment()
    {
        return isset($this->has_comment);
    }

    public function clearHasComment()
    {
        unset($this->has_comment);
    }

    /**
     * When set, keep only feedback that has (true) or lacks (false) a free-text comment.
     *
     * Generated from protobuf field <code>optional bool has_comment = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setHasComment($var)
    {
        GPBUtil::checkBool($var);
        $this->has_comment = $var;

        return $this;
    }

    /**
     * Keep only feedback created at or after this time (feedback created_at, not session time).
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp earliest = 4;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getEarliest()
    {
        return $this->earliest;
    }

    public function hasEarliest()
    {
        return isset($this->earliest);
    }

    public function clearEarliest()
    {
        unset($this->earliest);
    }

    /**
     * Keep only feedback created at or after this time (feedback created_at, not session time).
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp earliest = 4;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setEarliest($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->earliest = $var;

        return $this;
    }

    /**
     * Keep only feedback created at or before this time.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp latest = 5;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getLatest()
    {
        return $this->latest;
    }

    public function hasLatest()
    {
        return isset($this->latest);
    }

    public function clearLatest()
    {
        unset($this->latest);
    }

    /**
     * Keep only feedback created at or before this time.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp latest = 5;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setLatest($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->latest = $var;

        return $this;
    }

    /**
     * Keep only feedback whose criterion is one of these.
     *
     * Generated from protobuf field <code>repeated string criteria = 6;</code>
     * @return RepeatedField<string>
     */
    public function getCriteria()
    {
        return $this->criteria;
    }

    /**
     * Keep only feedback whose criterion is one of these.
     *
     * Generated from protobuf field <code>repeated string criteria = 6;</code>
     * @param string[] $var
     * @return $this
     */
    public function setCriteria($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->criteria = $arr;

        return $this;
    }

    /**
     * Keep only feedback whose language code is one of these.
     *
     * Generated from protobuf field <code>repeated string language_codes = 7;</code>
     * @return RepeatedField<string>
     */
    public function getLanguageCodes()
    {
        return $this->language_codes;
    }

    /**
     * Keep only feedback whose language code is one of these.
     *
     * Generated from protobuf field <code>repeated string language_codes = 7;</code>
     * @param string[] $var
     * @return $this
     */
    public function setLanguageCodes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->language_codes = $arr;

        return $this;
    }

    /**
     * Keep only feedback whose authenticated annotator is one of these user ids.
     *
     * Generated from protobuf field <code>repeated string annotator_user_ids = 8;</code>
     * @return RepeatedField<string>
     */
    public function getAnnotatorUserIds()
    {
        return $this->annotator_user_ids;
    }

    /**
     * Keep only feedback whose authenticated annotator is one of these user ids.
     *
     * Generated from protobuf field <code>repeated string annotator_user_ids = 8;</code>
     * @param string[] $var
     * @return $this
     */
    public function setAnnotatorUserIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->annotator_user_ids = $arr;

        return $this;
    }

    /**
     * Keep only feedback whose channel origin id is one of these.
     *
     * Generated from protobuf field <code>repeated string origin_ids = 9;</code>
     * @return RepeatedField<string>
     */
    public function getOriginIds()
    {
        return $this->origin_ids;
    }

    /**
     * Keep only feedback whose channel origin id is one of these.
     *
     * Generated from protobuf field <code>repeated string origin_ids = 9;</code>
     * @param string[] $var
     * @return $this
     */
    public function setOriginIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->origin_ids = $arr;

        return $this;
    }

    /**
     * When set, keep only feedback with a numeric score at or above this value.
     *
     * Generated from protobuf field <code>optional float score_min = 10;</code>
     * @return float
     */
    public function getScoreMin()
    {
        return isset($this->score_min) ? $this->score_min : 0.0;
    }

    public function hasScoreMin()
    {
        return isset($this->score_min);
    }

    public function clearScoreMin()
    {
        unset($this->score_min);
    }

    /**
     * When set, keep only feedback with a numeric score at or above this value.
     *
     * Generated from protobuf field <code>optional float score_min = 10;</code>
     * @param float $var
     * @return $this
     */
    public function setScoreMin($var)
    {
        GPBUtil::checkFloat($var);
        $this->score_min = $var;

        return $this;
    }

    /**
     * When set, keep only feedback with a numeric score at or below this value.
     *
     * Generated from protobuf field <code>optional float score_max = 11;</code>
     * @return float
     */
    public function getScoreMax()
    {
        return isset($this->score_max) ? $this->score_max : 0.0;
    }

    public function hasScoreMax()
    {
        return isset($this->score_max);
    }

    public function clearScoreMax()
    {
        unset($this->score_max);
    }

    /**
     * When set, keep only feedback with a numeric score at or below this value.
     *
     * Generated from protobuf field <code>optional float score_max = 11;</code>
     * @param float $var
     * @return $this
     */
    public function setScoreMax($var)
    {
        GPBUtil::checkFloat($var);
        $this->score_max = $var;

        return $this;
    }

    /**
     * Restrict to session-level or step-level feedback (unspecified means both).
     *
     * Generated from protobuf field <code>.ondewo.nlu.FeedbackScope scope = 12;</code>
     * @return int
     */
    public function getScope()
    {
        return $this->scope;
    }

    /**
     * Restrict to session-level or step-level feedback (unspecified means both).
     *
     * Generated from protobuf field <code>.ondewo.nlu.FeedbackScope scope = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setScope($var)
    {
        GPBUtil::checkEnum($var, \Ondewo\Nlu\FeedbackScope::class);
        $this->scope = $var;

        return $this;
    }

}

