<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/nlu/aiservices.proto

namespace Ondewo\Nlu;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Response containing user sentences
 *
 * Generated from protobuf message <code>ondewo.nlu.GenerateUserSaysResponse</code>
 */
class GenerateUserSaysResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * A list of sampled sentences
     *
     * Generated from protobuf field <code>repeated string user_says = 1;</code>
     */
    private $user_says;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[] $user_says
     *           A list of sampled sentences
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Nlu\Aiservices::initOnce();
        parent::__construct($data);
    }

    /**
     * A list of sampled sentences
     *
     * Generated from protobuf field <code>repeated string user_says = 1;</code>
     * @return RepeatedField<string>
     */
    public function getUserSays()
    {
        return $this->user_says;
    }

    /**
     * A list of sampled sentences
     *
     * Generated from protobuf field <code>repeated string user_says = 1;</code>
     * @param string[] $var
     * @return $this
     */
    public function setUserSays($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->user_says = $arr;

        return $this;
    }

}

