<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/nlu/operations.proto

namespace Ondewo\Nlu;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * The request message for <a href="index.html#ondewo.nlu.Operations.GetRemoteOperationContainerLogs">Operations.GetRemoteOperationContainerLogs</a>.
 *
 * Generated from protobuf message <code>ondewo.nlu.GetRemoteOperationContainerLogsRequest</code>
 */
class GetRemoteOperationContainerLogsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The name of the operation resource whose container logs should be returned.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Only return lines at or above this loguru severity. <code>LOG_SEVERITY_UNSPECIFIED</code> (the
     * default) returns every line regardless of level.
     *
     * Generated from protobuf field <code>.ondewo.nlu.LogSeverity min_log_level = 2;</code>
     */
    protected $min_log_level = 0;
    /**
     * Only return lines whose timestamp is at or after this instant. Unset returns from the start of
     * the available logs.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp start_time = 3;</code>
     */
    protected $start_time = null;
    /**
     * Only return lines whose timestamp is at or before this instant. Unset returns up to the latest
     * available log line.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp end_time = 4;</code>
     */
    protected $end_time = null;
    /**
     * Return at most this many lines, keeping the most recent matches. <code>0</code> (the default)
     * applies a server-side safety cap.
     *
     * Generated from protobuf field <code>int32 max_lines = 5;</code>
     */
    protected $max_lines = 0;
    /**
     * Only return lines whose message matches this regular expression (Python <code>re</code> syntax).
     * Empty (the default) disables regex filtering.
     *
     * Generated from protobuf field <code>string regex = 6;</code>
     */
    protected $regex = '';
    /**
     * Optional. Scope the query to a single container of the operation, identified by its docker
     * container id. Empty (the default) queries the operation&apos;s currently-registered container,
     * preserving the legacy single-container behavior. When the container has finished and been removed,
     * its persisted logs are served from the server-side log archive.
     *
     * Generated from protobuf field <code>string container_id = 7;</code>
     */
    protected $container_id = '';
    /**
     * Optional cursor for infinite-scroll-UP paging: return the newest lines with
     * <a href="index.html#ondewo.nlu.RemoteOperationContainerLogLine">seq</a> &lt; <code>before_seq</code>
     * (older window). <code>0</code> (the default) disables backward paging.
     *
     * Generated from protobuf field <code>int64 before_seq = 8;</code>
     */
    protected $before_seq = 0;
    /**
     * Optional cursor for infinite-scroll-DOWN paging: return lines with <code>seq</code> &gt;
     * <code>after_seq</code> (newer window). <code>0</code> (the default) disables forward paging.
     *
     * Generated from protobuf field <code>int64 after_seq = 9;</code>
     */
    protected $after_seq = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           The name of the operation resource whose container logs should be returned.
     *     @type int $min_log_level
     *           Only return lines at or above this loguru severity. <code>LOG_SEVERITY_UNSPECIFIED</code> (the
     *           default) returns every line regardless of level.
     *     @type \Google\Protobuf\Timestamp $start_time
     *           Only return lines whose timestamp is at or after this instant. Unset returns from the start of
     *           the available logs.
     *     @type \Google\Protobuf\Timestamp $end_time
     *           Only return lines whose timestamp is at or before this instant. Unset returns up to the latest
     *           available log line.
     *     @type int $max_lines
     *           Return at most this many lines, keeping the most recent matches. <code>0</code> (the default)
     *           applies a server-side safety cap.
     *     @type string $regex
     *           Only return lines whose message matches this regular expression (Python <code>re</code> syntax).
     *           Empty (the default) disables regex filtering.
     *     @type string $container_id
     *           Optional. Scope the query to a single container of the operation, identified by its docker
     *           container id. Empty (the default) queries the operation&apos;s currently-registered container,
     *           preserving the legacy single-container behavior. When the container has finished and been removed,
     *           its persisted logs are served from the server-side log archive.
     *     @type int|string $before_seq
     *           Optional cursor for infinite-scroll-UP paging: return the newest lines with
     *           <a href="index.html#ondewo.nlu.RemoteOperationContainerLogLine">seq</a> &lt; <code>before_seq</code>
     *           (older window). <code>0</code> (the default) disables backward paging.
     *     @type int|string $after_seq
     *           Optional cursor for infinite-scroll-DOWN paging: return lines with <code>seq</code> &gt;
     *           <code>after_seq</code> (newer window). <code>0</code> (the default) disables forward paging.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Nlu\Operations::initOnce();
        parent::__construct($data);
    }

    /**
     * The name of the operation resource whose container logs should be returned.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * The name of the operation resource whose container logs should be returned.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Only return lines at or above this loguru severity. <code>LOG_SEVERITY_UNSPECIFIED</code> (the
     * default) returns every line regardless of level.
     *
     * Generated from protobuf field <code>.ondewo.nlu.LogSeverity min_log_level = 2;</code>
     * @return int
     */
    public function getMinLogLevel()
    {
        return $this->min_log_level;
    }

    /**
     * Only return lines at or above this loguru severity. <code>LOG_SEVERITY_UNSPECIFIED</code> (the
     * default) returns every line regardless of level.
     *
     * Generated from protobuf field <code>.ondewo.nlu.LogSeverity min_log_level = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setMinLogLevel($var)
    {
        GPBUtil::checkEnum($var, \Ondewo\Nlu\LogSeverity::class);
        $this->min_log_level = $var;

        return $this;
    }

    /**
     * Only return lines whose timestamp is at or after this instant. Unset returns from the start of
     * the available logs.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp start_time = 3;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getStartTime()
    {
        return $this->start_time;
    }

    public function hasStartTime()
    {
        return isset($this->start_time);
    }

    public function clearStartTime()
    {
        unset($this->start_time);
    }

    /**
     * Only return lines whose timestamp is at or after this instant. Unset returns from the start of
     * the available logs.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp start_time = 3;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setStartTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->start_time = $var;

        return $this;
    }

    /**
     * Only return lines whose timestamp is at or before this instant. Unset returns up to the latest
     * available log line.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp end_time = 4;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getEndTime()
    {
        return $this->end_time;
    }

    public function hasEndTime()
    {
        return isset($this->end_time);
    }

    public function clearEndTime()
    {
        unset($this->end_time);
    }

    /**
     * Only return lines whose timestamp is at or before this instant. Unset returns up to the latest
     * available log line.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp end_time = 4;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setEndTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->end_time = $var;

        return $this;
    }

    /**
     * Return at most this many lines, keeping the most recent matches. <code>0</code> (the default)
     * applies a server-side safety cap.
     *
     * Generated from protobuf field <code>int32 max_lines = 5;</code>
     * @return int
     */
    public function getMaxLines()
    {
        return $this->max_lines;
    }

    /**
     * Return at most this many lines, keeping the most recent matches. <code>0</code> (the default)
     * applies a server-side safety cap.
     *
     * Generated from protobuf field <code>int32 max_lines = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxLines($var)
    {
        GPBUtil::checkInt32($var);
        $this->max_lines = $var;

        return $this;
    }

    /**
     * Only return lines whose message matches this regular expression (Python <code>re</code> syntax).
     * Empty (the default) disables regex filtering.
     *
     * Generated from protobuf field <code>string regex = 6;</code>
     * @return string
     */
    public function getRegex()
    {
        return $this->regex;
    }

    /**
     * Only return lines whose message matches this regular expression (Python <code>re</code> syntax).
     * Empty (the default) disables regex filtering.
     *
     * Generated from protobuf field <code>string regex = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setRegex($var)
    {
        GPBUtil::checkString($var, True);
        $this->regex = $var;

        return $this;
    }

    /**
     * Optional. Scope the query to a single container of the operation, identified by its docker
     * container id. Empty (the default) queries the operation&apos;s currently-registered container,
     * preserving the legacy single-container behavior. When the container has finished and been removed,
     * its persisted logs are served from the server-side log archive.
     *
     * Generated from protobuf field <code>string container_id = 7;</code>
     * @return string
     */
    public function getContainerId()
    {
        return $this->container_id;
    }

    /**
     * Optional. Scope the query to a single container of the operation, identified by its docker
     * container id. Empty (the default) queries the operation&apos;s currently-registered container,
     * preserving the legacy single-container behavior. When the container has finished and been removed,
     * its persisted logs are served from the server-side log archive.
     *
     * Generated from protobuf field <code>string container_id = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setContainerId($var)
    {
        GPBUtil::checkString($var, True);
        $this->container_id = $var;

        return $this;
    }

    /**
     * Optional cursor for infinite-scroll-UP paging: return the newest lines with
     * <a href="index.html#ondewo.nlu.RemoteOperationContainerLogLine">seq</a> &lt; <code>before_seq</code>
     * (older window). <code>0</code> (the default) disables backward paging.
     *
     * Generated from protobuf field <code>int64 before_seq = 8;</code>
     * @return int|string
     */
    public function getBeforeSeq()
    {
        return $this->before_seq;
    }

    /**
     * Optional cursor for infinite-scroll-UP paging: return the newest lines with
     * <a href="index.html#ondewo.nlu.RemoteOperationContainerLogLine">seq</a> &lt; <code>before_seq</code>
     * (older window). <code>0</code> (the default) disables backward paging.
     *
     * Generated from protobuf field <code>int64 before_seq = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBeforeSeq($var)
    {
        GPBUtil::checkInt64($var);
        $this->before_seq = $var;

        return $this;
    }

    /**
     * Optional cursor for infinite-scroll-DOWN paging: return lines with <code>seq</code> &gt;
     * <code>after_seq</code> (newer window). <code>0</code> (the default) disables forward paging.
     *
     * Generated from protobuf field <code>int64 after_seq = 9;</code>
     * @return int|string
     */
    public function getAfterSeq()
    {
        return $this->after_seq;
    }

    /**
     * Optional cursor for infinite-scroll-DOWN paging: return lines with <code>seq</code> &gt;
     * <code>after_seq</code> (newer window). <code>0</code> (the default) disables forward paging.
     *
     * Generated from protobuf field <code>int64 after_seq = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAfterSeq($var)
    {
        GPBUtil::checkInt64($var);
        $this->after_seq = $var;

        return $this;
    }

}

