<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/nlu/agent.proto

namespace Ondewo\Nlu;

use UnexpectedValueException;

/**
 * Defines when to initiate newly created agent when training started
 *
 * Protobuf type <code>ondewo.nlu.InitiationProtocol</code>
 */
class InitiationProtocol
{
    /**
     * after cache successfully built and after each model trained the agent will be updated
     *
     * Generated from protobuf enum <code>AS_SOON_AS_POSSIBLE = 0;</code>
     */
    const AS_SOON_AS_POSSIBLE = 0;
    /**
     * after cache successfully built and all the active models successfully trained
     *
     * Generated from protobuf enum <code>WHEN_TRAINED = 1;</code>
     */
    const WHEN_TRAINED = 1;
    /**
     * do not initiate
     *
     * Generated from protobuf enum <code>NEVER = 2;</code>
     */
    const NEVER = 2;

    private static $valueToName = [
        self::AS_SOON_AS_POSSIBLE => 'AS_SOON_AS_POSSIBLE',
        self::WHEN_TRAINED => 'WHEN_TRAINED',
        self::NEVER => 'NEVER',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

