<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/nlu/session.proto

namespace Ondewo\Nlu;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * This message is a request to list all available audio files of a session
 *
 * Generated from protobuf message <code>ondewo.nlu.ListAudioFilesRequest</code>
 */
class ListAudioFilesRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Required. The project of this agent.
     * Format: <pre><code>projects/&lt;project_uuid&gt;/agent</code></pre>
     *
     * Generated from protobuf field <code>string parent = 1;</code>
     */
    protected $parent = '';
    /**
     * Optional: The unique identifier of the session for which the audio files should be listed
     * Format: <pre><code>projects/&lt;project_uuid&gt;/agent/sessions/&lt;session_uuid&gt;/&lt</code></pre>
     *
     * Generated from protobuf field <code>string session_id = 2;</code>
     */
    protected $session_id = '';
    /**
     * Represents the options for views of resources
     *
     * Generated from protobuf field <code>.ondewo.nlu.ResourceView resource_view = 3;</code>
     */
    protected $resource_view = 0;
    /**
     * Optional: The page token to support pagination.
     * Pagination allows you to retrieve a large result set in smaller, more manageable portions.
     * The page token is a string representing the current index and page size.
     * Valid page token strings:
     * <ul>
     *   <li><code>&quot;&quot;</code> (empty string) - Retrieves the first page.</li>
     *   <li><code>&quot;current_index-0--page_size-20&quot;</code> - Retrieves the first page with a page size of 20.</li>
     *   <li><code>&quot;current_index-1--page_size-20&quot;</code> - Retrieves the second page with a page size of 20.</li>
     * </ul>
     * Index starts at 0.
     * Examples of valid page token strings:
     * <ul>
     *   <li><code>&quot;&quot;</code></li>
     *   <li><code>&quot;current_index-0--page_size-20&quot;</code></li>
     *   <li><code>&quot;current_index-1--page_size-20&quot;</code></li>
     *   <li><code>&quot;current_index-10--page_size-20&quot;</code></li>
     * </ul>
     * Examples of invalid page token strings:
     * <ul>
     *   <li><code>&quot;1&quot;</code></li>
     *   <li><code>&quot;current_index-0--page_size-20&quot;</code></li>
     *   <li><code>&quot;current_index--1--page_size-20&quot;</code></li>
     *   <li><code>&quot;current_index1--page_size-20&quot;</code></li>
     *   <li><code>&quot;current_index-1--page_size--20&quot;</code></li>
     * </ul>
     *
     * Generated from protobuf field <code>string page_token = 4;</code>
     */
    protected $page_token = '';
    /**
     * sorting mode
     *
     * Generated from protobuf field <code>.ondewo.nlu.SortingMode sorting_mode = 5;</code>
     */
    protected $sorting_mode = 0;
    /**
     * Optional. The mask to control which fields gets returned.
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask field_mask = 6;</code>
     */
    protected $field_mask = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $parent
     *           Required. The project of this agent.
     *           Format: <pre><code>projects/&lt;project_uuid&gt;/agent</code></pre>
     *     @type string $session_id
     *           Optional: The unique identifier of the session for which the audio files should be listed
     *           Format: <pre><code>projects/&lt;project_uuid&gt;/agent/sessions/&lt;session_uuid&gt;/&lt</code></pre>
     *     @type int $resource_view
     *           Represents the options for views of resources
     *     @type string $page_token
     *           Optional: The page token to support pagination.
     *           Pagination allows you to retrieve a large result set in smaller, more manageable portions.
     *           The page token is a string representing the current index and page size.
     *           Valid page token strings:
     *           <ul>
     *             <li><code>&quot;&quot;</code> (empty string) - Retrieves the first page.</li>
     *             <li><code>&quot;current_index-0--page_size-20&quot;</code> - Retrieves the first page with a page size of 20.</li>
     *             <li><code>&quot;current_index-1--page_size-20&quot;</code> - Retrieves the second page with a page size of 20.</li>
     *           </ul>
     *           Index starts at 0.
     *           Examples of valid page token strings:
     *           <ul>
     *             <li><code>&quot;&quot;</code></li>
     *             <li><code>&quot;current_index-0--page_size-20&quot;</code></li>
     *             <li><code>&quot;current_index-1--page_size-20&quot;</code></li>
     *             <li><code>&quot;current_index-10--page_size-20&quot;</code></li>
     *           </ul>
     *           Examples of invalid page token strings:
     *           <ul>
     *             <li><code>&quot;1&quot;</code></li>
     *             <li><code>&quot;current_index-0--page_size-20&quot;</code></li>
     *             <li><code>&quot;current_index--1--page_size-20&quot;</code></li>
     *             <li><code>&quot;current_index1--page_size-20&quot;</code></li>
     *             <li><code>&quot;current_index-1--page_size--20&quot;</code></li>
     *           </ul>
     *     @type int $sorting_mode
     *           sorting mode
     *     @type \Google\Protobuf\FieldMask $field_mask
     *           Optional. The mask to control which fields gets returned.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Nlu\Session::initOnce();
        parent::__construct($data);
    }

    /**
     * Required. The project of this agent.
     * Format: <pre><code>projects/&lt;project_uuid&gt;/agent</code></pre>
     *
     * Generated from protobuf field <code>string parent = 1;</code>
     * @return string
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * Required. The project of this agent.
     * Format: <pre><code>projects/&lt;project_uuid&gt;/agent</code></pre>
     *
     * Generated from protobuf field <code>string parent = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setParent($var)
    {
        GPBUtil::checkString($var, True);
        $this->parent = $var;

        return $this;
    }

    /**
     * Optional: The unique identifier of the session for which the audio files should be listed
     * Format: <pre><code>projects/&lt;project_uuid&gt;/agent/sessions/&lt;session_uuid&gt;/&lt</code></pre>
     *
     * Generated from protobuf field <code>string session_id = 2;</code>
     * @return string
     */
    public function getSessionId()
    {
        return $this->session_id;
    }

    /**
     * Optional: The unique identifier of the session for which the audio files should be listed
     * Format: <pre><code>projects/&lt;project_uuid&gt;/agent/sessions/&lt;session_uuid&gt;/&lt</code></pre>
     *
     * Generated from protobuf field <code>string session_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSessionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->session_id = $var;

        return $this;
    }

    /**
     * Represents the options for views of resources
     *
     * Generated from protobuf field <code>.ondewo.nlu.ResourceView resource_view = 3;</code>
     * @return int
     */
    public function getResourceView()
    {
        return $this->resource_view;
    }

    /**
     * Represents the options for views of resources
     *
     * Generated from protobuf field <code>.ondewo.nlu.ResourceView resource_view = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setResourceView($var)
    {
        GPBUtil::checkEnum($var, \Ondewo\Nlu\ResourceView::class);
        $this->resource_view = $var;

        return $this;
    }

    /**
     * Optional: The page token to support pagination.
     * Pagination allows you to retrieve a large result set in smaller, more manageable portions.
     * The page token is a string representing the current index and page size.
     * Valid page token strings:
     * <ul>
     *   <li><code>&quot;&quot;</code> (empty string) - Retrieves the first page.</li>
     *   <li><code>&quot;current_index-0--page_size-20&quot;</code> - Retrieves the first page with a page size of 20.</li>
     *   <li><code>&quot;current_index-1--page_size-20&quot;</code> - Retrieves the second page with a page size of 20.</li>
     * </ul>
     * Index starts at 0.
     * Examples of valid page token strings:
     * <ul>
     *   <li><code>&quot;&quot;</code></li>
     *   <li><code>&quot;current_index-0--page_size-20&quot;</code></li>
     *   <li><code>&quot;current_index-1--page_size-20&quot;</code></li>
     *   <li><code>&quot;current_index-10--page_size-20&quot;</code></li>
     * </ul>
     * Examples of invalid page token strings:
     * <ul>
     *   <li><code>&quot;1&quot;</code></li>
     *   <li><code>&quot;current_index-0--page_size-20&quot;</code></li>
     *   <li><code>&quot;current_index--1--page_size-20&quot;</code></li>
     *   <li><code>&quot;current_index1--page_size-20&quot;</code></li>
     *   <li><code>&quot;current_index-1--page_size--20&quot;</code></li>
     * </ul>
     *
     * Generated from protobuf field <code>string page_token = 4;</code>
     * @return string
     */
    public function getPageToken()
    {
        return $this->page_token;
    }

    /**
     * Optional: The page token to support pagination.
     * Pagination allows you to retrieve a large result set in smaller, more manageable portions.
     * The page token is a string representing the current index and page size.
     * Valid page token strings:
     * <ul>
     *   <li><code>&quot;&quot;</code> (empty string) - Retrieves the first page.</li>
     *   <li><code>&quot;current_index-0--page_size-20&quot;</code> - Retrieves the first page with a page size of 20.</li>
     *   <li><code>&quot;current_index-1--page_size-20&quot;</code> - Retrieves the second page with a page size of 20.</li>
     * </ul>
     * Index starts at 0.
     * Examples of valid page token strings:
     * <ul>
     *   <li><code>&quot;&quot;</code></li>
     *   <li><code>&quot;current_index-0--page_size-20&quot;</code></li>
     *   <li><code>&quot;current_index-1--page_size-20&quot;</code></li>
     *   <li><code>&quot;current_index-10--page_size-20&quot;</code></li>
     * </ul>
     * Examples of invalid page token strings:
     * <ul>
     *   <li><code>&quot;1&quot;</code></li>
     *   <li><code>&quot;current_index-0--page_size-20&quot;</code></li>
     *   <li><code>&quot;current_index--1--page_size-20&quot;</code></li>
     *   <li><code>&quot;current_index1--page_size-20&quot;</code></li>
     *   <li><code>&quot;current_index-1--page_size--20&quot;</code></li>
     * </ul>
     *
     * Generated from protobuf field <code>string page_token = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPageToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->page_token = $var;

        return $this;
    }

    /**
     * sorting mode
     *
     * Generated from protobuf field <code>.ondewo.nlu.SortingMode sorting_mode = 5;</code>
     * @return int
     */
    public function getSortingMode()
    {
        return $this->sorting_mode;
    }

    /**
     * sorting mode
     *
     * Generated from protobuf field <code>.ondewo.nlu.SortingMode sorting_mode = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setSortingMode($var)
    {
        GPBUtil::checkEnum($var, \Ondewo\Nlu\SortingMode::class);
        $this->sorting_mode = $var;

        return $this;
    }

    /**
     * Optional. The mask to control which fields gets returned.
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask field_mask = 6;</code>
     * @return \Google\Protobuf\FieldMask|null
     */
    public function getFieldMask()
    {
        return $this->field_mask;
    }

    public function hasFieldMask()
    {
        return isset($this->field_mask);
    }

    public function clearFieldMask()
    {
        unset($this->field_mask);
    }

    /**
     * Optional. The mask to control which fields gets returned.
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask field_mask = 6;</code>
     * @param \Google\Protobuf\FieldMask $var
     * @return $this
     */
    public function setFieldMask($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\FieldMask::class);
        $this->field_mask = $var;

        return $this;
    }

}

