<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/nlu/entity_type.proto

namespace Ondewo\Nlu;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * The response message for <a href="index.html#ondewo.nlu.EntityTypes.ListEntityTypes">EntityTypes.ListEntityTypes</a>.
 *
 * Generated from protobuf message <code>ondewo.nlu.ListEntityTypesResponse</code>
 */
class ListEntityTypesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The list of agent entity types. There will be a maximum number of items
     * returned based on the page_token field in the request.
     *
     * Generated from protobuf field <code>repeated .ondewo.nlu.EntityType entity_types = 1;</code>
     */
    private $entity_types;
    /**
     * The next_page_token is used to retrieve the next page of a returned result,
     * e.g. next_page_token is current_index-2
     *
     * Generated from protobuf field <code>string next_page_token = 2;</code>
     */
    protected $next_page_token = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Ondewo\Nlu\EntityType[] $entity_types
     *           The list of agent entity types. There will be a maximum number of items
     *           returned based on the page_token field in the request.
     *     @type string $next_page_token
     *           The next_page_token is used to retrieve the next page of a returned result,
     *           e.g. next_page_token is current_index-2
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Nlu\EntityType::initOnce();
        parent::__construct($data);
    }

    /**
     * The list of agent entity types. There will be a maximum number of items
     * returned based on the page_token field in the request.
     *
     * Generated from protobuf field <code>repeated .ondewo.nlu.EntityType entity_types = 1;</code>
     * @return RepeatedField<\Ondewo\Nlu\EntityType>
     */
    public function getEntityTypes()
    {
        return $this->entity_types;
    }

    /**
     * The list of agent entity types. There will be a maximum number of items
     * returned based on the page_token field in the request.
     *
     * Generated from protobuf field <code>repeated .ondewo.nlu.EntityType entity_types = 1;</code>
     * @param \Ondewo\Nlu\EntityType[] $var
     * @return $this
     */
    public function setEntityTypes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Ondewo\Nlu\EntityType::class);
        $this->entity_types = $arr;

        return $this;
    }

    /**
     * The next_page_token is used to retrieve the next page of a returned result,
     * e.g. next_page_token is current_index-2
     *
     * Generated from protobuf field <code>string next_page_token = 2;</code>
     * @return string
     */
    public function getNextPageToken()
    {
        return $this->next_page_token;
    }

    /**
     * The next_page_token is used to retrieve the next page of a returned result,
     * e.g. next_page_token is current_index-2
     *
     * Generated from protobuf field <code>string next_page_token = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNextPageToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->next_page_token = $var;

        return $this;
    }

}

