<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/nlu/user.proto

namespace Ondewo\Nlu;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Response containing list of server roles
 *
 * Generated from protobuf message <code>ondewo.nlu.ListServerRolesResponse</code>
 */
class ListServerRolesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The list of server roles. There will be a maximum number of items
     * returned based on the page_token field in the request.
     *
     * Generated from protobuf field <code>repeated .ondewo.nlu.ServerRole server_roles = 1;</code>
     */
    private $server_roles;
    /**
     * The next_page_token is used to retrieve the next page of a returned result,
     * e.g. next_page_token is current_index-2
     *
     * Generated from protobuf field <code>string next_page_token = 2;</code>
     */
    protected $next_page_token = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Ondewo\Nlu\ServerRole[] $server_roles
     *           The list of server roles. There will be a maximum number of items
     *           returned based on the page_token field in the request.
     *     @type string $next_page_token
     *           The next_page_token is used to retrieve the next page of a returned result,
     *           e.g. next_page_token is current_index-2
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Nlu\User::initOnce();
        parent::__construct($data);
    }

    /**
     * The list of server roles. There will be a maximum number of items
     * returned based on the page_token field in the request.
     *
     * Generated from protobuf field <code>repeated .ondewo.nlu.ServerRole server_roles = 1;</code>
     * @return RepeatedField<\Ondewo\Nlu\ServerRole>
     */
    public function getServerRoles()
    {
        return $this->server_roles;
    }

    /**
     * The list of server roles. There will be a maximum number of items
     * returned based on the page_token field in the request.
     *
     * Generated from protobuf field <code>repeated .ondewo.nlu.ServerRole server_roles = 1;</code>
     * @param \Ondewo\Nlu\ServerRole[] $var
     * @return $this
     */
    public function setServerRoles($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Ondewo\Nlu\ServerRole::class);
        $this->server_roles = $arr;

        return $this;
    }

    /**
     * The next_page_token is used to retrieve the next page of a returned result,
     * e.g. next_page_token is current_index-2
     *
     * Generated from protobuf field <code>string next_page_token = 2;</code>
     * @return string
     */
    public function getNextPageToken()
    {
        return $this->next_page_token;
    }

    /**
     * The next_page_token is used to retrieve the next page of a returned result,
     * e.g. next_page_token is current_index-2
     *
     * Generated from protobuf field <code>string next_page_token = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNextPageToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->next_page_token = $var;

        return $this;
    }

}

