<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/nlu/user.proto

namespace Ondewo\Nlu;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Server permissions
 *
 * Generated from protobuf message <code>ondewo.nlu.ListServerPermissionsRequest</code>
 */
class ListServerPermissionsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Optional: The page token to support pagination.
     * Pagination allows you to retrieve a large result set in smaller, more manageable portions.
     * The page token is a string representing the current index and page size.
     * Valid page token strings:
     * <ul>
     *     <li><code>&quot;&quot;</code> (empty string) - Retrieves the first page.</li>
     *     <li><code>&quot;current_index-0--page_size-20&quot;</code> - Retrieves the first page with a page size of 20.</li>
     *     <li><code>&quot;current_index-1--page_size-20&quot;</code> - Retrieves the second page with a page size of 20.</li>
     * </ul>
     * Index starts at 0.
     * Examples of valid page token strings:
     * <ul>
     *     <li><code>&quot;&quot;</code></li>
     *     <li><code>&quot;current_index-0--page_size-20&quot;</code></li>
     *     <li><code>&quot;current_index-1--page_size-20&quot;</code></li>
     *     <li><code>&quot;current_index-10--page_size-20&quot;</code></li>
     * </ul>
     * Examples of invalid page token strings:
     * <ul>
     *     <li><code>&quot;1&quot;</code></li>
     *     <li><code>&quot;current_index-0--page_size-20&quot;</code></li>
     *     <li><code>&quot;current_index--1--page_size-20&quot;</code></li>
     *     <li><code>&quot;current_index1--page_size-20&quot;</code></li>
     *     <li><code>&quot;current_index-1--page_size--20&quot;</code></li>
     * </ul>
     *
     * Generated from protobuf field <code>string page_token = 1;</code>
     */
    protected $page_token = '';
    /**
     * Optional. The mask to control which fields gets returned.
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask field_mask = 2;</code>
     */
    protected $field_mask = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $page_token
     *           Optional: The page token to support pagination.
     *           Pagination allows you to retrieve a large result set in smaller, more manageable portions.
     *           The page token is a string representing the current index and page size.
     *           Valid page token strings:
     *           <ul>
     *               <li><code>&quot;&quot;</code> (empty string) - Retrieves the first page.</li>
     *               <li><code>&quot;current_index-0--page_size-20&quot;</code> - Retrieves the first page with a page size of 20.</li>
     *               <li><code>&quot;current_index-1--page_size-20&quot;</code> - Retrieves the second page with a page size of 20.</li>
     *           </ul>
     *           Index starts at 0.
     *           Examples of valid page token strings:
     *           <ul>
     *               <li><code>&quot;&quot;</code></li>
     *               <li><code>&quot;current_index-0--page_size-20&quot;</code></li>
     *               <li><code>&quot;current_index-1--page_size-20&quot;</code></li>
     *               <li><code>&quot;current_index-10--page_size-20&quot;</code></li>
     *           </ul>
     *           Examples of invalid page token strings:
     *           <ul>
     *               <li><code>&quot;1&quot;</code></li>
     *               <li><code>&quot;current_index-0--page_size-20&quot;</code></li>
     *               <li><code>&quot;current_index--1--page_size-20&quot;</code></li>
     *               <li><code>&quot;current_index1--page_size-20&quot;</code></li>
     *               <li><code>&quot;current_index-1--page_size--20&quot;</code></li>
     *           </ul>
     *     @type \Google\Protobuf\FieldMask $field_mask
     *           Optional. The mask to control which fields gets returned.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Nlu\User::initOnce();
        parent::__construct($data);
    }

    /**
     * Optional: The page token to support pagination.
     * Pagination allows you to retrieve a large result set in smaller, more manageable portions.
     * The page token is a string representing the current index and page size.
     * Valid page token strings:
     * <ul>
     *     <li><code>&quot;&quot;</code> (empty string) - Retrieves the first page.</li>
     *     <li><code>&quot;current_index-0--page_size-20&quot;</code> - Retrieves the first page with a page size of 20.</li>
     *     <li><code>&quot;current_index-1--page_size-20&quot;</code> - Retrieves the second page with a page size of 20.</li>
     * </ul>
     * Index starts at 0.
     * Examples of valid page token strings:
     * <ul>
     *     <li><code>&quot;&quot;</code></li>
     *     <li><code>&quot;current_index-0--page_size-20&quot;</code></li>
     *     <li><code>&quot;current_index-1--page_size-20&quot;</code></li>
     *     <li><code>&quot;current_index-10--page_size-20&quot;</code></li>
     * </ul>
     * Examples of invalid page token strings:
     * <ul>
     *     <li><code>&quot;1&quot;</code></li>
     *     <li><code>&quot;current_index-0--page_size-20&quot;</code></li>
     *     <li><code>&quot;current_index--1--page_size-20&quot;</code></li>
     *     <li><code>&quot;current_index1--page_size-20&quot;</code></li>
     *     <li><code>&quot;current_index-1--page_size--20&quot;</code></li>
     * </ul>
     *
     * Generated from protobuf field <code>string page_token = 1;</code>
     * @return string
     */
    public function getPageToken()
    {
        return $this->page_token;
    }

    /**
     * Optional: The page token to support pagination.
     * Pagination allows you to retrieve a large result set in smaller, more manageable portions.
     * The page token is a string representing the current index and page size.
     * Valid page token strings:
     * <ul>
     *     <li><code>&quot;&quot;</code> (empty string) - Retrieves the first page.</li>
     *     <li><code>&quot;current_index-0--page_size-20&quot;</code> - Retrieves the first page with a page size of 20.</li>
     *     <li><code>&quot;current_index-1--page_size-20&quot;</code> - Retrieves the second page with a page size of 20.</li>
     * </ul>
     * Index starts at 0.
     * Examples of valid page token strings:
     * <ul>
     *     <li><code>&quot;&quot;</code></li>
     *     <li><code>&quot;current_index-0--page_size-20&quot;</code></li>
     *     <li><code>&quot;current_index-1--page_size-20&quot;</code></li>
     *     <li><code>&quot;current_index-10--page_size-20&quot;</code></li>
     * </ul>
     * Examples of invalid page token strings:
     * <ul>
     *     <li><code>&quot;1&quot;</code></li>
     *     <li><code>&quot;current_index-0--page_size-20&quot;</code></li>
     *     <li><code>&quot;current_index--1--page_size-20&quot;</code></li>
     *     <li><code>&quot;current_index1--page_size-20&quot;</code></li>
     *     <li><code>&quot;current_index-1--page_size--20&quot;</code></li>
     * </ul>
     *
     * Generated from protobuf field <code>string page_token = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPageToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->page_token = $var;

        return $this;
    }

    /**
     * Optional. The mask to control which fields gets returned.
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask field_mask = 2;</code>
     * @return \Google\Protobuf\FieldMask|null
     */
    public function getFieldMask()
    {
        return $this->field_mask;
    }

    public function hasFieldMask()
    {
        return isset($this->field_mask);
    }

    public function clearFieldMask()
    {
        unset($this->field_mask);
    }

    /**
     * Optional. The mask to control which fields gets returned.
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask field_mask = 2;</code>
     * @param \Google\Protobuf\FieldMask $var
     * @return $this
     */
    public function setFieldMask($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\FieldMask::class);
        $this->field_mask = $var;

        return $this;
    }

}

