<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/nlu/llm_evaluation.proto

namespace Ondewo\Nlu;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * One weighted criterion row of a scorecard.
 *
 * Generated from protobuf message <code>ondewo.nlu.LlmEvaluationScorecardComponent</code>
 */
class LlmEvaluationScorecardComponent extends \Google\Protobuf\Internal\Message
{
    /**
     * Criterion label the component aggregates (e.g. "faithfulness").
     *
     * Generated from protobuf field <code>string criterion = 1;</code>
     */
    protected $criterion = '';
    /**
     * Relative weight of the component (normalized server-side).
     *
     * Generated from protobuf field <code>double weight = 2;</code>
     */
    protected $weight = 0.0;
    /**
     * Target score (0.0-1.0) the criterion should reach.
     *
     * Generated from protobuf field <code>double target_score = 3;</code>
     */
    protected $target_score = 0.0;
    /**
     * Optional. Logical evaluator name backing the criterion.
     *
     * Generated from protobuf field <code>string evaluator_name = 4;</code>
     */
    protected $evaluator_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $criterion
     *           Criterion label the component aggregates (e.g. "faithfulness").
     *     @type float $weight
     *           Relative weight of the component (normalized server-side).
     *     @type float $target_score
     *           Target score (0.0-1.0) the criterion should reach.
     *     @type string $evaluator_name
     *           Optional. Logical evaluator name backing the criterion.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Nlu\LlmEvaluation::initOnce();
        parent::__construct($data);
    }

    /**
     * Criterion label the component aggregates (e.g. "faithfulness").
     *
     * Generated from protobuf field <code>string criterion = 1;</code>
     * @return string
     */
    public function getCriterion()
    {
        return $this->criterion;
    }

    /**
     * Criterion label the component aggregates (e.g. "faithfulness").
     *
     * Generated from protobuf field <code>string criterion = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCriterion($var)
    {
        GPBUtil::checkString($var, True);
        $this->criterion = $var;

        return $this;
    }

    /**
     * Relative weight of the component (normalized server-side).
     *
     * Generated from protobuf field <code>double weight = 2;</code>
     * @return float
     */
    public function getWeight()
    {
        return $this->weight;
    }

    /**
     * Relative weight of the component (normalized server-side).
     *
     * Generated from protobuf field <code>double weight = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setWeight($var)
    {
        GPBUtil::checkDouble($var);
        $this->weight = $var;

        return $this;
    }

    /**
     * Target score (0.0-1.0) the criterion should reach.
     *
     * Generated from protobuf field <code>double target_score = 3;</code>
     * @return float
     */
    public function getTargetScore()
    {
        return $this->target_score;
    }

    /**
     * Target score (0.0-1.0) the criterion should reach.
     *
     * Generated from protobuf field <code>double target_score = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setTargetScore($var)
    {
        GPBUtil::checkDouble($var);
        $this->target_score = $var;

        return $this;
    }

    /**
     * Optional. Logical evaluator name backing the criterion.
     *
     * Generated from protobuf field <code>string evaluator_name = 4;</code>
     * @return string
     */
    public function getEvaluatorName()
    {
        return $this->evaluator_name;
    }

    /**
     * Optional. Logical evaluator name backing the criterion.
     *
     * Generated from protobuf field <code>string evaluator_name = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setEvaluatorName($var)
    {
        GPBUtil::checkString($var, True);
        $this->evaluator_name = $var;

        return $this;
    }

}

