<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/nlu/llm_evaluation.proto

namespace Ondewo\Nlu;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Filter conditions for ListReports. All fields are optional; multiple fields
 * set at the same time are combined via logical AND.
 *
 * Generated from protobuf message <code>ondewo.nlu.LlmEvaluationReportFilter</code>
 */
class LlmEvaluationReportFilter extends \Google\Protobuf\Internal\Message
{
    /**
     * Optional. Match only reports whose display name contains this substring
     * (case-insensitive).
     *
     * Generated from protobuf field <code>string display_name = 1;</code>
     */
    protected $display_name = '';
    /**
     * Optional. Match only reports of this logical type.
     *
     * Generated from protobuf field <code>string report_type = 2;</code>
     */
    protected $report_type = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $display_name
     *           Optional. Match only reports whose display name contains this substring
     *           (case-insensitive).
     *     @type string $report_type
     *           Optional. Match only reports of this logical type.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Nlu\LlmEvaluation::initOnce();
        parent::__construct($data);
    }

    /**
     * Optional. Match only reports whose display name contains this substring
     * (case-insensitive).
     *
     * Generated from protobuf field <code>string display_name = 1;</code>
     * @return string
     */
    public function getDisplayName()
    {
        return $this->display_name;
    }

    /**
     * Optional. Match only reports whose display name contains this substring
     * (case-insensitive).
     *
     * Generated from protobuf field <code>string display_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDisplayName($var)
    {
        GPBUtil::checkString($var, True);
        $this->display_name = $var;

        return $this;
    }

    /**
     * Optional. Match only reports of this logical type.
     *
     * Generated from protobuf field <code>string report_type = 2;</code>
     * @return string
     */
    public function getReportType()
    {
        return $this->report_type;
    }

    /**
     * Optional. Match only reports of this logical type.
     *
     * Generated from protobuf field <code>string report_type = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setReportType($var)
    {
        GPBUtil::checkString($var, True);
        $this->report_type = $var;

        return $this;
    }

}

