<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/nlu/session.proto

namespace Ondewo\Nlu;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Native-safety breakdown aggregate across the LLM calls in scope. Computed from
 * the per-call LlmSafetyAssessment records.
 *
 * Generated from protobuf message <code>ondewo.nlu.LlmSafetyStats</code>
 */
class LlmSafetyStats extends \Google\Protobuf\Internal\Message
{
    /**
     * Number of LLM calls that carried a safety assessment in scope.
     *
     * Generated from protobuf field <code>int64 total_assessed = 1;</code>
     */
    protected $total_assessed = 0;
    /**
     * Number of assessed calls with at least one flagged category.
     *
     * Generated from protobuf field <code>int64 flagged_count = 2;</code>
     */
    protected $flagged_count = 0;
    /**
     * Mean LlmSafetyAssessment.safety_score across assessed calls
     * (<code>1.0</code> = fully safe).
     *
     * Generated from protobuf field <code>double overall_safety_score = 3;</code>
     */
    protected $overall_safety_score = 0.0;
    /**
     * Per-category counts and rates, descending by count.
     *
     * Generated from protobuf field <code>repeated .ondewo.nlu.LlmSafetyCategoryStat category_stats = 4;</code>
     */
    private $category_stats;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $total_assessed
     *           Number of LLM calls that carried a safety assessment in scope.
     *     @type int|string $flagged_count
     *           Number of assessed calls with at least one flagged category.
     *     @type float $overall_safety_score
     *           Mean LlmSafetyAssessment.safety_score across assessed calls
     *           (<code>1.0</code> = fully safe).
     *     @type \Ondewo\Nlu\LlmSafetyCategoryStat[] $category_stats
     *           Per-category counts and rates, descending by count.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Nlu\Session::initOnce();
        parent::__construct($data);
    }

    /**
     * Number of LLM calls that carried a safety assessment in scope.
     *
     * Generated from protobuf field <code>int64 total_assessed = 1;</code>
     * @return int|string
     */
    public function getTotalAssessed()
    {
        return $this->total_assessed;
    }

    /**
     * Number of LLM calls that carried a safety assessment in scope.
     *
     * Generated from protobuf field <code>int64 total_assessed = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalAssessed($var)
    {
        GPBUtil::checkInt64($var);
        $this->total_assessed = $var;

        return $this;
    }

    /**
     * Number of assessed calls with at least one flagged category.
     *
     * Generated from protobuf field <code>int64 flagged_count = 2;</code>
     * @return int|string
     */
    public function getFlaggedCount()
    {
        return $this->flagged_count;
    }

    /**
     * Number of assessed calls with at least one flagged category.
     *
     * Generated from protobuf field <code>int64 flagged_count = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFlaggedCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->flagged_count = $var;

        return $this;
    }

    /**
     * Mean LlmSafetyAssessment.safety_score across assessed calls
     * (<code>1.0</code> = fully safe).
     *
     * Generated from protobuf field <code>double overall_safety_score = 3;</code>
     * @return float
     */
    public function getOverallSafetyScore()
    {
        return $this->overall_safety_score;
    }

    /**
     * Mean LlmSafetyAssessment.safety_score across assessed calls
     * (<code>1.0</code> = fully safe).
     *
     * Generated from protobuf field <code>double overall_safety_score = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setOverallSafetyScore($var)
    {
        GPBUtil::checkDouble($var);
        $this->overall_safety_score = $var;

        return $this;
    }

    /**
     * Per-category counts and rates, descending by count.
     *
     * Generated from protobuf field <code>repeated .ondewo.nlu.LlmSafetyCategoryStat category_stats = 4;</code>
     * @return RepeatedField<\Ondewo\Nlu\LlmSafetyCategoryStat>
     */
    public function getCategoryStats()
    {
        return $this->category_stats;
    }

    /**
     * Per-category counts and rates, descending by count.
     *
     * Generated from protobuf field <code>repeated .ondewo.nlu.LlmSafetyCategoryStat category_stats = 4;</code>
     * @param \Ondewo\Nlu\LlmSafetyCategoryStat[] $var
     * @return $this
     */
    public function setCategoryStats($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Ondewo\Nlu\LlmSafetyCategoryStat::class);
        $this->category_stats = $arr;

        return $this;
    }

}

