<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/nlu/session.proto

namespace Ondewo\Nlu;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Emitted on a streaming DetectIntent when running token counts update.
 *
 * Generated from protobuf message <code>ondewo.nlu.LlmTokenUsageUpdateEvent</code>
 */
class LlmTokenUsageUpdateEvent extends \Google\Protobuf\Internal\Message
{
    /**
     * Groups events under an LlmTelemetry entry.
     *
     * Generated from protobuf field <code>string llm_call_id = 1;</code>
     */
    protected $llm_call_id = '';
    /**
     * Running totals for that llm_call.
     *
     * Generated from protobuf field <code>.ondewo.nlu.LlmTokenUsage llm_token_usage = 2;</code>
     */
    protected $llm_token_usage = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $llm_call_id
     *           Groups events under an LlmTelemetry entry.
     *     @type \Ondewo\Nlu\LlmTokenUsage $llm_token_usage
     *           Running totals for that llm_call.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Nlu\Session::initOnce();
        parent::__construct($data);
    }

    /**
     * Groups events under an LlmTelemetry entry.
     *
     * Generated from protobuf field <code>string llm_call_id = 1;</code>
     * @return string
     */
    public function getLlmCallId()
    {
        return $this->llm_call_id;
    }

    /**
     * Groups events under an LlmTelemetry entry.
     *
     * Generated from protobuf field <code>string llm_call_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setLlmCallId($var)
    {
        GPBUtil::checkString($var, True);
        $this->llm_call_id = $var;

        return $this;
    }

    /**
     * Running totals for that llm_call.
     *
     * Generated from protobuf field <code>.ondewo.nlu.LlmTokenUsage llm_token_usage = 2;</code>
     * @return \Ondewo\Nlu\LlmTokenUsage|null
     */
    public function getLlmTokenUsage()
    {
        return $this->llm_token_usage;
    }

    public function hasLlmTokenUsage()
    {
        return isset($this->llm_token_usage);
    }

    public function clearLlmTokenUsage()
    {
        unset($this->llm_token_usage);
    }

    /**
     * Running totals for that llm_call.
     *
     * Generated from protobuf field <code>.ondewo.nlu.LlmTokenUsage llm_token_usage = 2;</code>
     * @param \Ondewo\Nlu\LlmTokenUsage $var
     * @return $this
     */
    public function setLlmTokenUsage($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Nlu\LlmTokenUsage::class);
        $this->llm_token_usage = $var;

        return $this;
    }

}

