<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/nlu/common.proto

namespace Ondewo\Nlu;

use UnexpectedValueException;

/**
 * Log levels for various system operations based on Loguru log levels.
 *
 * Protobuf type <code>ondewo.nlu.LogSeverity</code>
 */
class LogSeverity
{
    /**
     * Unspecified log level.
     *
     * Generated from protobuf enum <code>LOG_SEVERITY_UNSPECIFIED = 0;</code>
     */
    const LOG_SEVERITY_UNSPECIFIED = 0;
    /**
     * Trace level - lowest level, most detailed.
     *
     * Generated from protobuf enum <code>LOG_SEVERITY_TRACE = 1;</code>
     */
    const LOG_SEVERITY_TRACE = 1;
    /**
     * Debug level - detailed information for troubleshooting.
     *
     * Generated from protobuf enum <code>LOG_SEVERITY_DEBUG = 2;</code>
     */
    const LOG_SEVERITY_DEBUG = 2;
    /**
     * Info level - general operational messages.
     *
     * Generated from protobuf enum <code>LOG_SEVERITY_INFO = 3;</code>
     */
    const LOG_SEVERITY_INFO = 3;
    /**
     * Success level - successful completion of an operation.
     *
     * Generated from protobuf enum <code>LOG_SEVERITY_SUCCESS = 4;</code>
     */
    const LOG_SEVERITY_SUCCESS = 4;
    /**
     * Warning level - potential issues that don't stop execution.
     *
     * Generated from protobuf enum <code>LOG_SEVERITY_WARNING = 5;</code>
     */
    const LOG_SEVERITY_WARNING = 5;
    /**
     * Error level - serious issues that might affect results.
     *
     * Generated from protobuf enum <code>LOG_SEVERITY_ERROR = 6;</code>
     */
    const LOG_SEVERITY_ERROR = 6;
    /**
     * Critical level - critical failures that stop the process.
     *
     * Generated from protobuf enum <code>LOG_SEVERITY_CRITICAL = 7;</code>
     */
    const LOG_SEVERITY_CRITICAL = 7;

    private static $valueToName = [
        self::LOG_SEVERITY_UNSPECIFIED => 'LOG_SEVERITY_UNSPECIFIED',
        self::LOG_SEVERITY_TRACE => 'LOG_SEVERITY_TRACE',
        self::LOG_SEVERITY_DEBUG => 'LOG_SEVERITY_DEBUG',
        self::LOG_SEVERITY_INFO => 'LOG_SEVERITY_INFO',
        self::LOG_SEVERITY_SUCCESS => 'LOG_SEVERITY_SUCCESS',
        self::LOG_SEVERITY_WARNING => 'LOG_SEVERITY_WARNING',
        self::LOG_SEVERITY_ERROR => 'LOG_SEVERITY_ERROR',
        self::LOG_SEVERITY_CRITICAL => 'LOG_SEVERITY_CRITICAL',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

