<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/nlu/agent.proto

namespace Ondewo\Nlu;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Request to migrate an agent
 *
 * Generated from protobuf message <code>ondewo.nlu.MigrateAgentRequest</code>
 */
class MigrateAgentRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The agent to migrate as zip file
     *
     * Generated from protobuf field <code>bytes agent_content = 1;</code>
     */
    protected $agent_content = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $agent_content
     *           The agent to migrate as zip file
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Nlu\Agent::initOnce();
        parent::__construct($data);
    }

    /**
     * The agent to migrate as zip file
     *
     * Generated from protobuf field <code>bytes agent_content = 1;</code>
     * @return string
     */
    public function getAgentContent()
    {
        return $this->agent_content;
    }

    /**
     * The agent to migrate as zip file
     *
     * Generated from protobuf field <code>bytes agent_content = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAgentContent($var)
    {
        GPBUtil::checkString($var, False);
        $this->agent_content = $var;

        return $this;
    }

}

