<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/nlu/agent.proto

namespace Ondewo\Nlu;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * This message is a request to run Optimize Ranking Match
 *
 * Generated from protobuf message <code>ondewo.nlu.OptimizeRankingMatchRequest</code>
 */
class OptimizeRankingMatchRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Required. The project that the agent to train is associated with.
     * Format: <pre><code>projects/&lt;project_uuid&gt;</code></pre>
     *
     * Generated from protobuf field <code>string parent = 1;</code>
     */
    protected $parent = '';
    /**
     * languages that should be optimized
     *
     * Generated from protobuf field <code>repeated string language_codes = 2;</code>
     */
    private $language_codes;
    /**
     * optimization config will contain all possible optimizations, with which we will come up in the future
     *
     * Generated from protobuf field <code>repeated .ondewo.nlu.RankingMatchOptimizationConfig optimization_configs = 3;</code>
     */
    private $optimization_configs;
    /**
     * if in_place is true then the config of the agent on the server will be updated, if False then config
     * with optimized thresholds will be returned but not updated on the server
     *
     * Generated from protobuf field <code>bool in_place = 4;</code>
     */
    protected $in_place = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $parent
     *           Required. The project that the agent to train is associated with.
     *           Format: <pre><code>projects/&lt;project_uuid&gt;</code></pre>
     *     @type string[] $language_codes
     *           languages that should be optimized
     *     @type \Ondewo\Nlu\RankingMatchOptimizationConfig[] $optimization_configs
     *           optimization config will contain all possible optimizations, with which we will come up in the future
     *     @type bool $in_place
     *           if in_place is true then the config of the agent on the server will be updated, if False then config
     *           with optimized thresholds will be returned but not updated on the server
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Nlu\Agent::initOnce();
        parent::__construct($data);
    }

    /**
     * Required. The project that the agent to train is associated with.
     * Format: <pre><code>projects/&lt;project_uuid&gt;</code></pre>
     *
     * Generated from protobuf field <code>string parent = 1;</code>
     * @return string
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * Required. The project that the agent to train is associated with.
     * Format: <pre><code>projects/&lt;project_uuid&gt;</code></pre>
     *
     * Generated from protobuf field <code>string parent = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setParent($var)
    {
        GPBUtil::checkString($var, True);
        $this->parent = $var;

        return $this;
    }

    /**
     * languages that should be optimized
     *
     * Generated from protobuf field <code>repeated string language_codes = 2;</code>
     * @return RepeatedField<string>
     */
    public function getLanguageCodes()
    {
        return $this->language_codes;
    }

    /**
     * languages that should be optimized
     *
     * Generated from protobuf field <code>repeated string language_codes = 2;</code>
     * @param string[] $var
     * @return $this
     */
    public function setLanguageCodes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->language_codes = $arr;

        return $this;
    }

    /**
     * optimization config will contain all possible optimizations, with which we will come up in the future
     *
     * Generated from protobuf field <code>repeated .ondewo.nlu.RankingMatchOptimizationConfig optimization_configs = 3;</code>
     * @return RepeatedField<\Ondewo\Nlu\RankingMatchOptimizationConfig>
     */
    public function getOptimizationConfigs()
    {
        return $this->optimization_configs;
    }

    /**
     * optimization config will contain all possible optimizations, with which we will come up in the future
     *
     * Generated from protobuf field <code>repeated .ondewo.nlu.RankingMatchOptimizationConfig optimization_configs = 3;</code>
     * @param \Ondewo\Nlu\RankingMatchOptimizationConfig[] $var
     * @return $this
     */
    public function setOptimizationConfigs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Ondewo\Nlu\RankingMatchOptimizationConfig::class);
        $this->optimization_configs = $arr;

        return $this;
    }

    /**
     * if in_place is true then the config of the agent on the server will be updated, if False then config
     * with optimized thresholds will be returned but not updated on the server
     *
     * Generated from protobuf field <code>bool in_place = 4;</code>
     * @return bool
     */
    public function getInPlace()
    {
        return $this->in_place;
    }

    /**
     * if in_place is true then the config of the agent on the server will be updated, if False then config
     * with optimized thresholds will be returned but not updated on the server
     *
     * Generated from protobuf field <code>bool in_place = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setInPlace($var)
    {
        GPBUtil::checkBool($var);
        $this->in_place = $var;

        return $this;
    }

}

