<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/nlu/webhook.proto

namespace Ondewo\Nlu;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Represents the contents of the original request that was passed to the <code>[Streaming]DetectIntent</code> call.
 *
 * Generated from protobuf message <code>ondewo.nlu.OriginalDetectIntentRequest</code>
 */
class OriginalDetectIntentRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The source of this request, e.g., <code>google</code>, <code>facebook</code>, <code>slack</code> or other &quot;platforms&quot;. .
     * Used to identify the &quot;platform&quot;
     *
     * Generated from protobuf field <code>string source = 1;</code>
     */
    protected $source = '';
    /**
     * Optional. This field is set to the value of the <code>QueryParameters.payload</code>
     * field passed in the request. Some integrations that query an
     * agent may provide additional data in the payload.
     * In particular this can be of the form:
     * <pre>{
     *  &quot;a&quot;: {
     *    &quot;b&quot;: &quot;c&quot;
     *  }
     * }</pre>
     *
     * Generated from protobuf field <code>.google.protobuf.Struct payload = 3;</code>
     */
    protected $payload = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $source
     *           The source of this request, e.g., <code>google</code>, <code>facebook</code>, <code>slack</code> or other &quot;platforms&quot;. .
     *           Used to identify the &quot;platform&quot;
     *     @type \Google\Protobuf\Struct $payload
     *           Optional. This field is set to the value of the <code>QueryParameters.payload</code>
     *           field passed in the request. Some integrations that query an
     *           agent may provide additional data in the payload.
     *           In particular this can be of the form:
     *           <pre>{
     *            &quot;a&quot;: {
     *              &quot;b&quot;: &quot;c&quot;
     *            }
     *           }</pre>
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Nlu\Webhook::initOnce();
        parent::__construct($data);
    }

    /**
     * The source of this request, e.g., <code>google</code>, <code>facebook</code>, <code>slack</code> or other &quot;platforms&quot;. .
     * Used to identify the &quot;platform&quot;
     *
     * Generated from protobuf field <code>string source = 1;</code>
     * @return string
     */
    public function getSource()
    {
        return $this->source;
    }

    /**
     * The source of this request, e.g., <code>google</code>, <code>facebook</code>, <code>slack</code> or other &quot;platforms&quot;. .
     * Used to identify the &quot;platform&quot;
     *
     * Generated from protobuf field <code>string source = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSource($var)
    {
        GPBUtil::checkString($var, True);
        $this->source = $var;

        return $this;
    }

    /**
     * Optional. This field is set to the value of the <code>QueryParameters.payload</code>
     * field passed in the request. Some integrations that query an
     * agent may provide additional data in the payload.
     * In particular this can be of the form:
     * <pre>{
     *  &quot;a&quot;: {
     *    &quot;b&quot;: &quot;c&quot;
     *  }
     * }</pre>
     *
     * Generated from protobuf field <code>.google.protobuf.Struct payload = 3;</code>
     * @return \Google\Protobuf\Struct|null
     */
    public function getPayload()
    {
        return $this->payload;
    }

    public function hasPayload()
    {
        return isset($this->payload);
    }

    public function clearPayload()
    {
        unset($this->payload);
    }

    /**
     * Optional. This field is set to the value of the <code>QueryParameters.payload</code>
     * field passed in the request. Some integrations that query an
     * agent may provide additional data in the payload.
     * In particular this can be of the form:
     * <pre>{
     *  &quot;a&quot;: {
     *    &quot;b&quot;: &quot;c&quot;
     *  }
     * }</pre>
     *
     * Generated from protobuf field <code>.google.protobuf.Struct payload = 3;</code>
     * @param \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setPayload($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->payload = $var;

        return $this;
    }

}

