<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/nlu/rag.proto

namespace Ondewo\Nlu;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>ondewo.nlu.RagCrawlerContentResult</code>
 */
class RagCrawlerContentResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Optional. Extracted page metadata.
     * Includes only fields configured in <code>RagCrawlerConfig.output_config.meta_data_extractors</code>.
     *
     * Generated from protobuf field <code>.google.protobuf.Struct metadata = 1;</code>
     */
    protected $metadata = null;
    /**
     * Optional. Extracted markdown output.
     *
     * Generated from protobuf field <code>optional string markdown = 2;</code>
     */
    protected $markdown = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Struct $metadata
     *           Optional. Extracted page metadata.
     *           Includes only fields configured in <code>RagCrawlerConfig.output_config.meta_data_extractors</code>.
     *     @type string $markdown
     *           Optional. Extracted markdown output.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Nlu\Rag::initOnce();
        parent::__construct($data);
    }

    /**
     * Optional. Extracted page metadata.
     * Includes only fields configured in <code>RagCrawlerConfig.output_config.meta_data_extractors</code>.
     *
     * Generated from protobuf field <code>.google.protobuf.Struct metadata = 1;</code>
     * @return \Google\Protobuf\Struct|null
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    public function hasMetadata()
    {
        return isset($this->metadata);
    }

    public function clearMetadata()
    {
        unset($this->metadata);
    }

    /**
     * Optional. Extracted page metadata.
     * Includes only fields configured in <code>RagCrawlerConfig.output_config.meta_data_extractors</code>.
     *
     * Generated from protobuf field <code>.google.protobuf.Struct metadata = 1;</code>
     * @param \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setMetadata($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->metadata = $var;

        return $this;
    }

    /**
     * Optional. Extracted markdown output.
     *
     * Generated from protobuf field <code>optional string markdown = 2;</code>
     * @return string
     */
    public function getMarkdown()
    {
        return isset($this->markdown) ? $this->markdown : '';
    }

    public function hasMarkdown()
    {
        return isset($this->markdown);
    }

    public function clearMarkdown()
    {
        unset($this->markdown);
    }

    /**
     * Optional. Extracted markdown output.
     *
     * Generated from protobuf field <code>optional string markdown = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMarkdown($var)
    {
        GPBUtil::checkString($var, True);
        $this->markdown = $var;

        return $this;
    }

}

