<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/nlu/rag.proto

namespace Ondewo\Nlu;

use UnexpectedValueException;

/**
 * Valid metadata condition comparison operators
 *
 * Protobuf type <code>ondewo.nlu.RagComparisonOperator</code>
 */
class RagComparisonOperator
{
    /**
     * Unspecified. Must never be used.
     *
     * Generated from protobuf enum <code>RAG_COMPARISON_OPERATOR_UNSPECIFIED = 0;</code>
     */
    const RAG_COMPARISON_OPERATOR_UNSPECIFIED = 0;
    /**
     * String representation of metadata field contains value.<br>
     * If metadata field is a list, checks if the string representation of <em>any</em> field contains value.
     *
     * Generated from protobuf enum <code>RAG_COMPARISON_OPERATOR_CONTAINS = 1;</code>
     */
    const RAG_COMPARISON_OPERATOR_CONTAINS = 1;
    /**
     * String representation of metadata field does not contain value.<br>
     * If metadata field is a list, checks if the string representation of <em>no</em> fields contains value.
     *
     * Generated from protobuf enum <code>RAG_COMPARISON_OPERATOR_NOT_CONTAINS = 2;</code>
     */
    const RAG_COMPARISON_OPERATOR_NOT_CONTAINS = 2;
    /**
     * Checks with Python's <code>in</code> operator.<br>
     * If metadata field is a list, <em>all</em> elements must satisfy the condition.
     *
     * Generated from protobuf enum <code>RAG_COMPARISON_OPERATOR_IN = 3;</code>
     */
    const RAG_COMPARISON_OPERATOR_IN = 3;
    /**
     * Checks with Python's <code>not in</code> operator.<br>
     * If metadata field is a list, <em>all</em> elements must satisfy the condition.
     *
     * Generated from protobuf enum <code>RAG_COMPARISON_OPERATOR_NOT_IN = 4;</code>
     */
    const RAG_COMPARISON_OPERATOR_NOT_IN = 4;
    /**
     * String representation of metadata field starts with value.<br>
     * If metadata field is a list, checks if the joined string of the string representations of all list elements starts with the value.
     *
     * Generated from protobuf enum <code>RAG_COMPARISON_OPERATOR_START_WITH = 5;</code>
     */
    const RAG_COMPARISON_OPERATOR_START_WITH = 5;
    /**
     * String representation of metadata field ends with value.<br>
     * If metadata field is a list, checks if the joined string of the string representations of all list elements ends with the value.
     *
     * Generated from protobuf enum <code>RAG_COMPARISON_OPERATOR_END_WITH = 6;</code>
     */
    const RAG_COMPARISON_OPERATOR_END_WITH = 6;
    /**
     * Is empty (Python <em>falsy</em>).
     *
     * Generated from protobuf enum <code>RAG_COMPARISON_OPERATOR_EMPTY = 7;</code>
     */
    const RAG_COMPARISON_OPERATOR_EMPTY = 7;
    /**
     * Is not empty (Python <em>truthy</em>).
     *
     * Generated from protobuf enum <code>RAG_COMPARISON_OPERATOR_NOT_EMPTY = 8;</code>
     */
    const RAG_COMPARISON_OPERATOR_NOT_EMPTY = 8;
    /**
     * Equals.
     *
     * Generated from protobuf enum <code>RAG_COMPARISON_OPERATOR_EQ = 9;</code>
     */
    const RAG_COMPARISON_OPERATOR_EQ = 9;
    /**
     * Does not equal.
     *
     * Generated from protobuf enum <code>RAG_COMPARISON_OPERATOR_NEQ = 10;</code>
     */
    const RAG_COMPARISON_OPERATOR_NEQ = 10;
    /**
     * Greater than.
     *
     * Generated from protobuf enum <code>RAG_COMPARISON_OPERATOR_GT = 11;</code>
     */
    const RAG_COMPARISON_OPERATOR_GT = 11;
    /**
     * Less than.
     *
     * Generated from protobuf enum <code>RAG_COMPARISON_OPERATOR_LT = 12;</code>
     */
    const RAG_COMPARISON_OPERATOR_LT = 12;
    /**
     * Greater than or equal.
     *
     * Generated from protobuf enum <code>RAG_COMPARISON_OPERATOR_GEQ = 13;</code>
     */
    const RAG_COMPARISON_OPERATOR_GEQ = 13;
    /**
     * Less than or equal.
     *
     * Generated from protobuf enum <code>RAG_COMPARISON_OPERATOR_LEQ = 14;</code>
     */
    const RAG_COMPARISON_OPERATOR_LEQ = 14;

    private static $valueToName = [
        self::RAG_COMPARISON_OPERATOR_UNSPECIFIED => 'RAG_COMPARISON_OPERATOR_UNSPECIFIED',
        self::RAG_COMPARISON_OPERATOR_CONTAINS => 'RAG_COMPARISON_OPERATOR_CONTAINS',
        self::RAG_COMPARISON_OPERATOR_NOT_CONTAINS => 'RAG_COMPARISON_OPERATOR_NOT_CONTAINS',
        self::RAG_COMPARISON_OPERATOR_IN => 'RAG_COMPARISON_OPERATOR_IN',
        self::RAG_COMPARISON_OPERATOR_NOT_IN => 'RAG_COMPARISON_OPERATOR_NOT_IN',
        self::RAG_COMPARISON_OPERATOR_START_WITH => 'RAG_COMPARISON_OPERATOR_START_WITH',
        self::RAG_COMPARISON_OPERATOR_END_WITH => 'RAG_COMPARISON_OPERATOR_END_WITH',
        self::RAG_COMPARISON_OPERATOR_EMPTY => 'RAG_COMPARISON_OPERATOR_EMPTY',
        self::RAG_COMPARISON_OPERATOR_NOT_EMPTY => 'RAG_COMPARISON_OPERATOR_NOT_EMPTY',
        self::RAG_COMPARISON_OPERATOR_EQ => 'RAG_COMPARISON_OPERATOR_EQ',
        self::RAG_COMPARISON_OPERATOR_NEQ => 'RAG_COMPARISON_OPERATOR_NEQ',
        self::RAG_COMPARISON_OPERATOR_GT => 'RAG_COMPARISON_OPERATOR_GT',
        self::RAG_COMPARISON_OPERATOR_LT => 'RAG_COMPARISON_OPERATOR_LT',
        self::RAG_COMPARISON_OPERATOR_GEQ => 'RAG_COMPARISON_OPERATOR_GEQ',
        self::RAG_COMPARISON_OPERATOR_LEQ => 'RAG_COMPARISON_OPERATOR_LEQ',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

