<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/nlu/rag.proto

namespace Ondewo\Nlu;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Crawl entry points.
 * Both inputs can be provided at the same time:
 * - Sitemaps are expanded into a crawl URL list (in discovery order)
 * - Seed URLs are appended afterwards (in the order provided)
 *
 * Generated from protobuf message <code>ondewo.nlu.RagCrawlerSources</code>
 */
class RagCrawlerSources extends \Google\Protobuf\Internal\Message
{
    /**
     * Direct seed URLs to enqueue as starting points.
     *
     * Generated from protobuf field <code>repeated string urls = 1;</code>
     */
    private $urls;
    /**
     * Sitemap URLs used for URL discovery.
     * Typical values are <code>/sitemap.xml</code> or sitemap index files.
     *
     * Generated from protobuf field <code>repeated string sitemaps = 2;</code>
     */
    private $sitemaps;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[] $urls
     *           Direct seed URLs to enqueue as starting points.
     *     @type string[] $sitemaps
     *           Sitemap URLs used for URL discovery.
     *           Typical values are <code>/sitemap.xml</code> or sitemap index files.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Nlu\Rag::initOnce();
        parent::__construct($data);
    }

    /**
     * Direct seed URLs to enqueue as starting points.
     *
     * Generated from protobuf field <code>repeated string urls = 1;</code>
     * @return RepeatedField<string>
     */
    public function getUrls()
    {
        return $this->urls;
    }

    /**
     * Direct seed URLs to enqueue as starting points.
     *
     * Generated from protobuf field <code>repeated string urls = 1;</code>
     * @param string[] $var
     * @return $this
     */
    public function setUrls($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->urls = $arr;

        return $this;
    }

    /**
     * Sitemap URLs used for URL discovery.
     * Typical values are <code>/sitemap.xml</code> or sitemap index files.
     *
     * Generated from protobuf field <code>repeated string sitemaps = 2;</code>
     * @return RepeatedField<string>
     */
    public function getSitemaps()
    {
        return $this->sitemaps;
    }

    /**
     * Sitemap URLs used for URL discovery.
     * Typical values are <code>/sitemap.xml</code> or sitemap index files.
     *
     * Generated from protobuf field <code>repeated string sitemaps = 2;</code>
     * @param string[] $var
     * @return $this
     */
    public function setSitemaps($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->sitemaps = $arr;

        return $this;
    }

}

