<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/nlu/rag.proto

namespace Ondewo\Nlu;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Browser runtime configuration.
 * This block maps closely to Crawl4AI BrowserConfig and controls browser
 * process setup (engine, headless mode, viewport, context, proxy, cookies,
 * user-agent behavior, and launch arguments).
 *
 * Generated from protobuf message <code>ondewo.nlu.RagCrawlerBrowserConfig</code>
 */
class RagCrawlerBrowserConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Optional. HTTP headers sent on page/resource requests.
     * Repeated entries allow duplicate header names and preserve order.
     *
     * Generated from protobuf field <code>repeated .google.protobuf.Struct crawler_headers = 1;</code>
     */
    private $crawler_headers;
    /**
     * Optional. Initial cookies.
     *
     * Generated from protobuf field <code>repeated .ondewo.nlu.RagCrawlerCookie crawler_cookies = 2;</code>
     */
    private $crawler_cookies;
    /**
     * Optional. User-Agent sent with requests.
     *
     * Generated from protobuf field <code>optional string crawler_user_agent = 3;</code>
     */
    protected $crawler_user_agent = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Struct[] $crawler_headers
     *           Optional. HTTP headers sent on page/resource requests.
     *           Repeated entries allow duplicate header names and preserve order.
     *     @type \Ondewo\Nlu\RagCrawlerCookie[] $crawler_cookies
     *           Optional. Initial cookies.
     *     @type string $crawler_user_agent
     *           Optional. User-Agent sent with requests.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Nlu\Rag::initOnce();
        parent::__construct($data);
    }

    /**
     * Optional. HTTP headers sent on page/resource requests.
     * Repeated entries allow duplicate header names and preserve order.
     *
     * Generated from protobuf field <code>repeated .google.protobuf.Struct crawler_headers = 1;</code>
     * @return RepeatedField<\Google\Protobuf\Struct>
     */
    public function getCrawlerHeaders()
    {
        return $this->crawler_headers;
    }

    /**
     * Optional. HTTP headers sent on page/resource requests.
     * Repeated entries allow duplicate header names and preserve order.
     *
     * Generated from protobuf field <code>repeated .google.protobuf.Struct crawler_headers = 1;</code>
     * @param \Google\Protobuf\Struct[] $var
     * @return $this
     */
    public function setCrawlerHeaders($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Protobuf\Struct::class);
        $this->crawler_headers = $arr;

        return $this;
    }

    /**
     * Optional. Initial cookies.
     *
     * Generated from protobuf field <code>repeated .ondewo.nlu.RagCrawlerCookie crawler_cookies = 2;</code>
     * @return RepeatedField<\Ondewo\Nlu\RagCrawlerCookie>
     */
    public function getCrawlerCookies()
    {
        return $this->crawler_cookies;
    }

    /**
     * Optional. Initial cookies.
     *
     * Generated from protobuf field <code>repeated .ondewo.nlu.RagCrawlerCookie crawler_cookies = 2;</code>
     * @param \Ondewo\Nlu\RagCrawlerCookie[] $var
     * @return $this
     */
    public function setCrawlerCookies($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Ondewo\Nlu\RagCrawlerCookie::class);
        $this->crawler_cookies = $arr;

        return $this;
    }

    /**
     * Optional. User-Agent sent with requests.
     *
     * Generated from protobuf field <code>optional string crawler_user_agent = 3;</code>
     * @return string
     */
    public function getCrawlerUserAgent()
    {
        return isset($this->crawler_user_agent) ? $this->crawler_user_agent : '';
    }

    public function hasCrawlerUserAgent()
    {
        return isset($this->crawler_user_agent);
    }

    public function clearCrawlerUserAgent()
    {
        unset($this->crawler_user_agent);
    }

    /**
     * Optional. User-Agent sent with requests.
     *
     * Generated from protobuf field <code>optional string crawler_user_agent = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCrawlerUserAgent($var)
    {
        GPBUtil::checkString($var, True);
        $this->crawler_user_agent = $var;

        return $this;
    }

}

