<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/nlu/rag.proto

namespace Ondewo\Nlu;

use UnexpectedValueException;

/**
 * Document processing status.
 *
 * Protobuf type <code>ondewo.nlu.RagDocumentStatus</code>
 */
class RagDocumentStatus
{
    /**
     * Unspecified.
     *
     * Generated from protobuf enum <code>RAG_DOCUMENT_STATUS_UNSPECIFIED = 0;</code>
     */
    const RAG_DOCUMENT_STATUS_UNSPECIFIED = 0;
    /**
     * Document has not started processing.
     *
     * Generated from protobuf enum <code>RAG_DOCUMENT_STATUS_UNSTART = 1;</code>
     */
    const RAG_DOCUMENT_STATUS_UNSTART = 1;
    /**
     * Document is currently being processed.
     *
     * Generated from protobuf enum <code>RAG_DOCUMENT_STATUS_RUNNING = 2;</code>
     */
    const RAG_DOCUMENT_STATUS_RUNNING = 2;
    /**
     * Document processing was cancelled.
     *
     * Generated from protobuf enum <code>RAG_DOCUMENT_STATUS_CANCEL = 3;</code>
     */
    const RAG_DOCUMENT_STATUS_CANCEL = 3;
    /**
     * Document processing completed successfully.
     *
     * Generated from protobuf enum <code>RAG_DOCUMENT_STATUS_DONE = 4;</code>
     */
    const RAG_DOCUMENT_STATUS_DONE = 4;
    /**
     * Document processing failed.
     *
     * Generated from protobuf enum <code>RAG_DOCUMENT_STATUS_FAIL = 5;</code>
     */
    const RAG_DOCUMENT_STATUS_FAIL = 5;

    private static $valueToName = [
        self::RAG_DOCUMENT_STATUS_UNSPECIFIED => 'RAG_DOCUMENT_STATUS_UNSPECIFIED',
        self::RAG_DOCUMENT_STATUS_UNSTART => 'RAG_DOCUMENT_STATUS_UNSTART',
        self::RAG_DOCUMENT_STATUS_RUNNING => 'RAG_DOCUMENT_STATUS_RUNNING',
        self::RAG_DOCUMENT_STATUS_CANCEL => 'RAG_DOCUMENT_STATUS_CANCEL',
        self::RAG_DOCUMENT_STATUS_DONE => 'RAG_DOCUMENT_STATUS_DONE',
        self::RAG_DOCUMENT_STATUS_FAIL => 'RAG_DOCUMENT_STATUS_FAIL',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

