<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/nlu/rag.proto

namespace Ondewo\Nlu;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Dataset containing documents for RAG.
 *
 * Generated from protobuf message <code>ondewo.nlu.RagDataset</code>
 */
class RagDataset extends \Google\Protobuf\Internal\Message
{
    /**
     * Dataset UUID.
     *
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Base64-encoded avatar image.
     *
     * Generated from protobuf field <code>string avatar = 2;</code>
     */
    protected $avatar = '';
    /**
     * Dataset name.
     *
     * Generated from protobuf field <code>string name = 3;</code>
     */
    protected $name = '';
    /**
     * Dataset description.
     *
     * Generated from protobuf field <code>string description = 4;</code>
     */
    protected $description = '';
    /**
     * Number of documents in the dataset.
     *
     * Generated from protobuf field <code>optional int32 document_count = 5;</code>
     */
    protected $document_count = null;
    /**
     * Number of tokens in the dataset.
     *
     * Generated from protobuf field <code>optional int32 token_num = 6;</code>
     */
    protected $token_num = null;
    /**
     * Number of chunks of all documents in the dataset.
     *
     * Generated from protobuf field <code>optional int32 chunk_count = 7;</code>
     */
    protected $chunk_count = null;
    /**
     * Default chunking method for documents in this dataset.
     *
     * Generated from protobuf field <code>.ondewo.nlu.RagChunkMethod chunk_method = 8;</code>
     */
    protected $chunk_method = 0;
    /**
     * Document parser configuration (auto-generated based on chunk_method).
     *
     * Generated from protobuf field <code>.ondewo.nlu.RagParserConfig parser_config = 9;</code>
     */
    protected $parser_config = null;
    /**
     * Pagerank.
     *
     * Generated from protobuf field <code>optional int32 pagerank = 10;</code>
     */
    protected $pagerank = null;
    /**
     * Parsing status of all documents in the dataset. Might be empty if the system failed to get the parsing statistics.
     *
     * Generated from protobuf field <code>.ondewo.nlu.RagDatasetParsingStatus parsing_status = 11;</code>
     */
    protected $parsing_status = null;
    /**
     * Creation date and time.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp create_time = 12;</code>
     */
    protected $create_time = null;
    /**
     * Last update date and time.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp update_time = 13;</code>
     */
    protected $update_time = null;
    /**
     * CCAI service name of the embedding model used by this dataset.
     *
     * Generated from protobuf field <code>string embedding_model_ccai_service_name = 14;</code>
     */
    protected $embedding_model_ccai_service_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *           Dataset UUID.
     *     @type string $avatar
     *           Base64-encoded avatar image.
     *     @type string $name
     *           Dataset name.
     *     @type string $description
     *           Dataset description.
     *     @type int $document_count
     *           Number of documents in the dataset.
     *     @type int $token_num
     *           Number of tokens in the dataset.
     *     @type int $chunk_count
     *           Number of chunks of all documents in the dataset.
     *     @type int $chunk_method
     *           Default chunking method for documents in this dataset.
     *     @type \Ondewo\Nlu\RagParserConfig $parser_config
     *           Document parser configuration (auto-generated based on chunk_method).
     *     @type int $pagerank
     *           Pagerank.
     *     @type \Ondewo\Nlu\RagDatasetParsingStatus $parsing_status
     *           Parsing status of all documents in the dataset. Might be empty if the system failed to get the parsing statistics.
     *     @type \Google\Protobuf\Timestamp $create_time
     *           Creation date and time.
     *     @type \Google\Protobuf\Timestamp $update_time
     *           Last update date and time.
     *     @type string $embedding_model_ccai_service_name
     *           CCAI service name of the embedding model used by this dataset.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Nlu\Rag::initOnce();
        parent::__construct($data);
    }

    /**
     * Dataset UUID.
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Dataset UUID.
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Base64-encoded avatar image.
     *
     * Generated from protobuf field <code>string avatar = 2;</code>
     * @return string
     */
    public function getAvatar()
    {
        return $this->avatar;
    }

    /**
     * Base64-encoded avatar image.
     *
     * Generated from protobuf field <code>string avatar = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAvatar($var)
    {
        GPBUtil::checkString($var, True);
        $this->avatar = $var;

        return $this;
    }

    /**
     * Dataset name.
     *
     * Generated from protobuf field <code>string name = 3;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Dataset name.
     *
     * Generated from protobuf field <code>string name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Dataset description.
     *
     * Generated from protobuf field <code>string description = 4;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Dataset description.
     *
     * Generated from protobuf field <code>string description = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Number of documents in the dataset.
     *
     * Generated from protobuf field <code>optional int32 document_count = 5;</code>
     * @return int
     */
    public function getDocumentCount()
    {
        return isset($this->document_count) ? $this->document_count : 0;
    }

    public function hasDocumentCount()
    {
        return isset($this->document_count);
    }

    public function clearDocumentCount()
    {
        unset($this->document_count);
    }

    /**
     * Number of documents in the dataset.
     *
     * Generated from protobuf field <code>optional int32 document_count = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setDocumentCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->document_count = $var;

        return $this;
    }

    /**
     * Number of tokens in the dataset.
     *
     * Generated from protobuf field <code>optional int32 token_num = 6;</code>
     * @return int
     */
    public function getTokenNum()
    {
        return isset($this->token_num) ? $this->token_num : 0;
    }

    public function hasTokenNum()
    {
        return isset($this->token_num);
    }

    public function clearTokenNum()
    {
        unset($this->token_num);
    }

    /**
     * Number of tokens in the dataset.
     *
     * Generated from protobuf field <code>optional int32 token_num = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setTokenNum($var)
    {
        GPBUtil::checkInt32($var);
        $this->token_num = $var;

        return $this;
    }

    /**
     * Number of chunks of all documents in the dataset.
     *
     * Generated from protobuf field <code>optional int32 chunk_count = 7;</code>
     * @return int
     */
    public function getChunkCount()
    {
        return isset($this->chunk_count) ? $this->chunk_count : 0;
    }

    public function hasChunkCount()
    {
        return isset($this->chunk_count);
    }

    public function clearChunkCount()
    {
        unset($this->chunk_count);
    }

    /**
     * Number of chunks of all documents in the dataset.
     *
     * Generated from protobuf field <code>optional int32 chunk_count = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setChunkCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->chunk_count = $var;

        return $this;
    }

    /**
     * Default chunking method for documents in this dataset.
     *
     * Generated from protobuf field <code>.ondewo.nlu.RagChunkMethod chunk_method = 8;</code>
     * @return int
     */
    public function getChunkMethod()
    {
        return $this->chunk_method;
    }

    /**
     * Default chunking method for documents in this dataset.
     *
     * Generated from protobuf field <code>.ondewo.nlu.RagChunkMethod chunk_method = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setChunkMethod($var)
    {
        GPBUtil::checkEnum($var, \Ondewo\Nlu\RagChunkMethod::class);
        $this->chunk_method = $var;

        return $this;
    }

    /**
     * Document parser configuration (auto-generated based on chunk_method).
     *
     * Generated from protobuf field <code>.ondewo.nlu.RagParserConfig parser_config = 9;</code>
     * @return \Ondewo\Nlu\RagParserConfig|null
     */
    public function getParserConfig()
    {
        return $this->parser_config;
    }

    public function hasParserConfig()
    {
        return isset($this->parser_config);
    }

    public function clearParserConfig()
    {
        unset($this->parser_config);
    }

    /**
     * Document parser configuration (auto-generated based on chunk_method).
     *
     * Generated from protobuf field <code>.ondewo.nlu.RagParserConfig parser_config = 9;</code>
     * @param \Ondewo\Nlu\RagParserConfig $var
     * @return $this
     */
    public function setParserConfig($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Nlu\RagParserConfig::class);
        $this->parser_config = $var;

        return $this;
    }

    /**
     * Pagerank.
     *
     * Generated from protobuf field <code>optional int32 pagerank = 10;</code>
     * @return int
     */
    public function getPagerank()
    {
        return isset($this->pagerank) ? $this->pagerank : 0;
    }

    public function hasPagerank()
    {
        return isset($this->pagerank);
    }

    public function clearPagerank()
    {
        unset($this->pagerank);
    }

    /**
     * Pagerank.
     *
     * Generated from protobuf field <code>optional int32 pagerank = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setPagerank($var)
    {
        GPBUtil::checkInt32($var);
        $this->pagerank = $var;

        return $this;
    }

    /**
     * Parsing status of all documents in the dataset. Might be empty if the system failed to get the parsing statistics.
     *
     * Generated from protobuf field <code>.ondewo.nlu.RagDatasetParsingStatus parsing_status = 11;</code>
     * @return \Ondewo\Nlu\RagDatasetParsingStatus|null
     */
    public function getParsingStatus()
    {
        return $this->parsing_status;
    }

    public function hasParsingStatus()
    {
        return isset($this->parsing_status);
    }

    public function clearParsingStatus()
    {
        unset($this->parsing_status);
    }

    /**
     * Parsing status of all documents in the dataset. Might be empty if the system failed to get the parsing statistics.
     *
     * Generated from protobuf field <code>.ondewo.nlu.RagDatasetParsingStatus parsing_status = 11;</code>
     * @param \Ondewo\Nlu\RagDatasetParsingStatus $var
     * @return $this
     */
    public function setParsingStatus($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Nlu\RagDatasetParsingStatus::class);
        $this->parsing_status = $var;

        return $this;
    }

    /**
     * Creation date and time.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp create_time = 12;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getCreateTime()
    {
        return $this->create_time;
    }

    public function hasCreateTime()
    {
        return isset($this->create_time);
    }

    public function clearCreateTime()
    {
        unset($this->create_time);
    }

    /**
     * Creation date and time.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp create_time = 12;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setCreateTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->create_time = $var;

        return $this;
    }

    /**
     * Last update date and time.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp update_time = 13;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getUpdateTime()
    {
        return $this->update_time;
    }

    public function hasUpdateTime()
    {
        return isset($this->update_time);
    }

    public function clearUpdateTime()
    {
        unset($this->update_time);
    }

    /**
     * Last update date and time.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp update_time = 13;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setUpdateTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->update_time = $var;

        return $this;
    }

    /**
     * CCAI service name of the embedding model used by this dataset.
     *
     * Generated from protobuf field <code>string embedding_model_ccai_service_name = 14;</code>
     * @return string
     */
    public function getEmbeddingModelCcaiServiceName()
    {
        return $this->embedding_model_ccai_service_name;
    }

    /**
     * CCAI service name of the embedding model used by this dataset.
     *
     * Generated from protobuf field <code>string embedding_model_ccai_service_name = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setEmbeddingModelCcaiServiceName($var)
    {
        GPBUtil::checkString($var, True);
        $this->embedding_model_ccai_service_name = $var;

        return $this;
    }

}

