<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/nlu/rag.proto

namespace Ondewo\Nlu;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Request message for getting a single crawler result from a crawler run.
 *
 * Generated from protobuf message <code>ondewo.nlu.RagGetCrawlerResultRequest</code>
 */
class RagGetCrawlerResultRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Required. The agent that owns the crawler run.
     * Format: <pre><code>projects/&lt;project_uuid&gt;/agent</code></pre>
     *
     * Generated from protobuf field <code>string parent = 1;</code>
     */
    protected $parent = '';
    /**
     * Required. The language of the project to use.
     *
     * Generated from protobuf field <code>string language_code = 2;</code>
     */
    protected $language_code = '';
    /**
     * Required. Resource name of the crawler run.
     * Format: <pre><code>projects/&lt;project_uuid&gt;/agent/crawler_runs/&lt;crawler_run_uuid&gt;</code></pre>
     *
     * Generated from protobuf field <code>string operation_name = 3;</code>
     */
    protected $operation_name = '';
    /**
     * Required. Exact URL of the crawler result to retrieve.
     *
     * Generated from protobuf field <code>string url = 4;</code>
     */
    protected $url = '';
    /**
     * Optional. The mask to control which RagCrawlerResult fields get returned.
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask field_mask = 5;</code>
     */
    protected $field_mask = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $parent
     *           Required. The agent that owns the crawler run.
     *           Format: <pre><code>projects/&lt;project_uuid&gt;/agent</code></pre>
     *     @type string $language_code
     *           Required. The language of the project to use.
     *     @type string $operation_name
     *           Required. Resource name of the crawler run.
     *           Format: <pre><code>projects/&lt;project_uuid&gt;/agent/crawler_runs/&lt;crawler_run_uuid&gt;</code></pre>
     *     @type string $url
     *           Required. Exact URL of the crawler result to retrieve.
     *     @type \Google\Protobuf\FieldMask $field_mask
     *           Optional. The mask to control which RagCrawlerResult fields get returned.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Nlu\Rag::initOnce();
        parent::__construct($data);
    }

    /**
     * Required. The agent that owns the crawler run.
     * Format: <pre><code>projects/&lt;project_uuid&gt;/agent</code></pre>
     *
     * Generated from protobuf field <code>string parent = 1;</code>
     * @return string
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * Required. The agent that owns the crawler run.
     * Format: <pre><code>projects/&lt;project_uuid&gt;/agent</code></pre>
     *
     * Generated from protobuf field <code>string parent = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setParent($var)
    {
        GPBUtil::checkString($var, True);
        $this->parent = $var;

        return $this;
    }

    /**
     * Required. The language of the project to use.
     *
     * Generated from protobuf field <code>string language_code = 2;</code>
     * @return string
     */
    public function getLanguageCode()
    {
        return $this->language_code;
    }

    /**
     * Required. The language of the project to use.
     *
     * Generated from protobuf field <code>string language_code = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setLanguageCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->language_code = $var;

        return $this;
    }

    /**
     * Required. Resource name of the crawler run.
     * Format: <pre><code>projects/&lt;project_uuid&gt;/agent/crawler_runs/&lt;crawler_run_uuid&gt;</code></pre>
     *
     * Generated from protobuf field <code>string operation_name = 3;</code>
     * @return string
     */
    public function getOperationName()
    {
        return $this->operation_name;
    }

    /**
     * Required. Resource name of the crawler run.
     * Format: <pre><code>projects/&lt;project_uuid&gt;/agent/crawler_runs/&lt;crawler_run_uuid&gt;</code></pre>
     *
     * Generated from protobuf field <code>string operation_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setOperationName($var)
    {
        GPBUtil::checkString($var, True);
        $this->operation_name = $var;

        return $this;
    }

    /**
     * Required. Exact URL of the crawler result to retrieve.
     *
     * Generated from protobuf field <code>string url = 4;</code>
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Required. Exact URL of the crawler result to retrieve.
     *
     * Generated from protobuf field <code>string url = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->url = $var;

        return $this;
    }

    /**
     * Optional. The mask to control which RagCrawlerResult fields get returned.
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask field_mask = 5;</code>
     * @return \Google\Protobuf\FieldMask|null
     */
    public function getFieldMask()
    {
        return $this->field_mask;
    }

    public function hasFieldMask()
    {
        return isset($this->field_mask);
    }

    public function clearFieldMask()
    {
        unset($this->field_mask);
    }

    /**
     * Optional. The mask to control which RagCrawlerResult fields get returned.
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask field_mask = 5;</code>
     * @param \Google\Protobuf\FieldMask $var
     * @return $this
     */
    public function setFieldMask($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\FieldMask::class);
        $this->field_mask = $var;

        return $this;
    }

}

