<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/nlu/rag.proto

namespace Ondewo\Nlu;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Request message for updating a crawler (partial update).
 *
 * Generated from protobuf message <code>ondewo.nlu.RagUpdateCrawlerRequest</code>
 */
class RagUpdateCrawlerRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Required. The crawler to update. Only configuration fields can be updated.
     * The name field must be set and must match an existing crawler.
     * Timestamps and audit fields are auto-managed by the service.
     *
     * Generated from protobuf field <code>.ondewo.nlu.RagCrawler crawler = 1;</code>
     */
    protected $crawler = null;
    /**
     * Required. The agent owning the crawler.
     * Format: <pre><code>projects/&lt;project_uuid&gt;/agent</code></pre>
     *
     * Generated from protobuf field <code>string parent = 2;</code>
     */
    protected $parent = '';
    /**
     * Required. The language of the project to use.
     *
     * Generated from protobuf field <code>string language_code = 3;</code>
     */
    protected $language_code = '';
    /**
     * Optional. FieldMask to specify which fields to update.
     * If not provided, all configuration fields in crawler are updated.
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask update_mask = 4;</code>
     */
    protected $update_mask = null;
    /**
     * Optional. The mask to control which crawler fields get returned.
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask field_mask = 5;</code>
     */
    protected $field_mask = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Ondewo\Nlu\RagCrawler $crawler
     *           Required. The crawler to update. Only configuration fields can be updated.
     *           The name field must be set and must match an existing crawler.
     *           Timestamps and audit fields are auto-managed by the service.
     *     @type string $parent
     *           Required. The agent owning the crawler.
     *           Format: <pre><code>projects/&lt;project_uuid&gt;/agent</code></pre>
     *     @type string $language_code
     *           Required. The language of the project to use.
     *     @type \Google\Protobuf\FieldMask $update_mask
     *           Optional. FieldMask to specify which fields to update.
     *           If not provided, all configuration fields in crawler are updated.
     *     @type \Google\Protobuf\FieldMask $field_mask
     *           Optional. The mask to control which crawler fields get returned.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Nlu\Rag::initOnce();
        parent::__construct($data);
    }

    /**
     * Required. The crawler to update. Only configuration fields can be updated.
     * The name field must be set and must match an existing crawler.
     * Timestamps and audit fields are auto-managed by the service.
     *
     * Generated from protobuf field <code>.ondewo.nlu.RagCrawler crawler = 1;</code>
     * @return \Ondewo\Nlu\RagCrawler|null
     */
    public function getCrawler()
    {
        return $this->crawler;
    }

    public function hasCrawler()
    {
        return isset($this->crawler);
    }

    public function clearCrawler()
    {
        unset($this->crawler);
    }

    /**
     * Required. The crawler to update. Only configuration fields can be updated.
     * The name field must be set and must match an existing crawler.
     * Timestamps and audit fields are auto-managed by the service.
     *
     * Generated from protobuf field <code>.ondewo.nlu.RagCrawler crawler = 1;</code>
     * @param \Ondewo\Nlu\RagCrawler $var
     * @return $this
     */
    public function setCrawler($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Nlu\RagCrawler::class);
        $this->crawler = $var;

        return $this;
    }

    /**
     * Required. The agent owning the crawler.
     * Format: <pre><code>projects/&lt;project_uuid&gt;/agent</code></pre>
     *
     * Generated from protobuf field <code>string parent = 2;</code>
     * @return string
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * Required. The agent owning the crawler.
     * Format: <pre><code>projects/&lt;project_uuid&gt;/agent</code></pre>
     *
     * Generated from protobuf field <code>string parent = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setParent($var)
    {
        GPBUtil::checkString($var, True);
        $this->parent = $var;

        return $this;
    }

    /**
     * Required. The language of the project to use.
     *
     * Generated from protobuf field <code>string language_code = 3;</code>
     * @return string
     */
    public function getLanguageCode()
    {
        return $this->language_code;
    }

    /**
     * Required. The language of the project to use.
     *
     * Generated from protobuf field <code>string language_code = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setLanguageCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->language_code = $var;

        return $this;
    }

    /**
     * Optional. FieldMask to specify which fields to update.
     * If not provided, all configuration fields in crawler are updated.
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask update_mask = 4;</code>
     * @return \Google\Protobuf\FieldMask|null
     */
    public function getUpdateMask()
    {
        return $this->update_mask;
    }

    public function hasUpdateMask()
    {
        return isset($this->update_mask);
    }

    public function clearUpdateMask()
    {
        unset($this->update_mask);
    }

    /**
     * Optional. FieldMask to specify which fields to update.
     * If not provided, all configuration fields in crawler are updated.
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask update_mask = 4;</code>
     * @param \Google\Protobuf\FieldMask $var
     * @return $this
     */
    public function setUpdateMask($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\FieldMask::class);
        $this->update_mask = $var;

        return $this;
    }

    /**
     * Optional. The mask to control which crawler fields get returned.
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask field_mask = 5;</code>
     * @return \Google\Protobuf\FieldMask|null
     */
    public function getFieldMask()
    {
        return $this->field_mask;
    }

    public function hasFieldMask()
    {
        return isset($this->field_mask);
    }

    public function clearFieldMask()
    {
        unset($this->field_mask);
    }

    /**
     * Optional. The mask to control which crawler fields get returned.
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask field_mask = 5;</code>
     * @param \Google\Protobuf\FieldMask $var
     * @return $this
     */
    public function setFieldMask($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\FieldMask::class);
        $this->field_mask = $var;

        return $this;
    }

}

