<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/nlu/agent.proto

namespace Ondewo\Nlu;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * This message contains the configuration to run Optimize Ranking Match
 *
 * Generated from protobuf message <code>ondewo.nlu.RankingMatchOptimizationConfig</code>
 */
class RankingMatchOptimizationConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Language code specifies the language of the request in IETF BCP 47 language tag format, e.g. de-DE, en-US, etc.
     *
     * Generated from protobuf field <code>string language_code = 1;</code>
     */
    protected $language_code = '';
    /**
     * number of splits for optimization
     *
     * Generated from protobuf field <code>int32 n_splits = 2;</code>
     */
    protected $n_splits = 0;
    /**
     * random seed number for defining the split of train and test of training phrases for optimization
     *
     * Generated from protobuf field <code>int32 random_seed = 3;</code>
     */
    protected $random_seed = 0;
    /**
     * initial thresholds are optional, if not given will be taken from the current config
     * <br>
     * example {'OndewoIntentSimilarityMatch': 0.59, 'OndewoIntentNamedSimilarityMatch': 0.39}
     * <br>
     *
     * Generated from protobuf field <code>.google.protobuf.Struct initial_thresholds = 4;</code>
     */
    protected $initial_thresholds = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $language_code
     *           Language code specifies the language of the request in IETF BCP 47 language tag format, e.g. de-DE, en-US, etc.
     *     @type int $n_splits
     *           number of splits for optimization
     *     @type int $random_seed
     *           random seed number for defining the split of train and test of training phrases for optimization
     *     @type \Google\Protobuf\Struct $initial_thresholds
     *           initial thresholds are optional, if not given will be taken from the current config
     *           <br>
     *           example {'OndewoIntentSimilarityMatch': 0.59, 'OndewoIntentNamedSimilarityMatch': 0.39}
     *           <br>
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Nlu\Agent::initOnce();
        parent::__construct($data);
    }

    /**
     * Language code specifies the language of the request in IETF BCP 47 language tag format, e.g. de-DE, en-US, etc.
     *
     * Generated from protobuf field <code>string language_code = 1;</code>
     * @return string
     */
    public function getLanguageCode()
    {
        return $this->language_code;
    }

    /**
     * Language code specifies the language of the request in IETF BCP 47 language tag format, e.g. de-DE, en-US, etc.
     *
     * Generated from protobuf field <code>string language_code = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setLanguageCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->language_code = $var;

        return $this;
    }

    /**
     * number of splits for optimization
     *
     * Generated from protobuf field <code>int32 n_splits = 2;</code>
     * @return int
     */
    public function getNSplits()
    {
        return $this->n_splits;
    }

    /**
     * number of splits for optimization
     *
     * Generated from protobuf field <code>int32 n_splits = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setNSplits($var)
    {
        GPBUtil::checkInt32($var);
        $this->n_splits = $var;

        return $this;
    }

    /**
     * random seed number for defining the split of train and test of training phrases for optimization
     *
     * Generated from protobuf field <code>int32 random_seed = 3;</code>
     * @return int
     */
    public function getRandomSeed()
    {
        return $this->random_seed;
    }

    /**
     * random seed number for defining the split of train and test of training phrases for optimization
     *
     * Generated from protobuf field <code>int32 random_seed = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setRandomSeed($var)
    {
        GPBUtil::checkInt32($var);
        $this->random_seed = $var;

        return $this;
    }

    /**
     * initial thresholds are optional, if not given will be taken from the current config
     * <br>
     * example {'OndewoIntentSimilarityMatch': 0.59, 'OndewoIntentNamedSimilarityMatch': 0.39}
     * <br>
     *
     * Generated from protobuf field <code>.google.protobuf.Struct initial_thresholds = 4;</code>
     * @return \Google\Protobuf\Struct|null
     */
    public function getInitialThresholds()
    {
        return $this->initial_thresholds;
    }

    public function hasInitialThresholds()
    {
        return isset($this->initial_thresholds);
    }

    public function clearInitialThresholds()
    {
        unset($this->initial_thresholds);
    }

    /**
     * initial thresholds are optional, if not given will be taken from the current config
     * <br>
     * example {'OndewoIntentSimilarityMatch': 0.59, 'OndewoIntentNamedSimilarityMatch': 0.39}
     * <br>
     *
     * Generated from protobuf field <code>.google.protobuf.Struct initial_thresholds = 4;</code>
     * @param \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setInitialThresholds($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->initial_thresholds = $var;

        return $this;
    }

}

