<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/nlu/session.proto

namespace Ondewo\Nlu;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * This message contains a session filter
 *
 * Generated from protobuf message <code>ondewo.nlu.SessionFilter</code>
 */
class SessionFilter extends \Google\Protobuf\Internal\Message
{
    /**
     * A SessionFilter can be used in some requests to return only sessions matching certain filter conditions.
     * All fields below are optional. Multiple fields specified at the same time are chained via AND.
     * Match only sessions with all of the following language_codes
     *
     * Generated from protobuf field <code>repeated string language_codes = 1;</code>
     */
    private $language_codes;
    /**
     * Match only sessions during which all of the following intents were detected
     * NOTE: only name and display name fields are used for comparison
     *
     * Generated from protobuf field <code>repeated .ondewo.nlu.Intent matched_intents = 2;</code>
     */
    private $matched_intents;
    /**
     * Match only sessions during which all of the following entity types were recognized
     * NOTE: only name and display name fields are used for comparison
     *
     * Generated from protobuf field <code>repeated .ondewo.nlu.EntityType matched_entity_types = 3;</code>
     */
    private $matched_entity_types;
    /**
     * Match only sessions where the minimum confidence for intent detection along the session falls
     * in the following range. Defaults to -1 if not set.
     *
     * Generated from protobuf field <code>float min_intents_confidence_min = 4;</code>
     */
    protected $min_intents_confidence_min = 0.0;
    /**
     * Match only sessions where the minimum confidence for intent detection along the session falls
     * in the following range. Defaults to +1 if not set.
     *
     * Generated from protobuf field <code>float min_intents_confidence_max = 5;</code>
     */
    protected $min_intents_confidence_max = 0.0;
    /**
     * Match only sessions where the minimum confidence for entity recognition along the session falls
     *  in the following range. Defaults to -1 if not set.
     *
     * Generated from protobuf field <code>float min_entity_types_confidence_min = 6;</code>
     */
    protected $min_entity_types_confidence_min = 0.0;
    /**
     * Match only sessions where the minimum confidence for entity recognition along the session falls
     *  in the following range. Defaults to +1 if not set.
     *
     * Generated from protobuf field <code>float min_entity_types_confidence_max = 7;</code>
     */
    protected $min_entity_types_confidence_max = 0.0;
    /**
     * Match only sessions whose time range falls within the following range (in UNIX epochs).
     * Defaults to 0 if not set.
     *
     * Generated from protobuf field <code>double earliest = 8;</code>
     */
    protected $earliest = 0.0;
    /**
     * Match only sessions whose time range falls within the following range (in UNIX epochs).
     * Defaults to current epoch if not set
     *
     * Generated from protobuf field <code>double latest = 9;</code>
     */
    protected $latest = 0.0;
    /**
     * Match only sessions for which the number of turns (interaction steps) falls in the following range
     * Defaults to 0 if not set.
     *
     * Generated from protobuf field <code>int32 min_number_turns = 10;</code>
     */
    protected $min_number_turns = 0;
    /**
     * Match only sessions for which the number of turns (interaction steps) falls in the following range
     * Defaults to MAXINT if not set.
     *
     * Generated from protobuf field <code>int32 max_number_turns = 11;</code>
     */
    protected $max_number_turns = 0;
    /**
     * Match only session which have all of the following labels assigned
     *
     * Generated from protobuf field <code>repeated string labels = 12;</code>
     */
    private $labels;
    /**
     * Match only session which had all of the following user_ids interacting with them.
     *
     * Generated from protobuf field <code>repeated string user_ids = 13;</code>
     */
    private $user_ids;
    /**
     * Match only session which have all of the following intent tags assigned
     *
     * Generated from protobuf field <code>repeated string intent_tags = 14;</code>
     */
    private $intent_tags;
    /**
     * Match only sessions whose IDs are specified here
     *
     * Generated from protobuf field <code>repeated string session_ids = 15;</code>
     */
    private $session_ids;
    /**
     * Match only sessions whose session info contains at least one step having all the contexts specified here
     * The input contexts are pre-conditions for detecting intents
     *
     * Generated from protobuf field <code>repeated .ondewo.nlu.Context input_contexts = 16;</code>
     */
    private $input_contexts;
    /**
     * The output contexts are the result of the intent matching and track the contextual state of a conversation
     *
     * Generated from protobuf field <code>repeated .ondewo.nlu.Context output_contexts = 17;</code>
     */
    private $output_contexts;
    /**
     * Match only sessions for which the duration in seconds are larger or equal
     *
     * Generated from protobuf field <code>float duration_in_s_min = 18;</code>
     */
    protected $duration_in_s_min = 0.0;
    /**
     * Match only sessions for which the duration in seconds are smaller or equal
     *
     * Generated from protobuf field <code>float duration_in_s_max = 19;</code>
     */
    protected $duration_in_s_max = 0.0;
    /**
     * Match only sessions for which the duration in minutes are larger or equal
     *
     * Generated from protobuf field <code>float duration_in_m_min = 20;</code>
     */
    protected $duration_in_m_min = 0.0;
    /**
     * Match only sessions for which the duration in minutes are smaller or equal
     *
     * Generated from protobuf field <code>float duration_in_m_max = 21;</code>
     */
    protected $duration_in_m_max = 0.0;
    /**
     * Match only sessions for which the duration in minutes rounded are larger or equal
     *
     * Generated from protobuf field <code>float duration_in_m_rounded_min = 22;</code>
     */
    protected $duration_in_m_rounded_min = 0.0;
    /**
     * Match only sessions for which the duration in minutes rounded are smaller or equal
     *
     * Generated from protobuf field <code>float duration_in_m_rounded_max = 23;</code>
     */
    protected $duration_in_m_rounded_max = 0.0;
    /**
     * Match only sessions for which the duration in 15 seconds rounded are larger or equal
     *
     * Generated from protobuf field <code>float duration_interval_15s_rounded_min = 24;</code>
     */
    protected $duration_interval_15s_rounded_min = 0.0;
    /**
     * Match only sessions for which the duration in 15 seconds rounded are smaller or equal
     *
     * Generated from protobuf field <code>float duration_interval_15s_rounded_max = 25;</code>
     */
    protected $duration_interval_15s_rounded_max = 0.0;
    /**
     * Match only sessions for which the duration in 30 seconds rounded are larger or equal
     *
     * Generated from protobuf field <code>float duration_interval_30s_rounded_min = 26;</code>
     */
    protected $duration_interval_30s_rounded_min = 0.0;
    /**
     * Match only sessions for which the duration in 30 seconds rounded are smaller or equal
     *
     * Generated from protobuf field <code>float duration_interval_30s_rounded_max = 27;</code>
     */
    protected $duration_interval_30s_rounded_max = 0.0;
    /**
     * Match only sessions for which the duration in 45 seconds rounded are larger or equal
     *
     * Generated from protobuf field <code>float duration_interval_45s_rounded_min = 28;</code>
     */
    protected $duration_interval_45s_rounded_min = 0.0;
    /**
     * Match only sessions for which the duration in 45 seconds rounded are smaller or equal
     *
     * Generated from protobuf field <code>float duration_interval_45s_rounded_max = 29;</code>
     */
    protected $duration_interval_45s_rounded_max = 0.0;
    /**
     * Match only sessions for which the started_time_slot_per_hour (e.g. 08:00) are larger or equal
     *
     * Generated from protobuf field <code>string started_time_slot_per_hour_min = 30;</code>
     */
    protected $started_time_slot_per_hour_min = '';
    /**
     * Match only sessions for which the started_time_slot_per_hour (e.g. 14:00) are smaller or equal
     *
     * Generated from protobuf field <code>string started_time_slot_per_hour_max = 31;</code>
     */
    protected $started_time_slot_per_hour_max = '';
    /**
     * Match only sessions for which the started_time_slot_per_quarter_hour (e.g. 08:00) are larger or equal
     *
     * Generated from protobuf field <code>string started_time_slot_per_quarter_hour_min = 32;</code>
     */
    protected $started_time_slot_per_quarter_hour_min = '';
    /**
     * Match only sessions for which the started_time_slot_per_quarter_hour (e.g. 14:00) are smaller or equal
     *
     * Generated from protobuf field <code>string started_time_slot_per_quarter_hour_max = 33;</code>
     */
    protected $started_time_slot_per_quarter_hour_max = '';
    /**
     * Match only sessions for which the started_time_slot_per_half_hour (e.g. 08:00) are larger or equal
     *
     * Generated from protobuf field <code>string started_time_slot_per_half_hour_min = 34;</code>
     */
    protected $started_time_slot_per_half_hour_min = '';
    /**
     * Match only sessions for which the started_time_slot_per_half_hour (e.g. 14:00) are smaller or equal
     *
     * Generated from protobuf field <code>string started_time_slot_per_half_hour_max = 35;</code>
     */
    protected $started_time_slot_per_half_hour_max = '';
    /**
     * Match only sessions for which the started_time_slot_per_day_phase (e.g. 08:00) are larger or equal
     *
     * Generated from protobuf field <code>string started_time_slot_per_day_phase_min = 36;</code>
     */
    protected $started_time_slot_per_day_phase_min = '';
    /**
     * Match only sessions for which the started_time_slot_per_day_phase (e.g. 14:00) are smaller or equal
     *
     * Generated from protobuf field <code>string started_time_slot_per_day_phase_max = 37;</code>
     */
    protected $started_time_slot_per_day_phase_max = '';
    /**
     * Match only sessions for which the started_time_slot_per_minute (e.g. 08:00) are larger or equal
     *
     * Generated from protobuf field <code>string started_time_slot_per_minute_min = 38;</code>
     */
    protected $started_time_slot_per_minute_min = '';
    /**
     * Match only sessions for which the started_time_slot_per_minute (e.g. 14:00) are smaller or equal
     *
     * Generated from protobuf field <code>string started_time_slot_per_minute_max = 39;</code>
     */
    protected $started_time_slot_per_minute_max = '';
    /**
     * Match only sessions for which the duration in seconds rounded are larger or equal
     *
     * Generated from protobuf field <code>float duration_in_s_rounded_min = 40;</code>
     */
    protected $duration_in_s_rounded_min = 0.0;
    /**
     * Match only sessions for which the duration in seconds rounded are smaller or equal
     *
     * Generated from protobuf field <code>float duration_in_s_rounded_max = 41;</code>
     */
    protected $duration_in_s_rounded_max = 0.0;
    /**
     * Messages for each of the Intent.Message.Platform were sent to the user
     *
     * Generated from protobuf field <code>repeated .ondewo.nlu.Intent.Message.Platform platforms = 42;</code>
     */
    private $platforms;
    /**
     * Ids of the account, e.g. Company Ondewo,
     * This field can also be used for customized tracking ids or tag ids
     *
     * Generated from protobuf field <code>repeated string account_ids = 43;</code>
     */
    private $account_ids;
    /**
     * Ids of the property of the account, e.g. Domain ondewo.com
     * This field can also be used for customized tracking ids or tag ids
     *
     * Generated from protobuf field <code>repeated string property_ids = 44;</code>
     */
    private $property_ids;
    /**
     * Ids of the datastream of the property of the account, e.g. Subdomain sub1.ondewo.com or sub2.ondewo.com
     * This field can also be used for customized tracking ids or tag ids
     *
     * Generated from protobuf field <code>repeated string datastream_ids = 45;</code>
     */
    private $datastream_ids;
    /**
     * Ids of the the origin of the user request
     * For a phone bot, this is the phone number +123456789 the user called (Note: This is not the user's phone number)
     * For a chatbot or voicebot on the web, this is the URL on which the bo, e.g. https://ondewo.com/webchat
     * For a voice assistant device, this is the device-id or the app id
     *
     * Generated from protobuf field <code>repeated string origin_ids = 46;</code>
     */
    private $origin_ids;
    /**
     * Ids of the "identified user" e.g. for a chatbot the email address or for a phone bot the phone number of the user
     *
     * Generated from protobuf field <code>repeated string identified_user_ids = 47;</code>
     */
    private $identified_user_ids;
    /**
     * Match only sessions for which the duration in 60 seconds rounded are larger or equal
     *
     * Generated from protobuf field <code>float duration_interval_60s_rounded_min = 48;</code>
     */
    protected $duration_interval_60s_rounded_min = 0.0;
    /**
     * Match only sessions for which the duration in 60 seconds rounded are smaller or equal
     *
     * Generated from protobuf field <code>float duration_interval_60s_rounded_max = 49;</code>
     */
    protected $duration_interval_60s_rounded_max = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[] $language_codes
     *           A SessionFilter can be used in some requests to return only sessions matching certain filter conditions.
     *           All fields below are optional. Multiple fields specified at the same time are chained via AND.
     *           Match only sessions with all of the following language_codes
     *     @type \Ondewo\Nlu\Intent[] $matched_intents
     *           Match only sessions during which all of the following intents were detected
     *           NOTE: only name and display name fields are used for comparison
     *     @type \Ondewo\Nlu\EntityType[] $matched_entity_types
     *           Match only sessions during which all of the following entity types were recognized
     *           NOTE: only name and display name fields are used for comparison
     *     @type float $min_intents_confidence_min
     *           Match only sessions where the minimum confidence for intent detection along the session falls
     *           in the following range. Defaults to -1 if not set.
     *     @type float $min_intents_confidence_max
     *           Match only sessions where the minimum confidence for intent detection along the session falls
     *           in the following range. Defaults to +1 if not set.
     *     @type float $min_entity_types_confidence_min
     *           Match only sessions where the minimum confidence for entity recognition along the session falls
     *            in the following range. Defaults to -1 if not set.
     *     @type float $min_entity_types_confidence_max
     *           Match only sessions where the minimum confidence for entity recognition along the session falls
     *            in the following range. Defaults to +1 if not set.
     *     @type float $earliest
     *           Match only sessions whose time range falls within the following range (in UNIX epochs).
     *           Defaults to 0 if not set.
     *     @type float $latest
     *           Match only sessions whose time range falls within the following range (in UNIX epochs).
     *           Defaults to current epoch if not set
     *     @type int $min_number_turns
     *           Match only sessions for which the number of turns (interaction steps) falls in the following range
     *           Defaults to 0 if not set.
     *     @type int $max_number_turns
     *           Match only sessions for which the number of turns (interaction steps) falls in the following range
     *           Defaults to MAXINT if not set.
     *     @type string[] $labels
     *           Match only session which have all of the following labels assigned
     *     @type string[] $user_ids
     *           Match only session which had all of the following user_ids interacting with them.
     *     @type string[] $intent_tags
     *           Match only session which have all of the following intent tags assigned
     *     @type string[] $session_ids
     *           Match only sessions whose IDs are specified here
     *     @type \Ondewo\Nlu\Context[] $input_contexts
     *           Match only sessions whose session info contains at least one step having all the contexts specified here
     *           The input contexts are pre-conditions for detecting intents
     *     @type \Ondewo\Nlu\Context[] $output_contexts
     *           The output contexts are the result of the intent matching and track the contextual state of a conversation
     *     @type float $duration_in_s_min
     *           Match only sessions for which the duration in seconds are larger or equal
     *     @type float $duration_in_s_max
     *           Match only sessions for which the duration in seconds are smaller or equal
     *     @type float $duration_in_m_min
     *           Match only sessions for which the duration in minutes are larger or equal
     *     @type float $duration_in_m_max
     *           Match only sessions for which the duration in minutes are smaller or equal
     *     @type float $duration_in_m_rounded_min
     *           Match only sessions for which the duration in minutes rounded are larger or equal
     *     @type float $duration_in_m_rounded_max
     *           Match only sessions for which the duration in minutes rounded are smaller or equal
     *     @type float $duration_interval_15s_rounded_min
     *           Match only sessions for which the duration in 15 seconds rounded are larger or equal
     *     @type float $duration_interval_15s_rounded_max
     *           Match only sessions for which the duration in 15 seconds rounded are smaller or equal
     *     @type float $duration_interval_30s_rounded_min
     *           Match only sessions for which the duration in 30 seconds rounded are larger or equal
     *     @type float $duration_interval_30s_rounded_max
     *           Match only sessions for which the duration in 30 seconds rounded are smaller or equal
     *     @type float $duration_interval_45s_rounded_min
     *           Match only sessions for which the duration in 45 seconds rounded are larger or equal
     *     @type float $duration_interval_45s_rounded_max
     *           Match only sessions for which the duration in 45 seconds rounded are smaller or equal
     *     @type string $started_time_slot_per_hour_min
     *           Match only sessions for which the started_time_slot_per_hour (e.g. 08:00) are larger or equal
     *     @type string $started_time_slot_per_hour_max
     *           Match only sessions for which the started_time_slot_per_hour (e.g. 14:00) are smaller or equal
     *     @type string $started_time_slot_per_quarter_hour_min
     *           Match only sessions for which the started_time_slot_per_quarter_hour (e.g. 08:00) are larger or equal
     *     @type string $started_time_slot_per_quarter_hour_max
     *           Match only sessions for which the started_time_slot_per_quarter_hour (e.g. 14:00) are smaller or equal
     *     @type string $started_time_slot_per_half_hour_min
     *           Match only sessions for which the started_time_slot_per_half_hour (e.g. 08:00) are larger or equal
     *     @type string $started_time_slot_per_half_hour_max
     *           Match only sessions for which the started_time_slot_per_half_hour (e.g. 14:00) are smaller or equal
     *     @type string $started_time_slot_per_day_phase_min
     *           Match only sessions for which the started_time_slot_per_day_phase (e.g. 08:00) are larger or equal
     *     @type string $started_time_slot_per_day_phase_max
     *           Match only sessions for which the started_time_slot_per_day_phase (e.g. 14:00) are smaller or equal
     *     @type string $started_time_slot_per_minute_min
     *           Match only sessions for which the started_time_slot_per_minute (e.g. 08:00) are larger or equal
     *     @type string $started_time_slot_per_minute_max
     *           Match only sessions for which the started_time_slot_per_minute (e.g. 14:00) are smaller or equal
     *     @type float $duration_in_s_rounded_min
     *           Match only sessions for which the duration in seconds rounded are larger or equal
     *     @type float $duration_in_s_rounded_max
     *           Match only sessions for which the duration in seconds rounded are smaller or equal
     *     @type int[] $platforms
     *           Messages for each of the Intent.Message.Platform were sent to the user
     *     @type string[] $account_ids
     *           Ids of the account, e.g. Company Ondewo,
     *           This field can also be used for customized tracking ids or tag ids
     *     @type string[] $property_ids
     *           Ids of the property of the account, e.g. Domain ondewo.com
     *           This field can also be used for customized tracking ids or tag ids
     *     @type string[] $datastream_ids
     *           Ids of the datastream of the property of the account, e.g. Subdomain sub1.ondewo.com or sub2.ondewo.com
     *           This field can also be used for customized tracking ids or tag ids
     *     @type string[] $origin_ids
     *           Ids of the the origin of the user request
     *           For a phone bot, this is the phone number +123456789 the user called (Note: This is not the user's phone number)
     *           For a chatbot or voicebot on the web, this is the URL on which the bo, e.g. https://ondewo.com/webchat
     *           For a voice assistant device, this is the device-id or the app id
     *     @type string[] $identified_user_ids
     *           Ids of the "identified user" e.g. for a chatbot the email address or for a phone bot the phone number of the user
     *     @type float $duration_interval_60s_rounded_min
     *           Match only sessions for which the duration in 60 seconds rounded are larger or equal
     *     @type float $duration_interval_60s_rounded_max
     *           Match only sessions for which the duration in 60 seconds rounded are smaller or equal
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Nlu\Session::initOnce();
        parent::__construct($data);
    }

    /**
     * A SessionFilter can be used in some requests to return only sessions matching certain filter conditions.
     * All fields below are optional. Multiple fields specified at the same time are chained via AND.
     * Match only sessions with all of the following language_codes
     *
     * Generated from protobuf field <code>repeated string language_codes = 1;</code>
     * @return RepeatedField<string>
     */
    public function getLanguageCodes()
    {
        return $this->language_codes;
    }

    /**
     * A SessionFilter can be used in some requests to return only sessions matching certain filter conditions.
     * All fields below are optional. Multiple fields specified at the same time are chained via AND.
     * Match only sessions with all of the following language_codes
     *
     * Generated from protobuf field <code>repeated string language_codes = 1;</code>
     * @param string[] $var
     * @return $this
     */
    public function setLanguageCodes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->language_codes = $arr;

        return $this;
    }

    /**
     * Match only sessions during which all of the following intents were detected
     * NOTE: only name and display name fields are used for comparison
     *
     * Generated from protobuf field <code>repeated .ondewo.nlu.Intent matched_intents = 2;</code>
     * @return RepeatedField<\Ondewo\Nlu\Intent>
     */
    public function getMatchedIntents()
    {
        return $this->matched_intents;
    }

    /**
     * Match only sessions during which all of the following intents were detected
     * NOTE: only name and display name fields are used for comparison
     *
     * Generated from protobuf field <code>repeated .ondewo.nlu.Intent matched_intents = 2;</code>
     * @param \Ondewo\Nlu\Intent[] $var
     * @return $this
     */
    public function setMatchedIntents($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Ondewo\Nlu\Intent::class);
        $this->matched_intents = $arr;

        return $this;
    }

    /**
     * Match only sessions during which all of the following entity types were recognized
     * NOTE: only name and display name fields are used for comparison
     *
     * Generated from protobuf field <code>repeated .ondewo.nlu.EntityType matched_entity_types = 3;</code>
     * @return RepeatedField<\Ondewo\Nlu\EntityType>
     */
    public function getMatchedEntityTypes()
    {
        return $this->matched_entity_types;
    }

    /**
     * Match only sessions during which all of the following entity types were recognized
     * NOTE: only name and display name fields are used for comparison
     *
     * Generated from protobuf field <code>repeated .ondewo.nlu.EntityType matched_entity_types = 3;</code>
     * @param \Ondewo\Nlu\EntityType[] $var
     * @return $this
     */
    public function setMatchedEntityTypes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Ondewo\Nlu\EntityType::class);
        $this->matched_entity_types = $arr;

        return $this;
    }

    /**
     * Match only sessions where the minimum confidence for intent detection along the session falls
     * in the following range. Defaults to -1 if not set.
     *
     * Generated from protobuf field <code>float min_intents_confidence_min = 4;</code>
     * @return float
     */
    public function getMinIntentsConfidenceMin()
    {
        return $this->min_intents_confidence_min;
    }

    /**
     * Match only sessions where the minimum confidence for intent detection along the session falls
     * in the following range. Defaults to -1 if not set.
     *
     * Generated from protobuf field <code>float min_intents_confidence_min = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setMinIntentsConfidenceMin($var)
    {
        GPBUtil::checkFloat($var);
        $this->min_intents_confidence_min = $var;

        return $this;
    }

    /**
     * Match only sessions where the minimum confidence for intent detection along the session falls
     * in the following range. Defaults to +1 if not set.
     *
     * Generated from protobuf field <code>float min_intents_confidence_max = 5;</code>
     * @return float
     */
    public function getMinIntentsConfidenceMax()
    {
        return $this->min_intents_confidence_max;
    }

    /**
     * Match only sessions where the minimum confidence for intent detection along the session falls
     * in the following range. Defaults to +1 if not set.
     *
     * Generated from protobuf field <code>float min_intents_confidence_max = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setMinIntentsConfidenceMax($var)
    {
        GPBUtil::checkFloat($var);
        $this->min_intents_confidence_max = $var;

        return $this;
    }

    /**
     * Match only sessions where the minimum confidence for entity recognition along the session falls
     *  in the following range. Defaults to -1 if not set.
     *
     * Generated from protobuf field <code>float min_entity_types_confidence_min = 6;</code>
     * @return float
     */
    public function getMinEntityTypesConfidenceMin()
    {
        return $this->min_entity_types_confidence_min;
    }

    /**
     * Match only sessions where the minimum confidence for entity recognition along the session falls
     *  in the following range. Defaults to -1 if not set.
     *
     * Generated from protobuf field <code>float min_entity_types_confidence_min = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setMinEntityTypesConfidenceMin($var)
    {
        GPBUtil::checkFloat($var);
        $this->min_entity_types_confidence_min = $var;

        return $this;
    }

    /**
     * Match only sessions where the minimum confidence for entity recognition along the session falls
     *  in the following range. Defaults to +1 if not set.
     *
     * Generated from protobuf field <code>float min_entity_types_confidence_max = 7;</code>
     * @return float
     */
    public function getMinEntityTypesConfidenceMax()
    {
        return $this->min_entity_types_confidence_max;
    }

    /**
     * Match only sessions where the minimum confidence for entity recognition along the session falls
     *  in the following range. Defaults to +1 if not set.
     *
     * Generated from protobuf field <code>float min_entity_types_confidence_max = 7;</code>
     * @param float $var
     * @return $this
     */
    public function setMinEntityTypesConfidenceMax($var)
    {
        GPBUtil::checkFloat($var);
        $this->min_entity_types_confidence_max = $var;

        return $this;
    }

    /**
     * Match only sessions whose time range falls within the following range (in UNIX epochs).
     * Defaults to 0 if not set.
     *
     * Generated from protobuf field <code>double earliest = 8;</code>
     * @return float
     */
    public function getEarliest()
    {
        return $this->earliest;
    }

    /**
     * Match only sessions whose time range falls within the following range (in UNIX epochs).
     * Defaults to 0 if not set.
     *
     * Generated from protobuf field <code>double earliest = 8;</code>
     * @param float $var
     * @return $this
     */
    public function setEarliest($var)
    {
        GPBUtil::checkDouble($var);
        $this->earliest = $var;

        return $this;
    }

    /**
     * Match only sessions whose time range falls within the following range (in UNIX epochs).
     * Defaults to current epoch if not set
     *
     * Generated from protobuf field <code>double latest = 9;</code>
     * @return float
     */
    public function getLatest()
    {
        return $this->latest;
    }

    /**
     * Match only sessions whose time range falls within the following range (in UNIX epochs).
     * Defaults to current epoch if not set
     *
     * Generated from protobuf field <code>double latest = 9;</code>
     * @param float $var
     * @return $this
     */
    public function setLatest($var)
    {
        GPBUtil::checkDouble($var);
        $this->latest = $var;

        return $this;
    }

    /**
     * Match only sessions for which the number of turns (interaction steps) falls in the following range
     * Defaults to 0 if not set.
     *
     * Generated from protobuf field <code>int32 min_number_turns = 10;</code>
     * @return int
     */
    public function getMinNumberTurns()
    {
        return $this->min_number_turns;
    }

    /**
     * Match only sessions for which the number of turns (interaction steps) falls in the following range
     * Defaults to 0 if not set.
     *
     * Generated from protobuf field <code>int32 min_number_turns = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setMinNumberTurns($var)
    {
        GPBUtil::checkInt32($var);
        $this->min_number_turns = $var;

        return $this;
    }

    /**
     * Match only sessions for which the number of turns (interaction steps) falls in the following range
     * Defaults to MAXINT if not set.
     *
     * Generated from protobuf field <code>int32 max_number_turns = 11;</code>
     * @return int
     */
    public function getMaxNumberTurns()
    {
        return $this->max_number_turns;
    }

    /**
     * Match only sessions for which the number of turns (interaction steps) falls in the following range
     * Defaults to MAXINT if not set.
     *
     * Generated from protobuf field <code>int32 max_number_turns = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxNumberTurns($var)
    {
        GPBUtil::checkInt32($var);
        $this->max_number_turns = $var;

        return $this;
    }

    /**
     * Match only session which have all of the following labels assigned
     *
     * Generated from protobuf field <code>repeated string labels = 12;</code>
     * @return RepeatedField<string>
     */
    public function getLabels()
    {
        return $this->labels;
    }

    /**
     * Match only session which have all of the following labels assigned
     *
     * Generated from protobuf field <code>repeated string labels = 12;</code>
     * @param string[] $var
     * @return $this
     */
    public function setLabels($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->labels = $arr;

        return $this;
    }

    /**
     * Match only session which had all of the following user_ids interacting with them.
     *
     * Generated from protobuf field <code>repeated string user_ids = 13;</code>
     * @return RepeatedField<string>
     */
    public function getUserIds()
    {
        return $this->user_ids;
    }

    /**
     * Match only session which had all of the following user_ids interacting with them.
     *
     * Generated from protobuf field <code>repeated string user_ids = 13;</code>
     * @param string[] $var
     * @return $this
     */
    public function setUserIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->user_ids = $arr;

        return $this;
    }

    /**
     * Match only session which have all of the following intent tags assigned
     *
     * Generated from protobuf field <code>repeated string intent_tags = 14;</code>
     * @return RepeatedField<string>
     */
    public function getIntentTags()
    {
        return $this->intent_tags;
    }

    /**
     * Match only session which have all of the following intent tags assigned
     *
     * Generated from protobuf field <code>repeated string intent_tags = 14;</code>
     * @param string[] $var
     * @return $this
     */
    public function setIntentTags($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->intent_tags = $arr;

        return $this;
    }

    /**
     * Match only sessions whose IDs are specified here
     *
     * Generated from protobuf field <code>repeated string session_ids = 15;</code>
     * @return RepeatedField<string>
     */
    public function getSessionIds()
    {
        return $this->session_ids;
    }

    /**
     * Match only sessions whose IDs are specified here
     *
     * Generated from protobuf field <code>repeated string session_ids = 15;</code>
     * @param string[] $var
     * @return $this
     */
    public function setSessionIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->session_ids = $arr;

        return $this;
    }

    /**
     * Match only sessions whose session info contains at least one step having all the contexts specified here
     * The input contexts are pre-conditions for detecting intents
     *
     * Generated from protobuf field <code>repeated .ondewo.nlu.Context input_contexts = 16;</code>
     * @return RepeatedField<\Ondewo\Nlu\Context>
     */
    public function getInputContexts()
    {
        return $this->input_contexts;
    }

    /**
     * Match only sessions whose session info contains at least one step having all the contexts specified here
     * The input contexts are pre-conditions for detecting intents
     *
     * Generated from protobuf field <code>repeated .ondewo.nlu.Context input_contexts = 16;</code>
     * @param \Ondewo\Nlu\Context[] $var
     * @return $this
     */
    public function setInputContexts($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Ondewo\Nlu\Context::class);
        $this->input_contexts = $arr;

        return $this;
    }

    /**
     * The output contexts are the result of the intent matching and track the contextual state of a conversation
     *
     * Generated from protobuf field <code>repeated .ondewo.nlu.Context output_contexts = 17;</code>
     * @return RepeatedField<\Ondewo\Nlu\Context>
     */
    public function getOutputContexts()
    {
        return $this->output_contexts;
    }

    /**
     * The output contexts are the result of the intent matching and track the contextual state of a conversation
     *
     * Generated from protobuf field <code>repeated .ondewo.nlu.Context output_contexts = 17;</code>
     * @param \Ondewo\Nlu\Context[] $var
     * @return $this
     */
    public function setOutputContexts($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Ondewo\Nlu\Context::class);
        $this->output_contexts = $arr;

        return $this;
    }

    /**
     * Match only sessions for which the duration in seconds are larger or equal
     *
     * Generated from protobuf field <code>float duration_in_s_min = 18;</code>
     * @return float
     */
    public function getDurationInSMin()
    {
        return $this->duration_in_s_min;
    }

    /**
     * Match only sessions for which the duration in seconds are larger or equal
     *
     * Generated from protobuf field <code>float duration_in_s_min = 18;</code>
     * @param float $var
     * @return $this
     */
    public function setDurationInSMin($var)
    {
        GPBUtil::checkFloat($var);
        $this->duration_in_s_min = $var;

        return $this;
    }

    /**
     * Match only sessions for which the duration in seconds are smaller or equal
     *
     * Generated from protobuf field <code>float duration_in_s_max = 19;</code>
     * @return float
     */
    public function getDurationInSMax()
    {
        return $this->duration_in_s_max;
    }

    /**
     * Match only sessions for which the duration in seconds are smaller or equal
     *
     * Generated from protobuf field <code>float duration_in_s_max = 19;</code>
     * @param float $var
     * @return $this
     */
    public function setDurationInSMax($var)
    {
        GPBUtil::checkFloat($var);
        $this->duration_in_s_max = $var;

        return $this;
    }

    /**
     * Match only sessions for which the duration in minutes are larger or equal
     *
     * Generated from protobuf field <code>float duration_in_m_min = 20;</code>
     * @return float
     */
    public function getDurationInMMin()
    {
        return $this->duration_in_m_min;
    }

    /**
     * Match only sessions for which the duration in minutes are larger or equal
     *
     * Generated from protobuf field <code>float duration_in_m_min = 20;</code>
     * @param float $var
     * @return $this
     */
    public function setDurationInMMin($var)
    {
        GPBUtil::checkFloat($var);
        $this->duration_in_m_min = $var;

        return $this;
    }

    /**
     * Match only sessions for which the duration in minutes are smaller or equal
     *
     * Generated from protobuf field <code>float duration_in_m_max = 21;</code>
     * @return float
     */
    public function getDurationInMMax()
    {
        return $this->duration_in_m_max;
    }

    /**
     * Match only sessions for which the duration in minutes are smaller or equal
     *
     * Generated from protobuf field <code>float duration_in_m_max = 21;</code>
     * @param float $var
     * @return $this
     */
    public function setDurationInMMax($var)
    {
        GPBUtil::checkFloat($var);
        $this->duration_in_m_max = $var;

        return $this;
    }

    /**
     * Match only sessions for which the duration in minutes rounded are larger or equal
     *
     * Generated from protobuf field <code>float duration_in_m_rounded_min = 22;</code>
     * @return float
     */
    public function getDurationInMRoundedMin()
    {
        return $this->duration_in_m_rounded_min;
    }

    /**
     * Match only sessions for which the duration in minutes rounded are larger or equal
     *
     * Generated from protobuf field <code>float duration_in_m_rounded_min = 22;</code>
     * @param float $var
     * @return $this
     */
    public function setDurationInMRoundedMin($var)
    {
        GPBUtil::checkFloat($var);
        $this->duration_in_m_rounded_min = $var;

        return $this;
    }

    /**
     * Match only sessions for which the duration in minutes rounded are smaller or equal
     *
     * Generated from protobuf field <code>float duration_in_m_rounded_max = 23;</code>
     * @return float
     */
    public function getDurationInMRoundedMax()
    {
        return $this->duration_in_m_rounded_max;
    }

    /**
     * Match only sessions for which the duration in minutes rounded are smaller or equal
     *
     * Generated from protobuf field <code>float duration_in_m_rounded_max = 23;</code>
     * @param float $var
     * @return $this
     */
    public function setDurationInMRoundedMax($var)
    {
        GPBUtil::checkFloat($var);
        $this->duration_in_m_rounded_max = $var;

        return $this;
    }

    /**
     * Match only sessions for which the duration in 15 seconds rounded are larger or equal
     *
     * Generated from protobuf field <code>float duration_interval_15s_rounded_min = 24;</code>
     * @return float
     */
    public function getDurationInterval15SRoundedMin()
    {
        return $this->duration_interval_15s_rounded_min;
    }

    /**
     * Match only sessions for which the duration in 15 seconds rounded are larger or equal
     *
     * Generated from protobuf field <code>float duration_interval_15s_rounded_min = 24;</code>
     * @param float $var
     * @return $this
     */
    public function setDurationInterval15SRoundedMin($var)
    {
        GPBUtil::checkFloat($var);
        $this->duration_interval_15s_rounded_min = $var;

        return $this;
    }

    /**
     * Match only sessions for which the duration in 15 seconds rounded are smaller or equal
     *
     * Generated from protobuf field <code>float duration_interval_15s_rounded_max = 25;</code>
     * @return float
     */
    public function getDurationInterval15SRoundedMax()
    {
        return $this->duration_interval_15s_rounded_max;
    }

    /**
     * Match only sessions for which the duration in 15 seconds rounded are smaller or equal
     *
     * Generated from protobuf field <code>float duration_interval_15s_rounded_max = 25;</code>
     * @param float $var
     * @return $this
     */
    public function setDurationInterval15SRoundedMax($var)
    {
        GPBUtil::checkFloat($var);
        $this->duration_interval_15s_rounded_max = $var;

        return $this;
    }

    /**
     * Match only sessions for which the duration in 30 seconds rounded are larger or equal
     *
     * Generated from protobuf field <code>float duration_interval_30s_rounded_min = 26;</code>
     * @return float
     */
    public function getDurationInterval30SRoundedMin()
    {
        return $this->duration_interval_30s_rounded_min;
    }

    /**
     * Match only sessions for which the duration in 30 seconds rounded are larger or equal
     *
     * Generated from protobuf field <code>float duration_interval_30s_rounded_min = 26;</code>
     * @param float $var
     * @return $this
     */
    public function setDurationInterval30SRoundedMin($var)
    {
        GPBUtil::checkFloat($var);
        $this->duration_interval_30s_rounded_min = $var;

        return $this;
    }

    /**
     * Match only sessions for which the duration in 30 seconds rounded are smaller or equal
     *
     * Generated from protobuf field <code>float duration_interval_30s_rounded_max = 27;</code>
     * @return float
     */
    public function getDurationInterval30SRoundedMax()
    {
        return $this->duration_interval_30s_rounded_max;
    }

    /**
     * Match only sessions for which the duration in 30 seconds rounded are smaller or equal
     *
     * Generated from protobuf field <code>float duration_interval_30s_rounded_max = 27;</code>
     * @param float $var
     * @return $this
     */
    public function setDurationInterval30SRoundedMax($var)
    {
        GPBUtil::checkFloat($var);
        $this->duration_interval_30s_rounded_max = $var;

        return $this;
    }

    /**
     * Match only sessions for which the duration in 45 seconds rounded are larger or equal
     *
     * Generated from protobuf field <code>float duration_interval_45s_rounded_min = 28;</code>
     * @return float
     */
    public function getDurationInterval45SRoundedMin()
    {
        return $this->duration_interval_45s_rounded_min;
    }

    /**
     * Match only sessions for which the duration in 45 seconds rounded are larger or equal
     *
     * Generated from protobuf field <code>float duration_interval_45s_rounded_min = 28;</code>
     * @param float $var
     * @return $this
     */
    public function setDurationInterval45SRoundedMin($var)
    {
        GPBUtil::checkFloat($var);
        $this->duration_interval_45s_rounded_min = $var;

        return $this;
    }

    /**
     * Match only sessions for which the duration in 45 seconds rounded are smaller or equal
     *
     * Generated from protobuf field <code>float duration_interval_45s_rounded_max = 29;</code>
     * @return float
     */
    public function getDurationInterval45SRoundedMax()
    {
        return $this->duration_interval_45s_rounded_max;
    }

    /**
     * Match only sessions for which the duration in 45 seconds rounded are smaller or equal
     *
     * Generated from protobuf field <code>float duration_interval_45s_rounded_max = 29;</code>
     * @param float $var
     * @return $this
     */
    public function setDurationInterval45SRoundedMax($var)
    {
        GPBUtil::checkFloat($var);
        $this->duration_interval_45s_rounded_max = $var;

        return $this;
    }

    /**
     * Match only sessions for which the started_time_slot_per_hour (e.g. 08:00) are larger or equal
     *
     * Generated from protobuf field <code>string started_time_slot_per_hour_min = 30;</code>
     * @return string
     */
    public function getStartedTimeSlotPerHourMin()
    {
        return $this->started_time_slot_per_hour_min;
    }

    /**
     * Match only sessions for which the started_time_slot_per_hour (e.g. 08:00) are larger or equal
     *
     * Generated from protobuf field <code>string started_time_slot_per_hour_min = 30;</code>
     * @param string $var
     * @return $this
     */
    public function setStartedTimeSlotPerHourMin($var)
    {
        GPBUtil::checkString($var, True);
        $this->started_time_slot_per_hour_min = $var;

        return $this;
    }

    /**
     * Match only sessions for which the started_time_slot_per_hour (e.g. 14:00) are smaller or equal
     *
     * Generated from protobuf field <code>string started_time_slot_per_hour_max = 31;</code>
     * @return string
     */
    public function getStartedTimeSlotPerHourMax()
    {
        return $this->started_time_slot_per_hour_max;
    }

    /**
     * Match only sessions for which the started_time_slot_per_hour (e.g. 14:00) are smaller or equal
     *
     * Generated from protobuf field <code>string started_time_slot_per_hour_max = 31;</code>
     * @param string $var
     * @return $this
     */
    public function setStartedTimeSlotPerHourMax($var)
    {
        GPBUtil::checkString($var, True);
        $this->started_time_slot_per_hour_max = $var;

        return $this;
    }

    /**
     * Match only sessions for which the started_time_slot_per_quarter_hour (e.g. 08:00) are larger or equal
     *
     * Generated from protobuf field <code>string started_time_slot_per_quarter_hour_min = 32;</code>
     * @return string
     */
    public function getStartedTimeSlotPerQuarterHourMin()
    {
        return $this->started_time_slot_per_quarter_hour_min;
    }

    /**
     * Match only sessions for which the started_time_slot_per_quarter_hour (e.g. 08:00) are larger or equal
     *
     * Generated from protobuf field <code>string started_time_slot_per_quarter_hour_min = 32;</code>
     * @param string $var
     * @return $this
     */
    public function setStartedTimeSlotPerQuarterHourMin($var)
    {
        GPBUtil::checkString($var, True);
        $this->started_time_slot_per_quarter_hour_min = $var;

        return $this;
    }

    /**
     * Match only sessions for which the started_time_slot_per_quarter_hour (e.g. 14:00) are smaller or equal
     *
     * Generated from protobuf field <code>string started_time_slot_per_quarter_hour_max = 33;</code>
     * @return string
     */
    public function getStartedTimeSlotPerQuarterHourMax()
    {
        return $this->started_time_slot_per_quarter_hour_max;
    }

    /**
     * Match only sessions for which the started_time_slot_per_quarter_hour (e.g. 14:00) are smaller or equal
     *
     * Generated from protobuf field <code>string started_time_slot_per_quarter_hour_max = 33;</code>
     * @param string $var
     * @return $this
     */
    public function setStartedTimeSlotPerQuarterHourMax($var)
    {
        GPBUtil::checkString($var, True);
        $this->started_time_slot_per_quarter_hour_max = $var;

        return $this;
    }

    /**
     * Match only sessions for which the started_time_slot_per_half_hour (e.g. 08:00) are larger or equal
     *
     * Generated from protobuf field <code>string started_time_slot_per_half_hour_min = 34;</code>
     * @return string
     */
    public function getStartedTimeSlotPerHalfHourMin()
    {
        return $this->started_time_slot_per_half_hour_min;
    }

    /**
     * Match only sessions for which the started_time_slot_per_half_hour (e.g. 08:00) are larger or equal
     *
     * Generated from protobuf field <code>string started_time_slot_per_half_hour_min = 34;</code>
     * @param string $var
     * @return $this
     */
    public function setStartedTimeSlotPerHalfHourMin($var)
    {
        GPBUtil::checkString($var, True);
        $this->started_time_slot_per_half_hour_min = $var;

        return $this;
    }

    /**
     * Match only sessions for which the started_time_slot_per_half_hour (e.g. 14:00) are smaller or equal
     *
     * Generated from protobuf field <code>string started_time_slot_per_half_hour_max = 35;</code>
     * @return string
     */
    public function getStartedTimeSlotPerHalfHourMax()
    {
        return $this->started_time_slot_per_half_hour_max;
    }

    /**
     * Match only sessions for which the started_time_slot_per_half_hour (e.g. 14:00) are smaller or equal
     *
     * Generated from protobuf field <code>string started_time_slot_per_half_hour_max = 35;</code>
     * @param string $var
     * @return $this
     */
    public function setStartedTimeSlotPerHalfHourMax($var)
    {
        GPBUtil::checkString($var, True);
        $this->started_time_slot_per_half_hour_max = $var;

        return $this;
    }

    /**
     * Match only sessions for which the started_time_slot_per_day_phase (e.g. 08:00) are larger or equal
     *
     * Generated from protobuf field <code>string started_time_slot_per_day_phase_min = 36;</code>
     * @return string
     */
    public function getStartedTimeSlotPerDayPhaseMin()
    {
        return $this->started_time_slot_per_day_phase_min;
    }

    /**
     * Match only sessions for which the started_time_slot_per_day_phase (e.g. 08:00) are larger or equal
     *
     * Generated from protobuf field <code>string started_time_slot_per_day_phase_min = 36;</code>
     * @param string $var
     * @return $this
     */
    public function setStartedTimeSlotPerDayPhaseMin($var)
    {
        GPBUtil::checkString($var, True);
        $this->started_time_slot_per_day_phase_min = $var;

        return $this;
    }

    /**
     * Match only sessions for which the started_time_slot_per_day_phase (e.g. 14:00) are smaller or equal
     *
     * Generated from protobuf field <code>string started_time_slot_per_day_phase_max = 37;</code>
     * @return string
     */
    public function getStartedTimeSlotPerDayPhaseMax()
    {
        return $this->started_time_slot_per_day_phase_max;
    }

    /**
     * Match only sessions for which the started_time_slot_per_day_phase (e.g. 14:00) are smaller or equal
     *
     * Generated from protobuf field <code>string started_time_slot_per_day_phase_max = 37;</code>
     * @param string $var
     * @return $this
     */
    public function setStartedTimeSlotPerDayPhaseMax($var)
    {
        GPBUtil::checkString($var, True);
        $this->started_time_slot_per_day_phase_max = $var;

        return $this;
    }

    /**
     * Match only sessions for which the started_time_slot_per_minute (e.g. 08:00) are larger or equal
     *
     * Generated from protobuf field <code>string started_time_slot_per_minute_min = 38;</code>
     * @return string
     */
    public function getStartedTimeSlotPerMinuteMin()
    {
        return $this->started_time_slot_per_minute_min;
    }

    /**
     * Match only sessions for which the started_time_slot_per_minute (e.g. 08:00) are larger or equal
     *
     * Generated from protobuf field <code>string started_time_slot_per_minute_min = 38;</code>
     * @param string $var
     * @return $this
     */
    public function setStartedTimeSlotPerMinuteMin($var)
    {
        GPBUtil::checkString($var, True);
        $this->started_time_slot_per_minute_min = $var;

        return $this;
    }

    /**
     * Match only sessions for which the started_time_slot_per_minute (e.g. 14:00) are smaller or equal
     *
     * Generated from protobuf field <code>string started_time_slot_per_minute_max = 39;</code>
     * @return string
     */
    public function getStartedTimeSlotPerMinuteMax()
    {
        return $this->started_time_slot_per_minute_max;
    }

    /**
     * Match only sessions for which the started_time_slot_per_minute (e.g. 14:00) are smaller or equal
     *
     * Generated from protobuf field <code>string started_time_slot_per_minute_max = 39;</code>
     * @param string $var
     * @return $this
     */
    public function setStartedTimeSlotPerMinuteMax($var)
    {
        GPBUtil::checkString($var, True);
        $this->started_time_slot_per_minute_max = $var;

        return $this;
    }

    /**
     * Match only sessions for which the duration in seconds rounded are larger or equal
     *
     * Generated from protobuf field <code>float duration_in_s_rounded_min = 40;</code>
     * @return float
     */
    public function getDurationInSRoundedMin()
    {
        return $this->duration_in_s_rounded_min;
    }

    /**
     * Match only sessions for which the duration in seconds rounded are larger or equal
     *
     * Generated from protobuf field <code>float duration_in_s_rounded_min = 40;</code>
     * @param float $var
     * @return $this
     */
    public function setDurationInSRoundedMin($var)
    {
        GPBUtil::checkFloat($var);
        $this->duration_in_s_rounded_min = $var;

        return $this;
    }

    /**
     * Match only sessions for which the duration in seconds rounded are smaller or equal
     *
     * Generated from protobuf field <code>float duration_in_s_rounded_max = 41;</code>
     * @return float
     */
    public function getDurationInSRoundedMax()
    {
        return $this->duration_in_s_rounded_max;
    }

    /**
     * Match only sessions for which the duration in seconds rounded are smaller or equal
     *
     * Generated from protobuf field <code>float duration_in_s_rounded_max = 41;</code>
     * @param float $var
     * @return $this
     */
    public function setDurationInSRoundedMax($var)
    {
        GPBUtil::checkFloat($var);
        $this->duration_in_s_rounded_max = $var;

        return $this;
    }

    /**
     * Messages for each of the Intent.Message.Platform were sent to the user
     *
     * Generated from protobuf field <code>repeated .ondewo.nlu.Intent.Message.Platform platforms = 42;</code>
     * @return RepeatedField<int>
     */
    public function getPlatforms()
    {
        return $this->platforms;
    }

    /**
     * Messages for each of the Intent.Message.Platform were sent to the user
     *
     * Generated from protobuf field <code>repeated .ondewo.nlu.Intent.Message.Platform platforms = 42;</code>
     * @param int[] $var
     * @return $this
     */
    public function setPlatforms($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Ondewo\Nlu\Intent\Message\Platform::class);
        $this->platforms = $arr;

        return $this;
    }

    /**
     * Ids of the account, e.g. Company Ondewo,
     * This field can also be used for customized tracking ids or tag ids
     *
     * Generated from protobuf field <code>repeated string account_ids = 43;</code>
     * @return RepeatedField<string>
     */
    public function getAccountIds()
    {
        return $this->account_ids;
    }

    /**
     * Ids of the account, e.g. Company Ondewo,
     * This field can also be used for customized tracking ids or tag ids
     *
     * Generated from protobuf field <code>repeated string account_ids = 43;</code>
     * @param string[] $var
     * @return $this
     */
    public function setAccountIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->account_ids = $arr;

        return $this;
    }

    /**
     * Ids of the property of the account, e.g. Domain ondewo.com
     * This field can also be used for customized tracking ids or tag ids
     *
     * Generated from protobuf field <code>repeated string property_ids = 44;</code>
     * @return RepeatedField<string>
     */
    public function getPropertyIds()
    {
        return $this->property_ids;
    }

    /**
     * Ids of the property of the account, e.g. Domain ondewo.com
     * This field can also be used for customized tracking ids or tag ids
     *
     * Generated from protobuf field <code>repeated string property_ids = 44;</code>
     * @param string[] $var
     * @return $this
     */
    public function setPropertyIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->property_ids = $arr;

        return $this;
    }

    /**
     * Ids of the datastream of the property of the account, e.g. Subdomain sub1.ondewo.com or sub2.ondewo.com
     * This field can also be used for customized tracking ids or tag ids
     *
     * Generated from protobuf field <code>repeated string datastream_ids = 45;</code>
     * @return RepeatedField<string>
     */
    public function getDatastreamIds()
    {
        return $this->datastream_ids;
    }

    /**
     * Ids of the datastream of the property of the account, e.g. Subdomain sub1.ondewo.com or sub2.ondewo.com
     * This field can also be used for customized tracking ids or tag ids
     *
     * Generated from protobuf field <code>repeated string datastream_ids = 45;</code>
     * @param string[] $var
     * @return $this
     */
    public function setDatastreamIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->datastream_ids = $arr;

        return $this;
    }

    /**
     * Ids of the the origin of the user request
     * For a phone bot, this is the phone number +123456789 the user called (Note: This is not the user's phone number)
     * For a chatbot or voicebot on the web, this is the URL on which the bo, e.g. https://ondewo.com/webchat
     * For a voice assistant device, this is the device-id or the app id
     *
     * Generated from protobuf field <code>repeated string origin_ids = 46;</code>
     * @return RepeatedField<string>
     */
    public function getOriginIds()
    {
        return $this->origin_ids;
    }

    /**
     * Ids of the the origin of the user request
     * For a phone bot, this is the phone number +123456789 the user called (Note: This is not the user's phone number)
     * For a chatbot or voicebot on the web, this is the URL on which the bo, e.g. https://ondewo.com/webchat
     * For a voice assistant device, this is the device-id or the app id
     *
     * Generated from protobuf field <code>repeated string origin_ids = 46;</code>
     * @param string[] $var
     * @return $this
     */
    public function setOriginIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->origin_ids = $arr;

        return $this;
    }

    /**
     * Ids of the "identified user" e.g. for a chatbot the email address or for a phone bot the phone number of the user
     *
     * Generated from protobuf field <code>repeated string identified_user_ids = 47;</code>
     * @return RepeatedField<string>
     */
    public function getIdentifiedUserIds()
    {
        return $this->identified_user_ids;
    }

    /**
     * Ids of the "identified user" e.g. for a chatbot the email address or for a phone bot the phone number of the user
     *
     * Generated from protobuf field <code>repeated string identified_user_ids = 47;</code>
     * @param string[] $var
     * @return $this
     */
    public function setIdentifiedUserIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->identified_user_ids = $arr;

        return $this;
    }

    /**
     * Match only sessions for which the duration in 60 seconds rounded are larger or equal
     *
     * Generated from protobuf field <code>float duration_interval_60s_rounded_min = 48;</code>
     * @return float
     */
    public function getDurationInterval60SRoundedMin()
    {
        return $this->duration_interval_60s_rounded_min;
    }

    /**
     * Match only sessions for which the duration in 60 seconds rounded are larger or equal
     *
     * Generated from protobuf field <code>float duration_interval_60s_rounded_min = 48;</code>
     * @param float $var
     * @return $this
     */
    public function setDurationInterval60SRoundedMin($var)
    {
        GPBUtil::checkFloat($var);
        $this->duration_interval_60s_rounded_min = $var;

        return $this;
    }

    /**
     * Match only sessions for which the duration in 60 seconds rounded are smaller or equal
     *
     * Generated from protobuf field <code>float duration_interval_60s_rounded_max = 49;</code>
     * @return float
     */
    public function getDurationInterval60SRoundedMax()
    {
        return $this->duration_interval_60s_rounded_max;
    }

    /**
     * Match only sessions for which the duration in 60 seconds rounded are smaller or equal
     *
     * Generated from protobuf field <code>float duration_interval_60s_rounded_max = 49;</code>
     * @param float $var
     * @return $this
     */
    public function setDurationInterval60SRoundedMax($var)
    {
        GPBUtil::checkFloat($var);
        $this->duration_interval_60s_rounded_max = $var;

        return $this;
    }

}

