<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/nlu/ccai_project.proto

namespace Ondewo\Nlu;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Request to updated CCAI service project
 *
 * Generated from protobuf message <code>ondewo.nlu.UpdateCcaiProjectRequest</code>
 */
class UpdateCcaiProjectRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The CcaiProject that should be updated
     *
     * Generated from protobuf field <code>.ondewo.nlu.CcaiProject ccai_project = 1;</code>
     */
    protected $ccai_project = null;
    /**
     * Filter which services should be updated in the CcaiProject
     *
     * Generated from protobuf field <code>.ondewo.nlu.CcaiServiceFilter ccai_service_filter = 2;</code>
     */
    protected $ccai_service_filter = null;
    /**
     * Optional. The mask to control which fields get updated.
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask update_mask = 3;</code>
     */
    protected $update_mask = null;
    /**
     * Required. The nlu agent project of this CcaiProject.
     * Format: <pre><code>projects/&lt;project_uuid&gt;/agent</code></pre>
     *
     * Generated from protobuf field <code>string nlu_project_name = 4;</code>
     */
    protected $nlu_project_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Ondewo\Nlu\CcaiProject $ccai_project
     *           The CcaiProject that should be updated
     *     @type \Ondewo\Nlu\CcaiServiceFilter $ccai_service_filter
     *           Filter which services should be updated in the CcaiProject
     *     @type \Google\Protobuf\FieldMask $update_mask
     *           Optional. The mask to control which fields get updated.
     *     @type string $nlu_project_name
     *           Required. The nlu agent project of this CcaiProject.
     *           Format: <pre><code>projects/&lt;project_uuid&gt;/agent</code></pre>
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Nlu\CcaiProject::initOnce();
        parent::__construct($data);
    }

    /**
     * The CcaiProject that should be updated
     *
     * Generated from protobuf field <code>.ondewo.nlu.CcaiProject ccai_project = 1;</code>
     * @return \Ondewo\Nlu\CcaiProject|null
     */
    public function getCcaiProject()
    {
        return $this->ccai_project;
    }

    public function hasCcaiProject()
    {
        return isset($this->ccai_project);
    }

    public function clearCcaiProject()
    {
        unset($this->ccai_project);
    }

    /**
     * The CcaiProject that should be updated
     *
     * Generated from protobuf field <code>.ondewo.nlu.CcaiProject ccai_project = 1;</code>
     * @param \Ondewo\Nlu\CcaiProject $var
     * @return $this
     */
    public function setCcaiProject($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Nlu\CcaiProject::class);
        $this->ccai_project = $var;

        return $this;
    }

    /**
     * Filter which services should be updated in the CcaiProject
     *
     * Generated from protobuf field <code>.ondewo.nlu.CcaiServiceFilter ccai_service_filter = 2;</code>
     * @return \Ondewo\Nlu\CcaiServiceFilter|null
     */
    public function getCcaiServiceFilter()
    {
        return $this->ccai_service_filter;
    }

    public function hasCcaiServiceFilter()
    {
        return isset($this->ccai_service_filter);
    }

    public function clearCcaiServiceFilter()
    {
        unset($this->ccai_service_filter);
    }

    /**
     * Filter which services should be updated in the CcaiProject
     *
     * Generated from protobuf field <code>.ondewo.nlu.CcaiServiceFilter ccai_service_filter = 2;</code>
     * @param \Ondewo\Nlu\CcaiServiceFilter $var
     * @return $this
     */
    public function setCcaiServiceFilter($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Nlu\CcaiServiceFilter::class);
        $this->ccai_service_filter = $var;

        return $this;
    }

    /**
     * Optional. The mask to control which fields get updated.
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask update_mask = 3;</code>
     * @return \Google\Protobuf\FieldMask|null
     */
    public function getUpdateMask()
    {
        return $this->update_mask;
    }

    public function hasUpdateMask()
    {
        return isset($this->update_mask);
    }

    public function clearUpdateMask()
    {
        unset($this->update_mask);
    }

    /**
     * Optional. The mask to control which fields get updated.
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask update_mask = 3;</code>
     * @param \Google\Protobuf\FieldMask $var
     * @return $this
     */
    public function setUpdateMask($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\FieldMask::class);
        $this->update_mask = $var;

        return $this;
    }

    /**
     * Required. The nlu agent project of this CcaiProject.
     * Format: <pre><code>projects/&lt;project_uuid&gt;/agent</code></pre>
     *
     * Generated from protobuf field <code>string nlu_project_name = 4;</code>
     * @return string
     */
    public function getNluProjectName()
    {
        return $this->nlu_project_name;
    }

    /**
     * Required. The nlu agent project of this CcaiProject.
     * Format: <pre><code>projects/&lt;project_uuid&gt;/agent</code></pre>
     *
     * Generated from protobuf field <code>string nlu_project_name = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setNluProjectName($var)
    {
        GPBUtil::checkString($var, True);
        $this->nlu_project_name = $var;

        return $this;
    }

}

