<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/nlu/llm_evaluation.proto

namespace Ondewo\Nlu;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Request to update an existing feedback record.
 *
 * Generated from protobuf message <code>ondewo.nlu.UpdateLlmEvaluationFeedbackRequest</code>
 */
class UpdateLlmEvaluationFeedbackRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Feedback payload (only fields covered by <code>update_mask</code> are
     * applied; typically <code>score</code>, <code>categorical_value</code>
     * and / or <code>comment</code>).
     *
     * Generated from protobuf field <code>.ondewo.nlu.LlmEvaluationFeedback llm_evaluation_feedback = 1;</code>
     */
    protected $llm_evaluation_feedback = null;
    /**
     * Mask of fields to update on the feedback record.
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask update_mask = 2;</code>
     */
    protected $update_mask = null;
    /**
     * Optional. The mask to control which fields will be filled with data on the
     * returned feedback record.
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask field_mask = 3;</code>
     */
    protected $field_mask = null;
    /**
     * Project owning the feedback.
     * Format: <code>projects/&lt;project_uuid&gt;/agent</code>.
     *
     * Generated from protobuf field <code>string parent = 4;</code>
     */
    protected $parent = '';
    /**
     * BCP-47 language-code scope (required).
     *
     * Generated from protobuf field <code>string language_code = 5;</code>
     */
    protected $language_code = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Ondewo\Nlu\LlmEvaluationFeedback $llm_evaluation_feedback
     *           Feedback payload (only fields covered by <code>update_mask</code> are
     *           applied; typically <code>score</code>, <code>categorical_value</code>
     *           and / or <code>comment</code>).
     *     @type \Google\Protobuf\FieldMask $update_mask
     *           Mask of fields to update on the feedback record.
     *     @type \Google\Protobuf\FieldMask $field_mask
     *           Optional. The mask to control which fields will be filled with data on the
     *           returned feedback record.
     *     @type string $parent
     *           Project owning the feedback.
     *           Format: <code>projects/&lt;project_uuid&gt;/agent</code>.
     *     @type string $language_code
     *           BCP-47 language-code scope (required).
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Nlu\LlmEvaluation::initOnce();
        parent::__construct($data);
    }

    /**
     * Feedback payload (only fields covered by <code>update_mask</code> are
     * applied; typically <code>score</code>, <code>categorical_value</code>
     * and / or <code>comment</code>).
     *
     * Generated from protobuf field <code>.ondewo.nlu.LlmEvaluationFeedback llm_evaluation_feedback = 1;</code>
     * @return \Ondewo\Nlu\LlmEvaluationFeedback|null
     */
    public function getLlmEvaluationFeedback()
    {
        return $this->llm_evaluation_feedback;
    }

    public function hasLlmEvaluationFeedback()
    {
        return isset($this->llm_evaluation_feedback);
    }

    public function clearLlmEvaluationFeedback()
    {
        unset($this->llm_evaluation_feedback);
    }

    /**
     * Feedback payload (only fields covered by <code>update_mask</code> are
     * applied; typically <code>score</code>, <code>categorical_value</code>
     * and / or <code>comment</code>).
     *
     * Generated from protobuf field <code>.ondewo.nlu.LlmEvaluationFeedback llm_evaluation_feedback = 1;</code>
     * @param \Ondewo\Nlu\LlmEvaluationFeedback $var
     * @return $this
     */
    public function setLlmEvaluationFeedback($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Nlu\LlmEvaluationFeedback::class);
        $this->llm_evaluation_feedback = $var;

        return $this;
    }

    /**
     * Mask of fields to update on the feedback record.
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask update_mask = 2;</code>
     * @return \Google\Protobuf\FieldMask|null
     */
    public function getUpdateMask()
    {
        return $this->update_mask;
    }

    public function hasUpdateMask()
    {
        return isset($this->update_mask);
    }

    public function clearUpdateMask()
    {
        unset($this->update_mask);
    }

    /**
     * Mask of fields to update on the feedback record.
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask update_mask = 2;</code>
     * @param \Google\Protobuf\FieldMask $var
     * @return $this
     */
    public function setUpdateMask($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\FieldMask::class);
        $this->update_mask = $var;

        return $this;
    }

    /**
     * Optional. The mask to control which fields will be filled with data on the
     * returned feedback record.
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask field_mask = 3;</code>
     * @return \Google\Protobuf\FieldMask|null
     */
    public function getFieldMask()
    {
        return $this->field_mask;
    }

    public function hasFieldMask()
    {
        return isset($this->field_mask);
    }

    public function clearFieldMask()
    {
        unset($this->field_mask);
    }

    /**
     * Optional. The mask to control which fields will be filled with data on the
     * returned feedback record.
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask field_mask = 3;</code>
     * @param \Google\Protobuf\FieldMask $var
     * @return $this
     */
    public function setFieldMask($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\FieldMask::class);
        $this->field_mask = $var;

        return $this;
    }

    /**
     * Project owning the feedback.
     * Format: <code>projects/&lt;project_uuid&gt;/agent</code>.
     *
     * Generated from protobuf field <code>string parent = 4;</code>
     * @return string
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * Project owning the feedback.
     * Format: <code>projects/&lt;project_uuid&gt;/agent</code>.
     *
     * Generated from protobuf field <code>string parent = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setParent($var)
    {
        GPBUtil::checkString($var, True);
        $this->parent = $var;

        return $this;
    }

    /**
     * BCP-47 language-code scope (required).
     *
     * Generated from protobuf field <code>string language_code = 5;</code>
     * @return string
     */
    public function getLanguageCode()
    {
        return $this->language_code;
    }

    /**
     * BCP-47 language-code scope (required).
     *
     * Generated from protobuf field <code>string language_code = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setLanguageCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->language_code = $var;

        return $this;
    }

}

