<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/nlu/entity_type.proto

namespace Ondewo\Nlu;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * The request message for <a href="index.html#ondewo.nlu.EntityTypes.UpdateEntityType">EntityTypes.UpdateEntityType</a>.
 *
 * Generated from protobuf message <code>ondewo.nlu.UpdateEntityTypeRequest</code>
 */
class UpdateEntityTypeRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Required. The entity type to update.
     * Format: <pre><code>projects/&lt;project_uuid&gt;/agent/entityTypes/&lt;entity_type_uuid&gt;</code></pre>
     *
     * Generated from protobuf field <code>.ondewo.nlu.EntityType entity_type = 1;</code>
     */
    protected $entity_type = null;
    /**
     * Optional. The language of entity synonyms defined in <code>entity_type</code>. If not
     * specified, the agent&apos;s default language is used.
     * <a href="https://dialogflow.com/docs/reference/language">More than a dozen
     * languages</a> are supported.
     * Note: languages must be enabled in the agent, before they can be used.
     *
     * Generated from protobuf field <code>string language_code = 2;</code>
     */
    protected $language_code = '';
    /**
     * Optional. The mask to control which fields get updated.
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask update_mask = 3;</code>
     */
    protected $update_mask = null;
    /**
     * Optional. The resource view to apply to the returned Entity Type
     *
     * Generated from protobuf field <code>.ondewo.nlu.EntityTypeView entity_type_view = 6;</code>
     */
    protected $entity_type_view = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Ondewo\Nlu\EntityType $entity_type
     *           Required. The entity type to update.
     *           Format: <pre><code>projects/&lt;project_uuid&gt;/agent/entityTypes/&lt;entity_type_uuid&gt;</code></pre>
     *     @type string $language_code
     *           Optional. The language of entity synonyms defined in <code>entity_type</code>. If not
     *           specified, the agent&apos;s default language is used.
     *           <a href="https://dialogflow.com/docs/reference/language">More than a dozen
     *           languages</a> are supported.
     *           Note: languages must be enabled in the agent, before they can be used.
     *     @type \Google\Protobuf\FieldMask $update_mask
     *           Optional. The mask to control which fields get updated.
     *     @type int $entity_type_view
     *           Optional. The resource view to apply to the returned Entity Type
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Nlu\EntityType::initOnce();
        parent::__construct($data);
    }

    /**
     * Required. The entity type to update.
     * Format: <pre><code>projects/&lt;project_uuid&gt;/agent/entityTypes/&lt;entity_type_uuid&gt;</code></pre>
     *
     * Generated from protobuf field <code>.ondewo.nlu.EntityType entity_type = 1;</code>
     * @return \Ondewo\Nlu\EntityType|null
     */
    public function getEntityType()
    {
        return $this->entity_type;
    }

    public function hasEntityType()
    {
        return isset($this->entity_type);
    }

    public function clearEntityType()
    {
        unset($this->entity_type);
    }

    /**
     * Required. The entity type to update.
     * Format: <pre><code>projects/&lt;project_uuid&gt;/agent/entityTypes/&lt;entity_type_uuid&gt;</code></pre>
     *
     * Generated from protobuf field <code>.ondewo.nlu.EntityType entity_type = 1;</code>
     * @param \Ondewo\Nlu\EntityType $var
     * @return $this
     */
    public function setEntityType($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Nlu\EntityType::class);
        $this->entity_type = $var;

        return $this;
    }

    /**
     * Optional. The language of entity synonyms defined in <code>entity_type</code>. If not
     * specified, the agent&apos;s default language is used.
     * <a href="https://dialogflow.com/docs/reference/language">More than a dozen
     * languages</a> are supported.
     * Note: languages must be enabled in the agent, before they can be used.
     *
     * Generated from protobuf field <code>string language_code = 2;</code>
     * @return string
     */
    public function getLanguageCode()
    {
        return $this->language_code;
    }

    /**
     * Optional. The language of entity synonyms defined in <code>entity_type</code>. If not
     * specified, the agent&apos;s default language is used.
     * <a href="https://dialogflow.com/docs/reference/language">More than a dozen
     * languages</a> are supported.
     * Note: languages must be enabled in the agent, before they can be used.
     *
     * Generated from protobuf field <code>string language_code = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setLanguageCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->language_code = $var;

        return $this;
    }

    /**
     * Optional. The mask to control which fields get updated.
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask update_mask = 3;</code>
     * @return \Google\Protobuf\FieldMask|null
     */
    public function getUpdateMask()
    {
        return $this->update_mask;
    }

    public function hasUpdateMask()
    {
        return isset($this->update_mask);
    }

    public function clearUpdateMask()
    {
        unset($this->update_mask);
    }

    /**
     * Optional. The mask to control which fields get updated.
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask update_mask = 3;</code>
     * @param \Google\Protobuf\FieldMask $var
     * @return $this
     */
    public function setUpdateMask($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\FieldMask::class);
        $this->update_mask = $var;

        return $this;
    }

    /**
     * Optional. The resource view to apply to the returned Entity Type
     *
     * Generated from protobuf field <code>.ondewo.nlu.EntityTypeView entity_type_view = 6;</code>
     * @return int
     */
    public function getEntityTypeView()
    {
        return $this->entity_type_view;
    }

    /**
     * Optional. The resource view to apply to the returned Entity Type
     *
     * Generated from protobuf field <code>.ondewo.nlu.EntityTypeView entity_type_view = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setEntityTypeView($var)
    {
        GPBUtil::checkEnum($var, \Ondewo\Nlu\EntityTypeView::class);
        $this->entity_type_view = $var;

        return $this;
    }

}

