<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/s2t/speech-to-text.proto

namespace Ondewo\S2t;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * <p>The request message for <code>ListS2tNormalizationPipelines</code>.</p>
 * <p>Filter pipelines by attributes in request.</p>
 *
 * Generated from protobuf message <code>ondewo.s2t.ListS2tNormalizationPipelinesRequest</code>
 */
class ListS2tNormalizationPipelinesRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Optional. Define the language.
     *
     * Generated from protobuf field <code>string language = 1;</code>
     */
    protected $language = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $language
     *           Optional. Define the language.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\S2T\SpeechToText::initOnce();
        parent::__construct($data);
    }

    /**
     * Optional. Define the language.
     *
     * Generated from protobuf field <code>string language = 1;</code>
     * @return string
     */
    public function getLanguage()
    {
        return $this->language;
    }

    /**
     * Optional. Define the language.
     *
     * Generated from protobuf field <code>string language = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setLanguage($var)
    {
        GPBUtil::checkString($var, True);
        $this->language = $var;

        return $this;
    }

}

