<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/s2t/speech-to-text.proto

namespace Ondewo\S2t;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * <p>PostProcessing contains the configuration for post-processing.</p>
 *
 * Generated from protobuf message <code>ondewo.s2t.PostProcessing</code>
 */
class PostProcessing extends \Google\Protobuf\Internal\Message
{
    /**
     * List of names of active post-processors.
     *
     * Generated from protobuf field <code>repeated string pipeline = 1;</code>
     */
    private $pipeline;
    /**
     * Post-processor configurations.
     *
     * Generated from protobuf field <code>.ondewo.s2t.PostProcessors post_processors = 2;</code>
     */
    protected $post_processors = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[] $pipeline
     *           List of names of active post-processors.
     *     @type \Ondewo\S2t\PostProcessors $post_processors
     *           Post-processor configurations.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\S2T\SpeechToText::initOnce();
        parent::__construct($data);
    }

    /**
     * List of names of active post-processors.
     *
     * Generated from protobuf field <code>repeated string pipeline = 1;</code>
     * @return RepeatedField<string>
     */
    public function getPipeline()
    {
        return $this->pipeline;
    }

    /**
     * List of names of active post-processors.
     *
     * Generated from protobuf field <code>repeated string pipeline = 1;</code>
     * @param string[] $var
     * @return $this
     */
    public function setPipeline($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->pipeline = $arr;

        return $this;
    }

    /**
     * Post-processor configurations.
     *
     * Generated from protobuf field <code>.ondewo.s2t.PostProcessors post_processors = 2;</code>
     * @return \Ondewo\S2t\PostProcessors|null
     */
    public function getPostProcessors()
    {
        return $this->post_processors;
    }

    public function hasPostProcessors()
    {
        return isset($this->post_processors);
    }

    public function clearPostProcessors()
    {
        unset($this->post_processors);
    }

    /**
     * Post-processor configurations.
     *
     * Generated from protobuf field <code>.ondewo.s2t.PostProcessors post_processors = 2;</code>
     * @param \Ondewo\S2t\PostProcessors $var
     * @return $this
     */
    public function setPostProcessors($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\S2t\PostProcessors::class);
        $this->post_processors = $var;

        return $this;
    }

}

