<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/s2t/speech-to-text.proto

namespace Ondewo\S2t;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * <p>Configuration of the options to summarization task in LLM post-processing.</p>
 *
 * Generated from protobuf message <code>ondewo.s2t.S2tLlmPostProcessingSummarizationOptions</code>
 */
class S2tLlmPostProcessingSummarizationOptions extends \Google\Protobuf\Internal\Message
{
    /**
     * Optional. Indicates if the summarization task of LLM post-processing is active.
     *
     * Generated from protobuf field <code>optional bool active = 1;</code>
     */
    protected $active = null;
    /**
     * Optional. Custom prompt to guide the LLM for summarization. Overrides the default prompt when set.
     *
     * Generated from protobuf field <code>optional string prompt = 2;</code>
     */
    protected $prompt = null;
    /**
     * Optional. Minimum number of characters of the summary generated in summarization task of LLM post-processing.
     *
     * Generated from protobuf field <code>optional int32 min_chars = 3;</code>
     */
    protected $min_chars = null;
    /**
     * Optional. Maximum number of characters of the summary generated in summarization task of LLM post-processing.
     *
     * Generated from protobuf field <code>optional int32 max_chars = 4;</code>
     */
    protected $max_chars = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $active
     *           Optional. Indicates if the summarization task of LLM post-processing is active.
     *     @type string $prompt
     *           Optional. Custom prompt to guide the LLM for summarization. Overrides the default prompt when set.
     *     @type int $min_chars
     *           Optional. Minimum number of characters of the summary generated in summarization task of LLM post-processing.
     *     @type int $max_chars
     *           Optional. Maximum number of characters of the summary generated in summarization task of LLM post-processing.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\S2T\SpeechToText::initOnce();
        parent::__construct($data);
    }

    /**
     * Optional. Indicates if the summarization task of LLM post-processing is active.
     *
     * Generated from protobuf field <code>optional bool active = 1;</code>
     * @return bool
     */
    public function getActive()
    {
        return isset($this->active) ? $this->active : false;
    }

    public function hasActive()
    {
        return isset($this->active);
    }

    public function clearActive()
    {
        unset($this->active);
    }

    /**
     * Optional. Indicates if the summarization task of LLM post-processing is active.
     *
     * Generated from protobuf field <code>optional bool active = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setActive($var)
    {
        GPBUtil::checkBool($var);
        $this->active = $var;

        return $this;
    }

    /**
     * Optional. Custom prompt to guide the LLM for summarization. Overrides the default prompt when set.
     *
     * Generated from protobuf field <code>optional string prompt = 2;</code>
     * @return string
     */
    public function getPrompt()
    {
        return isset($this->prompt) ? $this->prompt : '';
    }

    public function hasPrompt()
    {
        return isset($this->prompt);
    }

    public function clearPrompt()
    {
        unset($this->prompt);
    }

    /**
     * Optional. Custom prompt to guide the LLM for summarization. Overrides the default prompt when set.
     *
     * Generated from protobuf field <code>optional string prompt = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPrompt($var)
    {
        GPBUtil::checkString($var, True);
        $this->prompt = $var;

        return $this;
    }

    /**
     * Optional. Minimum number of characters of the summary generated in summarization task of LLM post-processing.
     *
     * Generated from protobuf field <code>optional int32 min_chars = 3;</code>
     * @return int
     */
    public function getMinChars()
    {
        return isset($this->min_chars) ? $this->min_chars : 0;
    }

    public function hasMinChars()
    {
        return isset($this->min_chars);
    }

    public function clearMinChars()
    {
        unset($this->min_chars);
    }

    /**
     * Optional. Minimum number of characters of the summary generated in summarization task of LLM post-processing.
     *
     * Generated from protobuf field <code>optional int32 min_chars = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setMinChars($var)
    {
        GPBUtil::checkInt32($var);
        $this->min_chars = $var;

        return $this;
    }

    /**
     * Optional. Maximum number of characters of the summary generated in summarization task of LLM post-processing.
     *
     * Generated from protobuf field <code>optional int32 max_chars = 4;</code>
     * @return int
     */
    public function getMaxChars()
    {
        return isset($this->max_chars) ? $this->max_chars : 0;
    }

    public function hasMaxChars()
    {
        return isset($this->max_chars);
    }

    public function clearMaxChars()
    {
        unset($this->max_chars);
    }

    /**
     * Optional. Maximum number of characters of the summary generated in summarization task of LLM post-processing.
     *
     * Generated from protobuf field <code>optional int32 max_chars = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxChars($var)
    {
        GPBUtil::checkInt32($var);
        $this->max_chars = $var;

        return $this;
    }

}

