<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/s2t/speech-to-text.proto

namespace Ondewo\S2t;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * <p>Request to transcribe an audio stream</p>
 *
 * Generated from protobuf message <code>ondewo.s2t.TranscribeStreamRequest</code>
 */
class TranscribeStreamRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * wav file to transcribe
     *
     * Generated from protobuf field <code>bytes audio_chunk = 1;</code>
     */
    protected $audio_chunk = '';
    /**
     * if it's the final chunk of the stream
     *
     * Generated from protobuf field <code>bool end_of_stream = 2;</code>
     */
    protected $end_of_stream = false;
    /**
     * The configuration to override the default configuration
     *
     * Generated from protobuf field <code>.ondewo.s2t.TranscribeRequestConfig config = 3;</code>
     */
    protected $config = null;
    /**
     * Whether or not to mute the audio signal. Defaults to false.
     *
     * Generated from protobuf field <code>bool mute_audio = 4;</code>
     */
    protected $mute_audio = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $audio_chunk
     *           wav file to transcribe
     *     @type bool $end_of_stream
     *           if it's the final chunk of the stream
     *     @type \Ondewo\S2t\TranscribeRequestConfig $config
     *           The configuration to override the default configuration
     *     @type bool $mute_audio
     *           Whether or not to mute the audio signal. Defaults to false.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\S2T\SpeechToText::initOnce();
        parent::__construct($data);
    }

    /**
     * wav file to transcribe
     *
     * Generated from protobuf field <code>bytes audio_chunk = 1;</code>
     * @return string
     */
    public function getAudioChunk()
    {
        return $this->audio_chunk;
    }

    /**
     * wav file to transcribe
     *
     * Generated from protobuf field <code>bytes audio_chunk = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAudioChunk($var)
    {
        GPBUtil::checkString($var, False);
        $this->audio_chunk = $var;

        return $this;
    }

    /**
     * if it's the final chunk of the stream
     *
     * Generated from protobuf field <code>bool end_of_stream = 2;</code>
     * @return bool
     */
    public function getEndOfStream()
    {
        return $this->end_of_stream;
    }

    /**
     * if it's the final chunk of the stream
     *
     * Generated from protobuf field <code>bool end_of_stream = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setEndOfStream($var)
    {
        GPBUtil::checkBool($var);
        $this->end_of_stream = $var;

        return $this;
    }

    /**
     * The configuration to override the default configuration
     *
     * Generated from protobuf field <code>.ondewo.s2t.TranscribeRequestConfig config = 3;</code>
     * @return \Ondewo\S2t\TranscribeRequestConfig|null
     */
    public function getConfig()
    {
        return $this->config;
    }

    public function hasConfig()
    {
        return isset($this->config);
    }

    public function clearConfig()
    {
        unset($this->config);
    }

    /**
     * The configuration to override the default configuration
     *
     * Generated from protobuf field <code>.ondewo.s2t.TranscribeRequestConfig config = 3;</code>
     * @param \Ondewo\S2t\TranscribeRequestConfig $var
     * @return $this
     */
    public function setConfig($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\S2t\TranscribeRequestConfig::class);
        $this->config = $var;

        return $this;
    }

    /**
     * Whether or not to mute the audio signal. Defaults to false.
     *
     * Generated from protobuf field <code>bool mute_audio = 4;</code>
     * @return bool
     */
    public function getMuteAudio()
    {
        return $this->mute_audio;
    }

    /**
     * Whether or not to mute the audio signal. Defaults to false.
     *
     * Generated from protobuf field <code>bool mute_audio = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setMuteAudio($var)
    {
        GPBUtil::checkBool($var);
        $this->mute_audio = $var;

        return $this;
    }

}

