<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/s2t/speech-to-text.proto

namespace Ondewo\S2t;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * <p>Configuration of the options to detect utterances</p>
 *
 * Generated from protobuf message <code>ondewo.s2t.UtteranceDetectionOptions</code>
 */
class UtteranceDetectionOptions extends \Google\Protobuf\Internal\Message
{
    /**
     * if time between audio chunks exceeds next_chunk_timeout, stream will be stopped
     *
     * Generated from protobuf field <code>float next_chunk_timeout = 2;</code>
     */
    protected $next_chunk_timeout = 0.0;
    protected $oneof_transcribe_not_final;
    protected $oneof_turn_detection;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $transcribe_not_final
     *           Return also immediate transcription results
     *     @type float $next_chunk_timeout
     *           if time between audio chunks exceeds next_chunk_timeout, stream will be stopped
     *     @type \Ondewo\S2t\TurnDetectionOptions $turn_detection
     *           The turn detection options
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\S2T\SpeechToText::initOnce();
        parent::__construct($data);
    }

    /**
     * Return also immediate transcription results
     *
     * Generated from protobuf field <code>bool transcribe_not_final = 1;</code>
     * @return bool
     */
    public function getTranscribeNotFinal()
    {
        return $this->readOneof(1);
    }

    public function hasTranscribeNotFinal()
    {
        return $this->hasOneof(1);
    }

    /**
     * Return also immediate transcription results
     *
     * Generated from protobuf field <code>bool transcribe_not_final = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setTranscribeNotFinal($var)
    {
        GPBUtil::checkBool($var);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * if time between audio chunks exceeds next_chunk_timeout, stream will be stopped
     *
     * Generated from protobuf field <code>float next_chunk_timeout = 2;</code>
     * @return float
     */
    public function getNextChunkTimeout()
    {
        return $this->next_chunk_timeout;
    }

    /**
     * if time between audio chunks exceeds next_chunk_timeout, stream will be stopped
     *
     * Generated from protobuf field <code>float next_chunk_timeout = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setNextChunkTimeout($var)
    {
        GPBUtil::checkFloat($var);
        $this->next_chunk_timeout = $var;

        return $this;
    }

    /**
     * The turn detection options
     *
     * Generated from protobuf field <code>.ondewo.s2t.TurnDetectionOptions turn_detection = 3;</code>
     * @return \Ondewo\S2t\TurnDetectionOptions|null
     */
    public function getTurnDetection()
    {
        return $this->readOneof(3);
    }

    public function hasTurnDetection()
    {
        return $this->hasOneof(3);
    }

    /**
     * The turn detection options
     *
     * Generated from protobuf field <code>.ondewo.s2t.TurnDetectionOptions turn_detection = 3;</code>
     * @param \Ondewo\S2t\TurnDetectionOptions $var
     * @return $this
     */
    public function setTurnDetection($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\S2t\TurnDetectionOptions::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getOneofTranscribeNotFinal()
    {
        return $this->whichOneof("oneof_transcribe_not_final");
    }

    /**
     * @return string
     */
    public function getOneofTurnDetection()
    {
        return $this->whichOneof("oneof_turn_detection");
    }

}

