<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/s2t/speech-to-text.proto

namespace Ondewo\S2t;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * <p>Whisper contains information about the Whisper model.</p>
 *
 * Generated from protobuf message <code>ondewo.s2t.Whisper</code>
 */
class Whisper extends \Google\Protobuf\Internal\Message
{
    /**
     * Path to the model.
     *
     * Generated from protobuf field <code>string model_path = 1;</code>
     */
    protected $model_path = '';
    /**
     * Indicates if GPU is used.
     *
     * Generated from protobuf field <code>bool use_gpu = 2;</code>
     */
    protected $use_gpu = false;
    /**
     * Default language of the model.
     *
     * Generated from protobuf field <code>string language = 3;</code>
     */
    protected $language = '';
    /**
     * Default task of the model.
     *
     * Generated from protobuf field <code>string task = 4;</code>
     */
    protected $task = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $model_path
     *           Path to the model.
     *     @type bool $use_gpu
     *           Indicates if GPU is used.
     *     @type string $language
     *           Default language of the model.
     *     @type string $task
     *           Default task of the model.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\S2T\SpeechToText::initOnce();
        parent::__construct($data);
    }

    /**
     * Path to the model.
     *
     * Generated from protobuf field <code>string model_path = 1;</code>
     * @return string
     */
    public function getModelPath()
    {
        return $this->model_path;
    }

    /**
     * Path to the model.
     *
     * Generated from protobuf field <code>string model_path = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setModelPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->model_path = $var;

        return $this;
    }

    /**
     * Indicates if GPU is used.
     *
     * Generated from protobuf field <code>bool use_gpu = 2;</code>
     * @return bool
     */
    public function getUseGpu()
    {
        return $this->use_gpu;
    }

    /**
     * Indicates if GPU is used.
     *
     * Generated from protobuf field <code>bool use_gpu = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setUseGpu($var)
    {
        GPBUtil::checkBool($var);
        $this->use_gpu = $var;

        return $this;
    }

    /**
     * Default language of the model.
     *
     * Generated from protobuf field <code>string language = 3;</code>
     * @return string
     */
    public function getLanguage()
    {
        return $this->language;
    }

    /**
     * Default language of the model.
     *
     * Generated from protobuf field <code>string language = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setLanguage($var)
    {
        GPBUtil::checkString($var, True);
        $this->language = $var;

        return $this;
    }

    /**
     * Default task of the model.
     *
     * Generated from protobuf field <code>string task = 4;</code>
     * @return string
     */
    public function getTask()
    {
        return $this->task;
    }

    /**
     * Default task of the model.
     *
     * Generated from protobuf field <code>string task = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setTask($var)
    {
        GPBUtil::checkString($var, True);
        $this->task = $var;

        return $this;
    }

}

