<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/t2s/text-to-speech.proto

namespace Ondewo\T2s;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * <p>CustomPhonemizerProto message represents a custom phonemizer.</p>
 *
 * Generated from protobuf message <code>ondewo.t2s.CustomPhonemizerProto</code>
 */
class CustomPhonemizerProto extends \Google\Protobuf\Internal\Message
{
    /**
     * The ID of the custom phonemizer.
     *
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Repeated field of Map messages representing word-to-phoneme mappings.
     *
     * Generated from protobuf field <code>repeated .ondewo.t2s.Map maps = 2;</code>
     */
    private $maps;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *           The ID of the custom phonemizer.
     *     @type \Ondewo\T2s\Map[] $maps
     *           Repeated field of Map messages representing word-to-phoneme mappings.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\T2S\TextToSpeech::initOnce();
        parent::__construct($data);
    }

    /**
     * The ID of the custom phonemizer.
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * The ID of the custom phonemizer.
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Repeated field of Map messages representing word-to-phoneme mappings.
     *
     * Generated from protobuf field <code>repeated .ondewo.t2s.Map maps = 2;</code>
     * @return RepeatedField<\Ondewo\T2s\Map>
     */
    public function getMaps()
    {
        return $this->maps;
    }

    /**
     * Repeated field of Map messages representing word-to-phoneme mappings.
     *
     * Generated from protobuf field <code>repeated .ondewo.t2s.Map maps = 2;</code>
     * @param \Ondewo\T2s\Map[] $var
     * @return $this
     */
    public function setMaps($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Ondewo\T2s\Map::class);
        $this->maps = $arr;

        return $this;
    }

}

