<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/t2s/text-to-speech.proto

namespace Ondewo\T2s;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * <p>Domains Response representation.</p>
 * <p>The response message for ListT2sDomains.</p>
 *
 * Generated from protobuf message <code>ondewo.t2s.ListT2sDomainsResponse</code>
 */
class ListT2sDomainsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Required. Define the domain/ domains that satisfy/ies
     * the specifications in the ListT2sDomainsRequest.
     *
     * Generated from protobuf field <code>repeated string domains = 1;</code>
     */
    private $domains;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[] $domains
     *           Required. Define the domain/ domains that satisfy/ies
     *           the specifications in the ListT2sDomainsRequest.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\T2S\TextToSpeech::initOnce();
        parent::__construct($data);
    }

    /**
     * Required. Define the domain/ domains that satisfy/ies
     * the specifications in the ListT2sDomainsRequest.
     *
     * Generated from protobuf field <code>repeated string domains = 1;</code>
     * @return RepeatedField<string>
     */
    public function getDomains()
    {
        return $this->domains;
    }

    /**
     * Required. Define the domain/ domains that satisfy/ies
     * the specifications in the ListT2sDomainsRequest.
     *
     * Generated from protobuf field <code>repeated string domains = 1;</code>
     * @param string[] $var
     * @return $this
     */
    public function setDomains($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->domains = $arr;

        return $this;
    }

}

