<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/t2s/text-to-speech.proto

namespace Ondewo\T2s;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * <p>NormalizeTextRequest message is used to request text normalization.</p>
 *
 * Generated from protobuf message <code>ondewo.t2s.NormalizeTextRequest</code>
 */
class NormalizeTextRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The ID of the text-to-speech pipeline.
     *
     * Generated from protobuf field <code>string t2s_pipeline_id = 1;</code>
     */
    protected $t2s_pipeline_id = '';
    /**
     * The text to be normalized.
     *
     * Generated from protobuf field <code>string text = 2;</code>
     */
    protected $text = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $t2s_pipeline_id
     *           The ID of the text-to-speech pipeline.
     *     @type string $text
     *           The text to be normalized.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\T2S\TextToSpeech::initOnce();
        parent::__construct($data);
    }

    /**
     * The ID of the text-to-speech pipeline.
     *
     * Generated from protobuf field <code>string t2s_pipeline_id = 1;</code>
     * @return string
     */
    public function getT2SPipelineId()
    {
        return $this->t2s_pipeline_id;
    }

    /**
     * The ID of the text-to-speech pipeline.
     *
     * Generated from protobuf field <code>string t2s_pipeline_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setT2SPipelineId($var)
    {
        GPBUtil::checkString($var, True);
        $this->t2s_pipeline_id = $var;

        return $this;
    }

    /**
     * The text to be normalized.
     *
     * Generated from protobuf field <code>string text = 2;</code>
     * @return string
     */
    public function getText()
    {
        return $this->text;
    }

    /**
     * The text to be normalized.
     *
     * Generated from protobuf field <code>string text = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setText($var)
    {
        GPBUtil::checkString($var, True);
        $this->text = $var;

        return $this;
    }

}

