<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/sip/sip.proto

namespace Ondewo\Sip;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * <p>Configuration of a <code>SipStreamCallAudio</code> stream. Must be the first request of the stream</p>
 *
 * Generated from protobuf message <code>ondewo.sip.SipCallAudioConfig</code>
 */
class SipCallAudioConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Mode of the stream. Unspecified means LISTEN
     *
     * Generated from protobuf field <code>.ondewo.sip.SipCallAudioMode mode = 1;</code>
     */
    protected $mode = 0;
    /**
     * Sample rate in Hz of the audio in both directions: <code>8000</code> or <code>16000</code>. <code>0</code> means
     * <code>16000</code>
     *
     * Generated from protobuf field <code>int32 sample_rate_hz = 2;</code>
     */
    protected $sample_rate_hz = 0;
    /**
     * Frame length in milliseconds. Only <code>20</code> is supported; <code>0</code> means <code>20</code>
     *
     * Generated from protobuf field <code>int32 frame_ms = 3;</code>
     */
    protected $frame_ms = 0;
    /**
     * REQUIRED for TALK: the bot is muted and does not listen while the stream is connected. Released when the stream
     * ends
     *
     * Generated from protobuf field <code>bool take_over = 4;</code>
     */
    protected $take_over = false;
    /**
     * Identifier of the stream for logs and audit correlation, minted by the client (a UUID)
     *
     * Generated from protobuf field <code>string stream_id = 5;</code>
     */
    protected $stream_id = '';
    /**
     * Maximum duration of the stream in seconds. <code>0</code> means the server default (3600)
     *
     * Generated from protobuf field <code>int32 max_duration_s = 6;</code>
     */
    protected $max_duration_s = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $mode
     *           Mode of the stream. Unspecified means LISTEN
     *     @type int $sample_rate_hz
     *           Sample rate in Hz of the audio in both directions: <code>8000</code> or <code>16000</code>. <code>0</code> means
     *           <code>16000</code>
     *     @type int $frame_ms
     *           Frame length in milliseconds. Only <code>20</code> is supported; <code>0</code> means <code>20</code>
     *     @type bool $take_over
     *           REQUIRED for TALK: the bot is muted and does not listen while the stream is connected. Released when the stream
     *           ends
     *     @type string $stream_id
     *           Identifier of the stream for logs and audit correlation, minted by the client (a UUID)
     *     @type int $max_duration_s
     *           Maximum duration of the stream in seconds. <code>0</code> means the server default (3600)
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Sip\Sip::initOnce();
        parent::__construct($data);
    }

    /**
     * Mode of the stream. Unspecified means LISTEN
     *
     * Generated from protobuf field <code>.ondewo.sip.SipCallAudioMode mode = 1;</code>
     * @return int
     */
    public function getMode()
    {
        return $this->mode;
    }

    /**
     * Mode of the stream. Unspecified means LISTEN
     *
     * Generated from protobuf field <code>.ondewo.sip.SipCallAudioMode mode = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setMode($var)
    {
        GPBUtil::checkEnum($var, \Ondewo\Sip\SipCallAudioMode::class);
        $this->mode = $var;

        return $this;
    }

    /**
     * Sample rate in Hz of the audio in both directions: <code>8000</code> or <code>16000</code>. <code>0</code> means
     * <code>16000</code>
     *
     * Generated from protobuf field <code>int32 sample_rate_hz = 2;</code>
     * @return int
     */
    public function getSampleRateHz()
    {
        return $this->sample_rate_hz;
    }

    /**
     * Sample rate in Hz of the audio in both directions: <code>8000</code> or <code>16000</code>. <code>0</code> means
     * <code>16000</code>
     *
     * Generated from protobuf field <code>int32 sample_rate_hz = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setSampleRateHz($var)
    {
        GPBUtil::checkInt32($var);
        $this->sample_rate_hz = $var;

        return $this;
    }

    /**
     * Frame length in milliseconds. Only <code>20</code> is supported; <code>0</code> means <code>20</code>
     *
     * Generated from protobuf field <code>int32 frame_ms = 3;</code>
     * @return int
     */
    public function getFrameMs()
    {
        return $this->frame_ms;
    }

    /**
     * Frame length in milliseconds. Only <code>20</code> is supported; <code>0</code> means <code>20</code>
     *
     * Generated from protobuf field <code>int32 frame_ms = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setFrameMs($var)
    {
        GPBUtil::checkInt32($var);
        $this->frame_ms = $var;

        return $this;
    }

    /**
     * REQUIRED for TALK: the bot is muted and does not listen while the stream is connected. Released when the stream
     * ends
     *
     * Generated from protobuf field <code>bool take_over = 4;</code>
     * @return bool
     */
    public function getTakeOver()
    {
        return $this->take_over;
    }

    /**
     * REQUIRED for TALK: the bot is muted and does not listen while the stream is connected. Released when the stream
     * ends
     *
     * Generated from protobuf field <code>bool take_over = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setTakeOver($var)
    {
        GPBUtil::checkBool($var);
        $this->take_over = $var;

        return $this;
    }

    /**
     * Identifier of the stream for logs and audit correlation, minted by the client (a UUID)
     *
     * Generated from protobuf field <code>string stream_id = 5;</code>
     * @return string
     */
    public function getStreamId()
    {
        return $this->stream_id;
    }

    /**
     * Identifier of the stream for logs and audit correlation, minted by the client (a UUID)
     *
     * Generated from protobuf field <code>string stream_id = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setStreamId($var)
    {
        GPBUtil::checkString($var, True);
        $this->stream_id = $var;

        return $this;
    }

    /**
     * Maximum duration of the stream in seconds. <code>0</code> means the server default (3600)
     *
     * Generated from protobuf field <code>int32 max_duration_s = 6;</code>
     * @return int
     */
    public function getMaxDurationS()
    {
        return $this->max_duration_s;
    }

    /**
     * Maximum duration of the stream in seconds. <code>0</code> means the server default (3600)
     *
     * Generated from protobuf field <code>int32 max_duration_s = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxDurationS($var)
    {
        GPBUtil::checkInt32($var);
        $this->max_duration_s = $var;

        return $this;
    }

}

