<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/vtsi/calls.proto

namespace Ondewo\Vtsi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Minio Audio Object Store
 *
 * Generated from protobuf message <code>ondewo.vtsi.AudioObjectStorageConfig</code>
 */
class AudioObjectStorageConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Audio storage should be activated or not
     *
     * Generated from protobuf field <code>bool activate_audio_object_storage = 1;</code>
     */
    protected $activate_audio_object_storage = false;
    /**
     * Configuration of the Minio Audio Object Store
     *
     * Generated from protobuf field <code>.ondewo.vtsi.AudioObjectStorageServicesActivationConfig audio_object_storage_services_activation_config = 2;</code>
     */
    protected $audio_object_storage_services_activation_config = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $activate_audio_object_storage
     *           Audio storage should be activated or not
     *     @type \Ondewo\Vtsi\AudioObjectStorageServicesActivationConfig $audio_object_storage_services_activation_config
     *           Configuration of the Minio Audio Object Store
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Vtsi\Calls::initOnce();
        parent::__construct($data);
    }

    /**
     * Audio storage should be activated or not
     *
     * Generated from protobuf field <code>bool activate_audio_object_storage = 1;</code>
     * @return bool
     */
    public function getActivateAudioObjectStorage()
    {
        return $this->activate_audio_object_storage;
    }

    /**
     * Audio storage should be activated or not
     *
     * Generated from protobuf field <code>bool activate_audio_object_storage = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setActivateAudioObjectStorage($var)
    {
        GPBUtil::checkBool($var);
        $this->activate_audio_object_storage = $var;

        return $this;
    }

    /**
     * Configuration of the Minio Audio Object Store
     *
     * Generated from protobuf field <code>.ondewo.vtsi.AudioObjectStorageServicesActivationConfig audio_object_storage_services_activation_config = 2;</code>
     * @return \Ondewo\Vtsi\AudioObjectStorageServicesActivationConfig|null
     */
    public function getAudioObjectStorageServicesActivationConfig()
    {
        return $this->audio_object_storage_services_activation_config;
    }

    public function hasAudioObjectStorageServicesActivationConfig()
    {
        return isset($this->audio_object_storage_services_activation_config);
    }

    public function clearAudioObjectStorageServicesActivationConfig()
    {
        unset($this->audio_object_storage_services_activation_config);
    }

    /**
     * Configuration of the Minio Audio Object Store
     *
     * Generated from protobuf field <code>.ondewo.vtsi.AudioObjectStorageServicesActivationConfig audio_object_storage_services_activation_config = 2;</code>
     * @param \Ondewo\Vtsi\AudioObjectStorageServicesActivationConfig $var
     * @return $this
     */
    public function setAudioObjectStorageServicesActivationConfig($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Vtsi\AudioObjectStorageServicesActivationConfig::class);
        $this->audio_object_storage_services_activation_config = $var;

        return $this;
    }

}

