<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/vtsi/calls.proto

namespace Ondewo\Vtsi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Configuration of the Minio Audio Object Store
 *
 * Generated from protobuf message <code>ondewo.vtsi.AudioObjectStorageServicesActivationConfig</code>
 */
class AudioObjectStorageServicesActivationConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Should audio object store save audio sent to the Speech-2-Text platform
     *
     * Generated from protobuf field <code>bool activate_s2t = 1;</code>
     */
    protected $activate_s2t = false;
    /**
     * Should audio object store save audio generated from the Text-2-Speech platform
     *
     * Generated from protobuf field <code>bool activate_t2s = 2;</code>
     */
    protected $activate_t2s = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $activate_s2t
     *           Should audio object store save audio sent to the Speech-2-Text platform
     *     @type bool $activate_t2s
     *           Should audio object store save audio generated from the Text-2-Speech platform
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Vtsi\Calls::initOnce();
        parent::__construct($data);
    }

    /**
     * Should audio object store save audio sent to the Speech-2-Text platform
     *
     * Generated from protobuf field <code>bool activate_s2t = 1;</code>
     * @return bool
     */
    public function getActivateS2T()
    {
        return $this->activate_s2t;
    }

    /**
     * Should audio object store save audio sent to the Speech-2-Text platform
     *
     * Generated from protobuf field <code>bool activate_s2t = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setActivateS2T($var)
    {
        GPBUtil::checkBool($var);
        $this->activate_s2t = $var;

        return $this;
    }

    /**
     * Should audio object store save audio generated from the Text-2-Speech platform
     *
     * Generated from protobuf field <code>bool activate_t2s = 2;</code>
     * @return bool
     */
    public function getActivateT2S()
    {
        return $this->activate_t2s;
    }

    /**
     * Should audio object store save audio generated from the Text-2-Speech platform
     *
     * Generated from protobuf field <code>bool activate_t2s = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setActivateT2S($var)
    {
        GPBUtil::checkBool($var);
        $this->activate_t2s = $var;

        return $this;
    }

}

