<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/vtsi/calls.proto

namespace Ondewo\Vtsi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * The status of one caller, listener or scheduled caller, as streamed by the status streams.
 *
 * Generated from protobuf message <code>ondewo.vtsi.CallResourceStatus</code>
 */
class CallResourceStatus extends \Google\Protobuf\Internal\Message
{
    /**
     * The caller, listener or scheduled caller.
     *
     * Generated from protobuf field <code>string resource_name = 1;</code>
     */
    protected $resource_name = '';
    /**
     * CALLER, LISTENER or SCHEDULED_CALLER.
     *
     * Generated from protobuf field <code>.ondewo.vtsi.CallType call_type = 2;</code>
     */
    protected $call_type = 0;
    /**
     * Its current or last call. Empty when it has none.
     *
     * Generated from protobuf field <code>string call_name = 3;</code>
     */
    protected $call_name = '';
    /**
     * Whether its call is active.
     *
     * Generated from protobuf field <code>bool active = 4;</code>
     */
    protected $active = false;
    /**
     * SIP status of its current or last call.
     *
     * Generated from protobuf field <code>.ondewo.sip.SipStatus.StatusType sip_status_type = 5;</code>
     */
    protected $sip_status_type = 0;
    /**
     * Description of that SIP status.
     *
     * Generated from protobuf field <code>string sip_status_description = 6;</code>
     */
    protected $sip_status_description = '';
    /**
     * Start of its current or last call.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp start_time = 7;</code>
     */
    protected $start_time = null;
    /**
     * End of its last call. Unset while a call runs.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp end_time = 8;</code>
     */
    protected $end_time = null;
    /**
     * Callee or caller number of its current or last call.
     *
     * Generated from protobuf field <code>string phone_number = 9;</code>
     */
    protected $phone_number = '';
    /**
     * For SCHEDULED_CALLER: its lifecycle state.
     *
     * Generated from protobuf field <code>.ondewo.vtsi.ScheduledCallerStatus scheduled_caller_status = 10;</code>
     */
    protected $scheduled_caller_status = 0;
    /**
     * For SCHEDULED_CALLER: its scheduled time.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp scheduled_time = 11;</code>
     */
    protected $scheduled_time = null;
    /**
     * The campaign it belongs to, if any.
     *
     * Generated from protobuf field <code>string campaign_name = 12;</code>
     */
    protected $campaign_name = '';
    /**
     * For SCHEDULED_CALLER: why it failed.
     *
     * Generated from protobuf field <code>string error_message = 13;</code>
     */
    protected $error_message = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $resource_name
     *           The caller, listener or scheduled caller.
     *     @type int $call_type
     *           CALLER, LISTENER or SCHEDULED_CALLER.
     *     @type string $call_name
     *           Its current or last call. Empty when it has none.
     *     @type bool $active
     *           Whether its call is active.
     *     @type int $sip_status_type
     *           SIP status of its current or last call.
     *     @type string $sip_status_description
     *           Description of that SIP status.
     *     @type \Google\Protobuf\Timestamp $start_time
     *           Start of its current or last call.
     *     @type \Google\Protobuf\Timestamp $end_time
     *           End of its last call. Unset while a call runs.
     *     @type string $phone_number
     *           Callee or caller number of its current or last call.
     *     @type int $scheduled_caller_status
     *           For SCHEDULED_CALLER: its lifecycle state.
     *     @type \Google\Protobuf\Timestamp $scheduled_time
     *           For SCHEDULED_CALLER: its scheduled time.
     *     @type string $campaign_name
     *           The campaign it belongs to, if any.
     *     @type string $error_message
     *           For SCHEDULED_CALLER: why it failed.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Vtsi\Calls::initOnce();
        parent::__construct($data);
    }

    /**
     * The caller, listener or scheduled caller.
     *
     * Generated from protobuf field <code>string resource_name = 1;</code>
     * @return string
     */
    public function getResourceName()
    {
        return $this->resource_name;
    }

    /**
     * The caller, listener or scheduled caller.
     *
     * Generated from protobuf field <code>string resource_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setResourceName($var)
    {
        GPBUtil::checkString($var, True);
        $this->resource_name = $var;

        return $this;
    }

    /**
     * CALLER, LISTENER or SCHEDULED_CALLER.
     *
     * Generated from protobuf field <code>.ondewo.vtsi.CallType call_type = 2;</code>
     * @return int
     */
    public function getCallType()
    {
        return $this->call_type;
    }

    /**
     * CALLER, LISTENER or SCHEDULED_CALLER.
     *
     * Generated from protobuf field <code>.ondewo.vtsi.CallType call_type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setCallType($var)
    {
        GPBUtil::checkEnum($var, \Ondewo\Vtsi\CallType::class);
        $this->call_type = $var;

        return $this;
    }

    /**
     * Its current or last call. Empty when it has none.
     *
     * Generated from protobuf field <code>string call_name = 3;</code>
     * @return string
     */
    public function getCallName()
    {
        return $this->call_name;
    }

    /**
     * Its current or last call. Empty when it has none.
     *
     * Generated from protobuf field <code>string call_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCallName($var)
    {
        GPBUtil::checkString($var, True);
        $this->call_name = $var;

        return $this;
    }

    /**
     * Whether its call is active.
     *
     * Generated from protobuf field <code>bool active = 4;</code>
     * @return bool
     */
    public function getActive()
    {
        return $this->active;
    }

    /**
     * Whether its call is active.
     *
     * Generated from protobuf field <code>bool active = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setActive($var)
    {
        GPBUtil::checkBool($var);
        $this->active = $var;

        return $this;
    }

    /**
     * SIP status of its current or last call.
     *
     * Generated from protobuf field <code>.ondewo.sip.SipStatus.StatusType sip_status_type = 5;</code>
     * @return int
     */
    public function getSipStatusType()
    {
        return $this->sip_status_type;
    }

    /**
     * SIP status of its current or last call.
     *
     * Generated from protobuf field <code>.ondewo.sip.SipStatus.StatusType sip_status_type = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setSipStatusType($var)
    {
        GPBUtil::checkEnum($var, \Ondewo\Sip\SipStatus\StatusType::class);
        $this->sip_status_type = $var;

        return $this;
    }

    /**
     * Description of that SIP status.
     *
     * Generated from protobuf field <code>string sip_status_description = 6;</code>
     * @return string
     */
    public function getSipStatusDescription()
    {
        return $this->sip_status_description;
    }

    /**
     * Description of that SIP status.
     *
     * Generated from protobuf field <code>string sip_status_description = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setSipStatusDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->sip_status_description = $var;

        return $this;
    }

    /**
     * Start of its current or last call.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp start_time = 7;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getStartTime()
    {
        return $this->start_time;
    }

    public function hasStartTime()
    {
        return isset($this->start_time);
    }

    public function clearStartTime()
    {
        unset($this->start_time);
    }

    /**
     * Start of its current or last call.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp start_time = 7;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setStartTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->start_time = $var;

        return $this;
    }

    /**
     * End of its last call. Unset while a call runs.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp end_time = 8;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getEndTime()
    {
        return $this->end_time;
    }

    public function hasEndTime()
    {
        return isset($this->end_time);
    }

    public function clearEndTime()
    {
        unset($this->end_time);
    }

    /**
     * End of its last call. Unset while a call runs.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp end_time = 8;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setEndTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->end_time = $var;

        return $this;
    }

    /**
     * Callee or caller number of its current or last call.
     *
     * Generated from protobuf field <code>string phone_number = 9;</code>
     * @return string
     */
    public function getPhoneNumber()
    {
        return $this->phone_number;
    }

    /**
     * Callee or caller number of its current or last call.
     *
     * Generated from protobuf field <code>string phone_number = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setPhoneNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->phone_number = $var;

        return $this;
    }

    /**
     * For SCHEDULED_CALLER: its lifecycle state.
     *
     * Generated from protobuf field <code>.ondewo.vtsi.ScheduledCallerStatus scheduled_caller_status = 10;</code>
     * @return int
     */
    public function getScheduledCallerStatus()
    {
        return $this->scheduled_caller_status;
    }

    /**
     * For SCHEDULED_CALLER: its lifecycle state.
     *
     * Generated from protobuf field <code>.ondewo.vtsi.ScheduledCallerStatus scheduled_caller_status = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setScheduledCallerStatus($var)
    {
        GPBUtil::checkEnum($var, \Ondewo\Vtsi\ScheduledCallerStatus::class);
        $this->scheduled_caller_status = $var;

        return $this;
    }

    /**
     * For SCHEDULED_CALLER: its scheduled time.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp scheduled_time = 11;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getScheduledTime()
    {
        return $this->scheduled_time;
    }

    public function hasScheduledTime()
    {
        return isset($this->scheduled_time);
    }

    public function clearScheduledTime()
    {
        unset($this->scheduled_time);
    }

    /**
     * For SCHEDULED_CALLER: its scheduled time.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp scheduled_time = 11;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setScheduledTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->scheduled_time = $var;

        return $this;
    }

    /**
     * The campaign it belongs to, if any.
     *
     * Generated from protobuf field <code>string campaign_name = 12;</code>
     * @return string
     */
    public function getCampaignName()
    {
        return $this->campaign_name;
    }

    /**
     * The campaign it belongs to, if any.
     *
     * Generated from protobuf field <code>string campaign_name = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setCampaignName($var)
    {
        GPBUtil::checkString($var, True);
        $this->campaign_name = $var;

        return $this;
    }

    /**
     * For SCHEDULED_CALLER: why it failed.
     *
     * Generated from protobuf field <code>string error_message = 13;</code>
     * @return string
     */
    public function getErrorMessage()
    {
        return $this->error_message;
    }

    /**
     * For SCHEDULED_CALLER: why it failed.
     *
     * Generated from protobuf field <code>string error_message = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setErrorMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->error_message = $var;

        return $this;
    }

}

