<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/vtsi/softphones.proto

namespace Ondewo\Vtsi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * The response message for
 * <a href="index.html#ondewo.vtsi.Softphones.CreateSoftphoneAccount">Softphones.CreateSoftphoneAccount</a>.
 *
 * Generated from protobuf message <code>ondewo.vtsi.CreateSoftphoneAccountResponse</code>
 */
class CreateSoftphoneAccountResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The created account.
     *
     * Generated from protobuf field <code>.ondewo.vtsi.SoftphoneAccount softphone_account = 1;</code>
     */
    protected $softphone_account = null;
    /**
     * ONE-TIME secrets: the SIP password and, for
     * <code>SOFTPHONE_TRANSPORT_SECURITY_CLIENT_CERTIFICATE</code>, the PKCS#12 bundle and its password.
     *
     * Generated from protobuf field <code>.ondewo.vtsi.SoftphoneCredentials credentials = 2;</code>
     */
    protected $credentials = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Ondewo\Vtsi\SoftphoneAccount $softphone_account
     *           The created account.
     *     @type \Ondewo\Vtsi\SoftphoneCredentials $credentials
     *           ONE-TIME secrets: the SIP password and, for
     *           <code>SOFTPHONE_TRANSPORT_SECURITY_CLIENT_CERTIFICATE</code>, the PKCS#12 bundle and its password.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Vtsi\Softphones::initOnce();
        parent::__construct($data);
    }

    /**
     * The created account.
     *
     * Generated from protobuf field <code>.ondewo.vtsi.SoftphoneAccount softphone_account = 1;</code>
     * @return \Ondewo\Vtsi\SoftphoneAccount|null
     */
    public function getSoftphoneAccount()
    {
        return $this->softphone_account;
    }

    public function hasSoftphoneAccount()
    {
        return isset($this->softphone_account);
    }

    public function clearSoftphoneAccount()
    {
        unset($this->softphone_account);
    }

    /**
     * The created account.
     *
     * Generated from protobuf field <code>.ondewo.vtsi.SoftphoneAccount softphone_account = 1;</code>
     * @param \Ondewo\Vtsi\SoftphoneAccount $var
     * @return $this
     */
    public function setSoftphoneAccount($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Vtsi\SoftphoneAccount::class);
        $this->softphone_account = $var;

        return $this;
    }

    /**
     * ONE-TIME secrets: the SIP password and, for
     * <code>SOFTPHONE_TRANSPORT_SECURITY_CLIENT_CERTIFICATE</code>, the PKCS#12 bundle and its password.
     *
     * Generated from protobuf field <code>.ondewo.vtsi.SoftphoneCredentials credentials = 2;</code>
     * @return \Ondewo\Vtsi\SoftphoneCredentials|null
     */
    public function getCredentials()
    {
        return $this->credentials;
    }

    public function hasCredentials()
    {
        return isset($this->credentials);
    }

    public function clearCredentials()
    {
        unset($this->credentials);
    }

    /**
     * ONE-TIME secrets: the SIP password and, for
     * <code>SOFTPHONE_TRANSPORT_SECURITY_CLIENT_CERTIFICATE</code>, the PKCS#12 bundle and its password.
     *
     * Generated from protobuf field <code>.ondewo.vtsi.SoftphoneCredentials credentials = 2;</code>
     * @param \Ondewo\Vtsi\SoftphoneCredentials $var
     * @return $this
     */
    public function setCredentials($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Vtsi\SoftphoneCredentials::class);
        $this->credentials = $var;

        return $this;
    }

}

