<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/vtsi/logs.proto

namespace Ondewo\Vtsi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * The request message for
 * <a href="index.html#ondewo.vtsi.Logs.GetCallLogStream">Logs.GetCallLogStream</a>.
 *
 * Generated from protobuf message <code>ondewo.vtsi.GetCallLogStreamRequest</code>
 */
class GetCallLogStreamRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * VTSI project name which to perform the call of the form <pre><code>projects/&lt;project_uuid&gt;/project</code></pre>
     *
     * Generated from protobuf field <code>string vtsi_project_name = 1;</code>
     */
    protected $vtsi_project_name = '';
    /**
     * The name of the log stream to retrieve of the form
     * <pre><code>projects/&lt;project_uuid&gt;/logStreams/&lt;log_stream_uuid&gt;</code></pre>
     *
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $vtsi_project_name
     *           VTSI project name which to perform the call of the form <pre><code>projects/&lt;project_uuid&gt;/project</code></pre>
     *     @type string $name
     *           The name of the log stream to retrieve of the form
     *           <pre><code>projects/&lt;project_uuid&gt;/logStreams/&lt;log_stream_uuid&gt;</code></pre>
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Vtsi\Logs::initOnce();
        parent::__construct($data);
    }

    /**
     * VTSI project name which to perform the call of the form <pre><code>projects/&lt;project_uuid&gt;/project</code></pre>
     *
     * Generated from protobuf field <code>string vtsi_project_name = 1;</code>
     * @return string
     */
    public function getVtsiProjectName()
    {
        return $this->vtsi_project_name;
    }

    /**
     * VTSI project name which to perform the call of the form <pre><code>projects/&lt;project_uuid&gt;/project</code></pre>
     *
     * Generated from protobuf field <code>string vtsi_project_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setVtsiProjectName($var)
    {
        GPBUtil::checkString($var, True);
        $this->vtsi_project_name = $var;

        return $this;
    }

    /**
     * The name of the log stream to retrieve of the form
     * <pre><code>projects/&lt;project_uuid&gt;/logStreams/&lt;log_stream_uuid&gt;</code></pre>
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * The name of the log stream to retrieve of the form
     * <pre><code>projects/&lt;project_uuid&gt;/logStreams/&lt;log_stream_uuid&gt;</code></pre>
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

}

