<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/vtsi/calls.proto

namespace Ondewo\Vtsi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Represents the response for listing callers.
 *
 * Generated from protobuf message <code>ondewo.vtsi.ListCallersResponse</code>
 */
class ListCallersResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The list of callers.
     *
     * Generated from protobuf field <code>repeated .ondewo.vtsi.Caller callers = 1;</code>
     */
    private $callers;
    /**
     * Token to retrieve the next page of results.
     * This field is a string that holds a token for fetching the next page of results.
     * If there are no more results in the list, this field will be empty.
     *
     * Generated from protobuf field <code>string next_page_token = 2;</code>
     */
    protected $next_page_token = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Ondewo\Vtsi\Caller[] $callers
     *           The list of callers.
     *     @type string $next_page_token
     *           Token to retrieve the next page of results.
     *           This field is a string that holds a token for fetching the next page of results.
     *           If there are no more results in the list, this field will be empty.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Vtsi\Calls::initOnce();
        parent::__construct($data);
    }

    /**
     * The list of callers.
     *
     * Generated from protobuf field <code>repeated .ondewo.vtsi.Caller callers = 1;</code>
     * @return RepeatedField<\Ondewo\Vtsi\Caller>
     */
    public function getCallers()
    {
        return $this->callers;
    }

    /**
     * The list of callers.
     *
     * Generated from protobuf field <code>repeated .ondewo.vtsi.Caller callers = 1;</code>
     * @param \Ondewo\Vtsi\Caller[] $var
     * @return $this
     */
    public function setCallers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Ondewo\Vtsi\Caller::class);
        $this->callers = $arr;

        return $this;
    }

    /**
     * Token to retrieve the next page of results.
     * This field is a string that holds a token for fetching the next page of results.
     * If there are no more results in the list, this field will be empty.
     *
     * Generated from protobuf field <code>string next_page_token = 2;</code>
     * @return string
     */
    public function getNextPageToken()
    {
        return $this->next_page_token;
    }

    /**
     * Token to retrieve the next page of results.
     * This field is a string that holds a token for fetching the next page of results.
     * If there are no more results in the list, this field will be empty.
     *
     * Generated from protobuf field <code>string next_page_token = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNextPageToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->next_page_token = $var;

        return $this;
    }

}

