<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/vtsi/campaigns.proto

namespace Ondewo\Vtsi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * The request message for
 * <a href="index.html#ondewo.vtsi.Campaigns.ListCampaignCalls">Campaigns.ListCampaignCalls</a>.
 *
 * Generated from protobuf message <code>ondewo.vtsi.ListCampaignCallsRequest</code>
 */
class ListCampaignCallsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Only calls in one of these states. Empty means every state.
     *
     * Generated from protobuf field <code>repeated .ondewo.vtsi.CampaignCallState states = 2;</code>
     */
    private $states;
    /**
     * Only calls to this callee (exact match on <code>phone_number</code>). Empty means every callee.
     *
     * Generated from protobuf field <code>string phone_number = 3;</code>
     */
    protected $phone_number = '';
    /**
     * Optional. Maximum calls per page. <code>0</code> means 50; values above 1000 are clamped to
     * 1000; negative values are rejected with <code>INVALID_ARGUMENT</code>.
     *
     * Generated from protobuf field <code>int32 page_size = 4;</code>
     */
    protected $page_size = 0;
    /**
     * Optional. The <code>next_page_token</code> of a previous response; valid only with the same
     * campaign and filter.
     *
     * Generated from protobuf field <code>optional string page_token = 5;</code>
     */
    protected $page_token = null;
    /**
     * Populate <code>CampaignCall.attempt_history</code>.
     *
     * Generated from protobuf field <code>bool include_attempts = 6;</code>
     */
    protected $include_attempts = false;
    protected $campaign;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $campaign_name
     *           Resource name of the campaign.
     *     @type \Ondewo\Vtsi\CampaignDisplayName $campaign_display_name
     *           The campaign with this display name.
     *     @type int[] $states
     *           Only calls in one of these states. Empty means every state.
     *     @type string $phone_number
     *           Only calls to this callee (exact match on <code>phone_number</code>). Empty means every callee.
     *     @type int $page_size
     *           Optional. Maximum calls per page. <code>0</code> means 50; values above 1000 are clamped to
     *           1000; negative values are rejected with <code>INVALID_ARGUMENT</code>.
     *     @type string $page_token
     *           Optional. The <code>next_page_token</code> of a previous response; valid only with the same
     *           campaign and filter.
     *     @type bool $include_attempts
     *           Populate <code>CampaignCall.attempt_history</code>.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Vtsi\Campaigns::initOnce();
        parent::__construct($data);
    }

    /**
     * Resource name of the campaign.
     *
     * Generated from protobuf field <code>string campaign_name = 1;</code>
     * @return string
     */
    public function getCampaignName()
    {
        return $this->readOneof(1);
    }

    public function hasCampaignName()
    {
        return $this->hasOneof(1);
    }

    /**
     * Resource name of the campaign.
     *
     * Generated from protobuf field <code>string campaign_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCampaignName($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * The campaign with this display name.
     *
     * Generated from protobuf field <code>.ondewo.vtsi.CampaignDisplayName campaign_display_name = 7;</code>
     * @return \Ondewo\Vtsi\CampaignDisplayName|null
     */
    public function getCampaignDisplayName()
    {
        return $this->readOneof(7);
    }

    public function hasCampaignDisplayName()
    {
        return $this->hasOneof(7);
    }

    /**
     * The campaign with this display name.
     *
     * Generated from protobuf field <code>.ondewo.vtsi.CampaignDisplayName campaign_display_name = 7;</code>
     * @param \Ondewo\Vtsi\CampaignDisplayName $var
     * @return $this
     */
    public function setCampaignDisplayName($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Vtsi\CampaignDisplayName::class);
        $this->writeOneof(7, $var);

        return $this;
    }

    /**
     * Only calls in one of these states. Empty means every state.
     *
     * Generated from protobuf field <code>repeated .ondewo.vtsi.CampaignCallState states = 2;</code>
     * @return RepeatedField<int>
     */
    public function getStates()
    {
        return $this->states;
    }

    /**
     * Only calls in one of these states. Empty means every state.
     *
     * Generated from protobuf field <code>repeated .ondewo.vtsi.CampaignCallState states = 2;</code>
     * @param int[] $var
     * @return $this
     */
    public function setStates($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Ondewo\Vtsi\CampaignCallState::class);
        $this->states = $arr;

        return $this;
    }

    /**
     * Only calls to this callee (exact match on <code>phone_number</code>). Empty means every callee.
     *
     * Generated from protobuf field <code>string phone_number = 3;</code>
     * @return string
     */
    public function getPhoneNumber()
    {
        return $this->phone_number;
    }

    /**
     * Only calls to this callee (exact match on <code>phone_number</code>). Empty means every callee.
     *
     * Generated from protobuf field <code>string phone_number = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPhoneNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->phone_number = $var;

        return $this;
    }

    /**
     * Optional. Maximum calls per page. <code>0</code> means 50; values above 1000 are clamped to
     * 1000; negative values are rejected with <code>INVALID_ARGUMENT</code>.
     *
     * Generated from protobuf field <code>int32 page_size = 4;</code>
     * @return int
     */
    public function getPageSize()
    {
        return $this->page_size;
    }

    /**
     * Optional. Maximum calls per page. <code>0</code> means 50; values above 1000 are clamped to
     * 1000; negative values are rejected with <code>INVALID_ARGUMENT</code>.
     *
     * Generated from protobuf field <code>int32 page_size = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setPageSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->page_size = $var;

        return $this;
    }

    /**
     * Optional. The <code>next_page_token</code> of a previous response; valid only with the same
     * campaign and filter.
     *
     * Generated from protobuf field <code>optional string page_token = 5;</code>
     * @return string
     */
    public function getPageToken()
    {
        return isset($this->page_token) ? $this->page_token : '';
    }

    public function hasPageToken()
    {
        return isset($this->page_token);
    }

    public function clearPageToken()
    {
        unset($this->page_token);
    }

    /**
     * Optional. The <code>next_page_token</code> of a previous response; valid only with the same
     * campaign and filter.
     *
     * Generated from protobuf field <code>optional string page_token = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setPageToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->page_token = $var;

        return $this;
    }

    /**
     * Populate <code>CampaignCall.attempt_history</code>.
     *
     * Generated from protobuf field <code>bool include_attempts = 6;</code>
     * @return bool
     */
    public function getIncludeAttempts()
    {
        return $this->include_attempts;
    }

    /**
     * Populate <code>CampaignCall.attempt_history</code>.
     *
     * Generated from protobuf field <code>bool include_attempts = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setIncludeAttempts($var)
    {
        GPBUtil::checkBool($var);
        $this->include_attempts = $var;

        return $this;
    }

    /**
     * @return string
     */
    public function getCampaign()
    {
        return $this->whichOneof("campaign");
    }

}

