<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/vtsi/calls.proto

namespace Ondewo\Vtsi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Listener represents a listener instance that waits for incoming calls
 *
 * Generated from protobuf message <code>ondewo.vtsi.Listener</code>
 */
class Listener extends \Google\Protobuf\Internal\Message
{
    /**
     * VTSI project name with which to perform the call of the form
     * <pre><code>projects/&lt;project_uuid&gt;/listeners/&lt;listener_uuid&gt;</code></pre>
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * The call name that was assigned to the call
     * <pre><code>projects/&lt;project_uuid&gt;/listeners/&lt;listener_uuid&gt;/calls/&lt;call_uuid&gt;</code></pre>
     *
     * Generated from protobuf field <code>string call_name = 2;</code>
     */
    protected $call_name = '';
    /**
     * SIP service configuration
     *
     * Generated from protobuf field <code>.ondewo.vtsi.SipBaseConfig sip_base_config = 3;</code>
     */
    protected $sip_base_config = null;
    /**
     * Service Configs of Speech-2-Text, NLU, Text-2-Speech and CSI
     *
     * Generated from protobuf field <code>.ondewo.vtsi.CommonServicesConfig common_services_config = 4;</code>
     */
    protected $common_services_config = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           VTSI project name with which to perform the call of the form
     *           <pre><code>projects/&lt;project_uuid&gt;/listeners/&lt;listener_uuid&gt;</code></pre>
     *     @type string $call_name
     *           The call name that was assigned to the call
     *           <pre><code>projects/&lt;project_uuid&gt;/listeners/&lt;listener_uuid&gt;/calls/&lt;call_uuid&gt;</code></pre>
     *     @type \Ondewo\Vtsi\SipBaseConfig $sip_base_config
     *           SIP service configuration
     *     @type \Ondewo\Vtsi\CommonServicesConfig $common_services_config
     *           Service Configs of Speech-2-Text, NLU, Text-2-Speech and CSI
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Vtsi\Calls::initOnce();
        parent::__construct($data);
    }

    /**
     * VTSI project name with which to perform the call of the form
     * <pre><code>projects/&lt;project_uuid&gt;/listeners/&lt;listener_uuid&gt;</code></pre>
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * VTSI project name with which to perform the call of the form
     * <pre><code>projects/&lt;project_uuid&gt;/listeners/&lt;listener_uuid&gt;</code></pre>
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * The call name that was assigned to the call
     * <pre><code>projects/&lt;project_uuid&gt;/listeners/&lt;listener_uuid&gt;/calls/&lt;call_uuid&gt;</code></pre>
     *
     * Generated from protobuf field <code>string call_name = 2;</code>
     * @return string
     */
    public function getCallName()
    {
        return $this->call_name;
    }

    /**
     * The call name that was assigned to the call
     * <pre><code>projects/&lt;project_uuid&gt;/listeners/&lt;listener_uuid&gt;/calls/&lt;call_uuid&gt;</code></pre>
     *
     * Generated from protobuf field <code>string call_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCallName($var)
    {
        GPBUtil::checkString($var, True);
        $this->call_name = $var;

        return $this;
    }

    /**
     * SIP service configuration
     *
     * Generated from protobuf field <code>.ondewo.vtsi.SipBaseConfig sip_base_config = 3;</code>
     * @return \Ondewo\Vtsi\SipBaseConfig|null
     */
    public function getSipBaseConfig()
    {
        return $this->sip_base_config;
    }

    public function hasSipBaseConfig()
    {
        return isset($this->sip_base_config);
    }

    public function clearSipBaseConfig()
    {
        unset($this->sip_base_config);
    }

    /**
     * SIP service configuration
     *
     * Generated from protobuf field <code>.ondewo.vtsi.SipBaseConfig sip_base_config = 3;</code>
     * @param \Ondewo\Vtsi\SipBaseConfig $var
     * @return $this
     */
    public function setSipBaseConfig($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Vtsi\SipBaseConfig::class);
        $this->sip_base_config = $var;

        return $this;
    }

    /**
     * Service Configs of Speech-2-Text, NLU, Text-2-Speech and CSI
     *
     * Generated from protobuf field <code>.ondewo.vtsi.CommonServicesConfig common_services_config = 4;</code>
     * @return \Ondewo\Vtsi\CommonServicesConfig|null
     */
    public function getCommonServicesConfig()
    {
        return $this->common_services_config;
    }

    public function hasCommonServicesConfig()
    {
        return isset($this->common_services_config);
    }

    public function clearCommonServicesConfig()
    {
        unset($this->common_services_config);
    }

    /**
     * Service Configs of Speech-2-Text, NLU, Text-2-Speech and CSI
     *
     * Generated from protobuf field <code>.ondewo.vtsi.CommonServicesConfig common_services_config = 4;</code>
     * @param \Ondewo\Vtsi\CommonServicesConfig $var
     * @return $this
     */
    public function setCommonServicesConfig($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Vtsi\CommonServicesConfig::class);
        $this->common_services_config = $var;

        return $this;
    }

}

