<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/vtsi/calls.proto

namespace Ondewo\Vtsi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Configuration of the response timing, i.e. when and how the bot responds
 *
 * Generated from protobuf message <code>ondewo.vtsi.ResponseTimingConfig</code>
 */
class ResponseTimingConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Optional: Seconds of caller silence after a bot response until a follow-up event
     * is triggered (default: 20.0, valid range: 1.0 - 30.0)
     *
     * Generated from protobuf field <code>optional float turn_timeout_seconds = 1;</code>
     */
    protected $turn_timeout_seconds = null;
    /**
     * Optional: Seconds of caller silence until the call is ended.
     * Unset = off (-1 is also accepted as explicit off)
     *
     * Generated from protobuf field <code>optional float silence_end_call_timeout_seconds = 2;</code>
     */
    protected $silence_end_call_timeout_seconds = null;
    /**
     * Configuration of the soft timeout filler messages
     *
     * Generated from protobuf field <code>.ondewo.vtsi.SoftTimeoutConfig soft_timeout_config = 3;</code>
     */
    protected $soft_timeout_config = null;
    /**
     * Optional: Enable preemptive response generation on an eagerly detected end of turn (default: false)
     *
     * Generated from protobuf field <code>optional bool preemptive_generation_enabled = 4;</code>
     */
    protected $preemptive_generation_enabled = null;
    /**
     * Optional: Enable chunked text-to-speech streaming for a lower time to first audio (default: false)
     *
     * Generated from protobuf field <code>optional bool t2s_chunked_streaming_enabled = 5;</code>
     */
    protected $t2s_chunked_streaming_enabled = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $turn_timeout_seconds
     *           Optional: Seconds of caller silence after a bot response until a follow-up event
     *           is triggered (default: 20.0, valid range: 1.0 - 30.0)
     *     @type float $silence_end_call_timeout_seconds
     *           Optional: Seconds of caller silence until the call is ended.
     *           Unset = off (-1 is also accepted as explicit off)
     *     @type \Ondewo\Vtsi\SoftTimeoutConfig $soft_timeout_config
     *           Configuration of the soft timeout filler messages
     *     @type bool $preemptive_generation_enabled
     *           Optional: Enable preemptive response generation on an eagerly detected end of turn (default: false)
     *     @type bool $t2s_chunked_streaming_enabled
     *           Optional: Enable chunked text-to-speech streaming for a lower time to first audio (default: false)
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Vtsi\Calls::initOnce();
        parent::__construct($data);
    }

    /**
     * Optional: Seconds of caller silence after a bot response until a follow-up event
     * is triggered (default: 20.0, valid range: 1.0 - 30.0)
     *
     * Generated from protobuf field <code>optional float turn_timeout_seconds = 1;</code>
     * @return float
     */
    public function getTurnTimeoutSeconds()
    {
        return isset($this->turn_timeout_seconds) ? $this->turn_timeout_seconds : 0.0;
    }

    public function hasTurnTimeoutSeconds()
    {
        return isset($this->turn_timeout_seconds);
    }

    public function clearTurnTimeoutSeconds()
    {
        unset($this->turn_timeout_seconds);
    }

    /**
     * Optional: Seconds of caller silence after a bot response until a follow-up event
     * is triggered (default: 20.0, valid range: 1.0 - 30.0)
     *
     * Generated from protobuf field <code>optional float turn_timeout_seconds = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setTurnTimeoutSeconds($var)
    {
        GPBUtil::checkFloat($var);
        $this->turn_timeout_seconds = $var;

        return $this;
    }

    /**
     * Optional: Seconds of caller silence until the call is ended.
     * Unset = off (-1 is also accepted as explicit off)
     *
     * Generated from protobuf field <code>optional float silence_end_call_timeout_seconds = 2;</code>
     * @return float
     */
    public function getSilenceEndCallTimeoutSeconds()
    {
        return isset($this->silence_end_call_timeout_seconds) ? $this->silence_end_call_timeout_seconds : 0.0;
    }

    public function hasSilenceEndCallTimeoutSeconds()
    {
        return isset($this->silence_end_call_timeout_seconds);
    }

    public function clearSilenceEndCallTimeoutSeconds()
    {
        unset($this->silence_end_call_timeout_seconds);
    }

    /**
     * Optional: Seconds of caller silence until the call is ended.
     * Unset = off (-1 is also accepted as explicit off)
     *
     * Generated from protobuf field <code>optional float silence_end_call_timeout_seconds = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setSilenceEndCallTimeoutSeconds($var)
    {
        GPBUtil::checkFloat($var);
        $this->silence_end_call_timeout_seconds = $var;

        return $this;
    }

    /**
     * Configuration of the soft timeout filler messages
     *
     * Generated from protobuf field <code>.ondewo.vtsi.SoftTimeoutConfig soft_timeout_config = 3;</code>
     * @return \Ondewo\Vtsi\SoftTimeoutConfig|null
     */
    public function getSoftTimeoutConfig()
    {
        return $this->soft_timeout_config;
    }

    public function hasSoftTimeoutConfig()
    {
        return isset($this->soft_timeout_config);
    }

    public function clearSoftTimeoutConfig()
    {
        unset($this->soft_timeout_config);
    }

    /**
     * Configuration of the soft timeout filler messages
     *
     * Generated from protobuf field <code>.ondewo.vtsi.SoftTimeoutConfig soft_timeout_config = 3;</code>
     * @param \Ondewo\Vtsi\SoftTimeoutConfig $var
     * @return $this
     */
    public function setSoftTimeoutConfig($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Vtsi\SoftTimeoutConfig::class);
        $this->soft_timeout_config = $var;

        return $this;
    }

    /**
     * Optional: Enable preemptive response generation on an eagerly detected end of turn (default: false)
     *
     * Generated from protobuf field <code>optional bool preemptive_generation_enabled = 4;</code>
     * @return bool
     */
    public function getPreemptiveGenerationEnabled()
    {
        return isset($this->preemptive_generation_enabled) ? $this->preemptive_generation_enabled : false;
    }

    public function hasPreemptiveGenerationEnabled()
    {
        return isset($this->preemptive_generation_enabled);
    }

    public function clearPreemptiveGenerationEnabled()
    {
        unset($this->preemptive_generation_enabled);
    }

    /**
     * Optional: Enable preemptive response generation on an eagerly detected end of turn (default: false)
     *
     * Generated from protobuf field <code>optional bool preemptive_generation_enabled = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setPreemptiveGenerationEnabled($var)
    {
        GPBUtil::checkBool($var);
        $this->preemptive_generation_enabled = $var;

        return $this;
    }

    /**
     * Optional: Enable chunked text-to-speech streaming for a lower time to first audio (default: false)
     *
     * Generated from protobuf field <code>optional bool t2s_chunked_streaming_enabled = 5;</code>
     * @return bool
     */
    public function getT2SChunkedStreamingEnabled()
    {
        return isset($this->t2s_chunked_streaming_enabled) ? $this->t2s_chunked_streaming_enabled : false;
    }

    public function hasT2SChunkedStreamingEnabled()
    {
        return isset($this->t2s_chunked_streaming_enabled);
    }

    public function clearT2SChunkedStreamingEnabled()
    {
        unset($this->t2s_chunked_streaming_enabled);
    }

    /**
     * Optional: Enable chunked text-to-speech streaming for a lower time to first audio (default: false)
     *
     * Generated from protobuf field <code>optional bool t2s_chunked_streaming_enabled = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setT2SChunkedStreamingEnabled($var)
    {
        GPBUtil::checkBool($var);
        $this->t2s_chunked_streaming_enabled = $var;

        return $this;
    }

}

