<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/vtsi/logs.proto

namespace Ondewo\Vtsi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * The request message for
 * <a href="index.html#ondewo.vtsi.Logs.StreamCallLogs">Logs.StreamCallLogs</a>.
 *
 * Generated from protobuf message <code>ondewo.vtsi.StreamCallLogsRequest</code>
 */
class StreamCallLogsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * VTSI project name for which to stream the logs.
     * The format is: <pre><code>projects/&lt;project_uuid&gt;/project</code></pre>
     *
     * Generated from protobuf field <code>string vtsi_project_name = 1;</code>
     */
    protected $vtsi_project_name = '';
    /**
     * Optional. A filter to narrow the stream down to the entries of interest. The time-window
     * fields and paging cursors of the filter are meaningless for a live stream and are rejected
     * with <code>INVALID_ARGUMENT</code> rather than silently ignored.
     *
     * Generated from protobuf field <code>optional .ondewo.vtsi.CallLogFilter filter = 2;</code>
     */
    protected $filter = null;
    /**
     * Replay at most this many of the most recent stored entries before switching to live follow.
     * <code>0</code> (the default) starts the follow with no historical replay. Applied to the
     * FILTERED result, so <code>tail_lines = 100</code> with a severity floor returns up to 100
     * matching entries rather than the matches within the last 100 entries.
     *
     * Generated from protobuf field <code>optional int32 tail_lines = 3;</code>
     */
    protected $tail_lines = null;
    /**
     * Optional. Resume exactly where a previous stream or page stopped. This is an opaque,
     * server-encoded per-log-stream cursor and must be echoed back verbatim. Prefer it over
     * <code>after_seq</code>: a single scalar cannot express a cursor across several containers, and
     * using one when the filter matches more than one container SKIPS entries.
     *
     * Generated from protobuf field <code>optional string resume_token = 4;</code>
     */
    protected $resume_token = null;
    /**
     * Optional. Resume after this <code>seq</code>. Valid ONLY when the filter resolves to exactly
     * one log stream; otherwise the request is rejected with <code>INVALID_ARGUMENT</code>. Ignored
     * when <code>resume_token</code> is set.
     *
     * Generated from protobuf field <code>optional int64 after_seq = 5;</code>
     */
    protected $after_seq = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $vtsi_project_name
     *           VTSI project name for which to stream the logs.
     *           The format is: <pre><code>projects/&lt;project_uuid&gt;/project</code></pre>
     *     @type \Ondewo\Vtsi\CallLogFilter $filter
     *           Optional. A filter to narrow the stream down to the entries of interest. The time-window
     *           fields and paging cursors of the filter are meaningless for a live stream and are rejected
     *           with <code>INVALID_ARGUMENT</code> rather than silently ignored.
     *     @type int $tail_lines
     *           Replay at most this many of the most recent stored entries before switching to live follow.
     *           <code>0</code> (the default) starts the follow with no historical replay. Applied to the
     *           FILTERED result, so <code>tail_lines = 100</code> with a severity floor returns up to 100
     *           matching entries rather than the matches within the last 100 entries.
     *     @type string $resume_token
     *           Optional. Resume exactly where a previous stream or page stopped. This is an opaque,
     *           server-encoded per-log-stream cursor and must be echoed back verbatim. Prefer it over
     *           <code>after_seq</code>: a single scalar cannot express a cursor across several containers, and
     *           using one when the filter matches more than one container SKIPS entries.
     *     @type int|string $after_seq
     *           Optional. Resume after this <code>seq</code>. Valid ONLY when the filter resolves to exactly
     *           one log stream; otherwise the request is rejected with <code>INVALID_ARGUMENT</code>. Ignored
     *           when <code>resume_token</code> is set.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Vtsi\Logs::initOnce();
        parent::__construct($data);
    }

    /**
     * VTSI project name for which to stream the logs.
     * The format is: <pre><code>projects/&lt;project_uuid&gt;/project</code></pre>
     *
     * Generated from protobuf field <code>string vtsi_project_name = 1;</code>
     * @return string
     */
    public function getVtsiProjectName()
    {
        return $this->vtsi_project_name;
    }

    /**
     * VTSI project name for which to stream the logs.
     * The format is: <pre><code>projects/&lt;project_uuid&gt;/project</code></pre>
     *
     * Generated from protobuf field <code>string vtsi_project_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setVtsiProjectName($var)
    {
        GPBUtil::checkString($var, True);
        $this->vtsi_project_name = $var;

        return $this;
    }

    /**
     * Optional. A filter to narrow the stream down to the entries of interest. The time-window
     * fields and paging cursors of the filter are meaningless for a live stream and are rejected
     * with <code>INVALID_ARGUMENT</code> rather than silently ignored.
     *
     * Generated from protobuf field <code>optional .ondewo.vtsi.CallLogFilter filter = 2;</code>
     * @return \Ondewo\Vtsi\CallLogFilter|null
     */
    public function getFilter()
    {
        return $this->filter;
    }

    public function hasFilter()
    {
        return isset($this->filter);
    }

    public function clearFilter()
    {
        unset($this->filter);
    }

    /**
     * Optional. A filter to narrow the stream down to the entries of interest. The time-window
     * fields and paging cursors of the filter are meaningless for a live stream and are rejected
     * with <code>INVALID_ARGUMENT</code> rather than silently ignored.
     *
     * Generated from protobuf field <code>optional .ondewo.vtsi.CallLogFilter filter = 2;</code>
     * @param \Ondewo\Vtsi\CallLogFilter $var
     * @return $this
     */
    public function setFilter($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Vtsi\CallLogFilter::class);
        $this->filter = $var;

        return $this;
    }

    /**
     * Replay at most this many of the most recent stored entries before switching to live follow.
     * <code>0</code> (the default) starts the follow with no historical replay. Applied to the
     * FILTERED result, so <code>tail_lines = 100</code> with a severity floor returns up to 100
     * matching entries rather than the matches within the last 100 entries.
     *
     * Generated from protobuf field <code>optional int32 tail_lines = 3;</code>
     * @return int
     */
    public function getTailLines()
    {
        return isset($this->tail_lines) ? $this->tail_lines : 0;
    }

    public function hasTailLines()
    {
        return isset($this->tail_lines);
    }

    public function clearTailLines()
    {
        unset($this->tail_lines);
    }

    /**
     * Replay at most this many of the most recent stored entries before switching to live follow.
     * <code>0</code> (the default) starts the follow with no historical replay. Applied to the
     * FILTERED result, so <code>tail_lines = 100</code> with a severity floor returns up to 100
     * matching entries rather than the matches within the last 100 entries.
     *
     * Generated from protobuf field <code>optional int32 tail_lines = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setTailLines($var)
    {
        GPBUtil::checkInt32($var);
        $this->tail_lines = $var;

        return $this;
    }

    /**
     * Optional. Resume exactly where a previous stream or page stopped. This is an opaque,
     * server-encoded per-log-stream cursor and must be echoed back verbatim. Prefer it over
     * <code>after_seq</code>: a single scalar cannot express a cursor across several containers, and
     * using one when the filter matches more than one container SKIPS entries.
     *
     * Generated from protobuf field <code>optional string resume_token = 4;</code>
     * @return string
     */
    public function getResumeToken()
    {
        return isset($this->resume_token) ? $this->resume_token : '';
    }

    public function hasResumeToken()
    {
        return isset($this->resume_token);
    }

    public function clearResumeToken()
    {
        unset($this->resume_token);
    }

    /**
     * Optional. Resume exactly where a previous stream or page stopped. This is an opaque,
     * server-encoded per-log-stream cursor and must be echoed back verbatim. Prefer it over
     * <code>after_seq</code>: a single scalar cannot express a cursor across several containers, and
     * using one when the filter matches more than one container SKIPS entries.
     *
     * Generated from protobuf field <code>optional string resume_token = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setResumeToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->resume_token = $var;

        return $this;
    }

    /**
     * Optional. Resume after this <code>seq</code>. Valid ONLY when the filter resolves to exactly
     * one log stream; otherwise the request is rejected with <code>INVALID_ARGUMENT</code>. Ignored
     * when <code>resume_token</code> is set.
     *
     * Generated from protobuf field <code>optional int64 after_seq = 5;</code>
     * @return int|string
     */
    public function getAfterSeq()
    {
        return isset($this->after_seq) ? $this->after_seq : 0;
    }

    public function hasAfterSeq()
    {
        return isset($this->after_seq);
    }

    public function clearAfterSeq()
    {
        unset($this->after_seq);
    }

    /**
     * Optional. Resume after this <code>seq</code>. Valid ONLY when the filter resolves to exactly
     * one log stream; otherwise the request is rejected with <code>INVALID_ARGUMENT</code>. Ignored
     * when <code>resume_token</code> is set.
     *
     * Generated from protobuf field <code>optional int64 after_seq = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAfterSeq($var)
    {
        GPBUtil::checkInt64($var);
        $this->after_seq = $var;

        return $this;
    }

}

