<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/vtsi/calls.proto

namespace Ondewo\Vtsi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Configuration of the voice interaction behavior of a call:
 * turn detection, interruption (barge-in) handling and response timing
 *
 * Generated from protobuf message <code>ondewo.vtsi.VoiceInteractionConfig</code>
 */
class VoiceInteractionConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Configuration of the turn detection
     *
     * Generated from protobuf field <code>.ondewo.vtsi.TurnDetectionConfig turn_detection_config = 1;</code>
     */
    protected $turn_detection_config = null;
    /**
     * Configuration of the interruption (barge-in) handling
     *
     * Generated from protobuf field <code>.ondewo.vtsi.InterruptionHandlingConfig interruption_handling_config = 2;</code>
     */
    protected $interruption_handling_config = null;
    /**
     * Configuration of the response timing
     *
     * Generated from protobuf field <code>.ondewo.vtsi.ResponseTimingConfig response_timing_config = 3;</code>
     */
    protected $response_timing_config = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Ondewo\Vtsi\TurnDetectionConfig $turn_detection_config
     *           Configuration of the turn detection
     *     @type \Ondewo\Vtsi\InterruptionHandlingConfig $interruption_handling_config
     *           Configuration of the interruption (barge-in) handling
     *     @type \Ondewo\Vtsi\ResponseTimingConfig $response_timing_config
     *           Configuration of the response timing
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Vtsi\Calls::initOnce();
        parent::__construct($data);
    }

    /**
     * Configuration of the turn detection
     *
     * Generated from protobuf field <code>.ondewo.vtsi.TurnDetectionConfig turn_detection_config = 1;</code>
     * @return \Ondewo\Vtsi\TurnDetectionConfig|null
     */
    public function getTurnDetectionConfig()
    {
        return $this->turn_detection_config;
    }

    public function hasTurnDetectionConfig()
    {
        return isset($this->turn_detection_config);
    }

    public function clearTurnDetectionConfig()
    {
        unset($this->turn_detection_config);
    }

    /**
     * Configuration of the turn detection
     *
     * Generated from protobuf field <code>.ondewo.vtsi.TurnDetectionConfig turn_detection_config = 1;</code>
     * @param \Ondewo\Vtsi\TurnDetectionConfig $var
     * @return $this
     */
    public function setTurnDetectionConfig($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Vtsi\TurnDetectionConfig::class);
        $this->turn_detection_config = $var;

        return $this;
    }

    /**
     * Configuration of the interruption (barge-in) handling
     *
     * Generated from protobuf field <code>.ondewo.vtsi.InterruptionHandlingConfig interruption_handling_config = 2;</code>
     * @return \Ondewo\Vtsi\InterruptionHandlingConfig|null
     */
    public function getInterruptionHandlingConfig()
    {
        return $this->interruption_handling_config;
    }

    public function hasInterruptionHandlingConfig()
    {
        return isset($this->interruption_handling_config);
    }

    public function clearInterruptionHandlingConfig()
    {
        unset($this->interruption_handling_config);
    }

    /**
     * Configuration of the interruption (barge-in) handling
     *
     * Generated from protobuf field <code>.ondewo.vtsi.InterruptionHandlingConfig interruption_handling_config = 2;</code>
     * @param \Ondewo\Vtsi\InterruptionHandlingConfig $var
     * @return $this
     */
    public function setInterruptionHandlingConfig($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Vtsi\InterruptionHandlingConfig::class);
        $this->interruption_handling_config = $var;

        return $this;
    }

    /**
     * Configuration of the response timing
     *
     * Generated from protobuf field <code>.ondewo.vtsi.ResponseTimingConfig response_timing_config = 3;</code>
     * @return \Ondewo\Vtsi\ResponseTimingConfig|null
     */
    public function getResponseTimingConfig()
    {
        return $this->response_timing_config;
    }

    public function hasResponseTimingConfig()
    {
        return isset($this->response_timing_config);
    }

    public function clearResponseTimingConfig()
    {
        unset($this->response_timing_config);
    }

    /**
     * Configuration of the response timing
     *
     * Generated from protobuf field <code>.ondewo.vtsi.ResponseTimingConfig response_timing_config = 3;</code>
     * @param \Ondewo\Vtsi\ResponseTimingConfig $var
     * @return $this
     */
    public function setResponseTimingConfig($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Vtsi\ResponseTimingConfig::class);
        $this->response_timing_config = $var;

        return $this;
    }

}

