<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/vtsi/events.proto

namespace Ondewo\Vtsi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * One event. This is the body of a webhook request (proto3 JSON with the original field names)
 * and the unit of the <code>SubscribeVtsiEvents</code> stream.
 *
 * Generated from protobuf message <code>ondewo.vtsi.VtsiEventMessage</code>
 */
class VtsiEventMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Unique id of the event (uuid). A retried webhook request carries the same id, and a call
     * status change observed by several server replicas carries one id, so it identifies a
     * duplicate.
     *
     * Generated from protobuf field <code>string event_id = 1;</code>
     */
    protected $event_id = '';
    /**
     * The event.
     *
     * Generated from protobuf field <code>.ondewo.vtsi.VtsiEvent event = 2;</code>
     */
    protected $event = 0;
    /**
     * VTSI project of the event.
     * The format is: <pre><code>projects/&lt;project_uuid&gt;/project</code></pre>
     *
     * Generated from protobuf field <code>string vtsi_project_name = 3;</code>
     */
    protected $vtsi_project_name = '';
    /**
     * The resource the event is about (call, caller, listener, scheduled caller, campaign, campaign
     * call, project, softphone account).
     *
     * Generated from protobuf field <code>string resource_name = 4;</code>
     */
    protected $resource_name = '';
    /**
     * When the event happened.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp event_time = 5;</code>
     */
    protected $event_time = null;
    /**
     * SIP status after the change, for call and campaign call events.
     *
     * Generated from protobuf field <code>optional .ondewo.sip.SipStatus.StatusType sip_status_type = 6;</code>
     */
    protected $sip_status_type = null;
    /**
     * SIP status description, where the event has one.
     *
     * Generated from protobuf field <code>string sip_status_description = 7;</code>
     */
    protected $sip_status_description = '';
    /**
     * SIP status before the change, for <code>VTSI_EVENT_CALL_SIP_STATUS_CHANGED</code>.
     *
     * Generated from protobuf field <code>optional .ondewo.sip.SipStatus.StatusType previous_sip_status_type = 8;</code>
     */
    protected $previous_sip_status_type = null;
    /**
     * The call the event is about or produced, where there is one.
     *
     * Generated from protobuf field <code>string call_name = 9;</code>
     */
    protected $call_name = '';
    /**
     * The campaign the event belongs to, where known.
     *
     * Generated from protobuf field <code>string campaign_name = 10;</code>
     */
    protected $campaign_name = '';
    /**
     * Human-readable description, e.g. why something failed.
     *
     * Generated from protobuf field <code>string description = 11;</code>
     */
    protected $description = '';
    /**
     * Further event-specific values, e.g. <code>caller_name</code>, <code>listener_name</code>,
     * <code>phone_number</code>, <code>container_name</code>, <code>attempt_number</code>,
     * <code>previous_status</code>. Keys are documented per event in the VTSI documentation.
     *
     * Generated from protobuf field <code>map<string, string> attributes = 12;</code>
     */
    private $attributes;
    /**
     * Statistics of the campaign, on campaign events.
     *
     * Generated from protobuf field <code>.ondewo.vtsi.CampaignStatistics campaign_statistics = 13;</code>
     */
    protected $campaign_statistics = null;
    /**
     * Increases with every change of <code>resource_name</code> that produced an event, so a
     * receiver can order events of one resource that arrived out of order. Defined (&gt; 0) for
     * call events (the call&apos;s status change number), campaign call events and campaign state
     * events; <code>0</code> where the resource has no such counter, then order by
     * <code>event_time</code>.
     *
     * Generated from protobuf field <code>int64 resource_sequence = 14;</code>
     */
    protected $resource_sequence = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $event_id
     *           Unique id of the event (uuid). A retried webhook request carries the same id, and a call
     *           status change observed by several server replicas carries one id, so it identifies a
     *           duplicate.
     *     @type int $event
     *           The event.
     *     @type string $vtsi_project_name
     *           VTSI project of the event.
     *           The format is: <pre><code>projects/&lt;project_uuid&gt;/project</code></pre>
     *     @type string $resource_name
     *           The resource the event is about (call, caller, listener, scheduled caller, campaign, campaign
     *           call, project, softphone account).
     *     @type \Google\Protobuf\Timestamp $event_time
     *           When the event happened.
     *     @type int $sip_status_type
     *           SIP status after the change, for call and campaign call events.
     *     @type string $sip_status_description
     *           SIP status description, where the event has one.
     *     @type int $previous_sip_status_type
     *           SIP status before the change, for <code>VTSI_EVENT_CALL_SIP_STATUS_CHANGED</code>.
     *     @type string $call_name
     *           The call the event is about or produced, where there is one.
     *     @type string $campaign_name
     *           The campaign the event belongs to, where known.
     *     @type string $description
     *           Human-readable description, e.g. why something failed.
     *     @type array|\Google\Protobuf\Internal\MapField $attributes
     *           Further event-specific values, e.g. <code>caller_name</code>, <code>listener_name</code>,
     *           <code>phone_number</code>, <code>container_name</code>, <code>attempt_number</code>,
     *           <code>previous_status</code>. Keys are documented per event in the VTSI documentation.
     *     @type \Ondewo\Vtsi\CampaignStatistics $campaign_statistics
     *           Statistics of the campaign, on campaign events.
     *     @type int|string $resource_sequence
     *           Increases with every change of <code>resource_name</code> that produced an event, so a
     *           receiver can order events of one resource that arrived out of order. Defined (&gt; 0) for
     *           call events (the call&apos;s status change number), campaign call events and campaign state
     *           events; <code>0</code> where the resource has no such counter, then order by
     *           <code>event_time</code>.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Vtsi\Events::initOnce();
        parent::__construct($data);
    }

    /**
     * Unique id of the event (uuid). A retried webhook request carries the same id, and a call
     * status change observed by several server replicas carries one id, so it identifies a
     * duplicate.
     *
     * Generated from protobuf field <code>string event_id = 1;</code>
     * @return string
     */
    public function getEventId()
    {
        return $this->event_id;
    }

    /**
     * Unique id of the event (uuid). A retried webhook request carries the same id, and a call
     * status change observed by several server replicas carries one id, so it identifies a
     * duplicate.
     *
     * Generated from protobuf field <code>string event_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setEventId($var)
    {
        GPBUtil::checkString($var, True);
        $this->event_id = $var;

        return $this;
    }

    /**
     * The event.
     *
     * Generated from protobuf field <code>.ondewo.vtsi.VtsiEvent event = 2;</code>
     * @return int
     */
    public function getEvent()
    {
        return $this->event;
    }

    /**
     * The event.
     *
     * Generated from protobuf field <code>.ondewo.vtsi.VtsiEvent event = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setEvent($var)
    {
        GPBUtil::checkEnum($var, \Ondewo\Vtsi\VtsiEvent::class);
        $this->event = $var;

        return $this;
    }

    /**
     * VTSI project of the event.
     * The format is: <pre><code>projects/&lt;project_uuid&gt;/project</code></pre>
     *
     * Generated from protobuf field <code>string vtsi_project_name = 3;</code>
     * @return string
     */
    public function getVtsiProjectName()
    {
        return $this->vtsi_project_name;
    }

    /**
     * VTSI project of the event.
     * The format is: <pre><code>projects/&lt;project_uuid&gt;/project</code></pre>
     *
     * Generated from protobuf field <code>string vtsi_project_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setVtsiProjectName($var)
    {
        GPBUtil::checkString($var, True);
        $this->vtsi_project_name = $var;

        return $this;
    }

    /**
     * The resource the event is about (call, caller, listener, scheduled caller, campaign, campaign
     * call, project, softphone account).
     *
     * Generated from protobuf field <code>string resource_name = 4;</code>
     * @return string
     */
    public function getResourceName()
    {
        return $this->resource_name;
    }

    /**
     * The resource the event is about (call, caller, listener, scheduled caller, campaign, campaign
     * call, project, softphone account).
     *
     * Generated from protobuf field <code>string resource_name = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setResourceName($var)
    {
        GPBUtil::checkString($var, True);
        $this->resource_name = $var;

        return $this;
    }

    /**
     * When the event happened.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp event_time = 5;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getEventTime()
    {
        return $this->event_time;
    }

    public function hasEventTime()
    {
        return isset($this->event_time);
    }

    public function clearEventTime()
    {
        unset($this->event_time);
    }

    /**
     * When the event happened.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp event_time = 5;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setEventTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->event_time = $var;

        return $this;
    }

    /**
     * SIP status after the change, for call and campaign call events.
     *
     * Generated from protobuf field <code>optional .ondewo.sip.SipStatus.StatusType sip_status_type = 6;</code>
     * @return int
     */
    public function getSipStatusType()
    {
        return isset($this->sip_status_type) ? $this->sip_status_type : 0;
    }

    public function hasSipStatusType()
    {
        return isset($this->sip_status_type);
    }

    public function clearSipStatusType()
    {
        unset($this->sip_status_type);
    }

    /**
     * SIP status after the change, for call and campaign call events.
     *
     * Generated from protobuf field <code>optional .ondewo.sip.SipStatus.StatusType sip_status_type = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setSipStatusType($var)
    {
        GPBUtil::checkEnum($var, \Ondewo\Sip\SipStatus\StatusType::class);
        $this->sip_status_type = $var;

        return $this;
    }

    /**
     * SIP status description, where the event has one.
     *
     * Generated from protobuf field <code>string sip_status_description = 7;</code>
     * @return string
     */
    public function getSipStatusDescription()
    {
        return $this->sip_status_description;
    }

    /**
     * SIP status description, where the event has one.
     *
     * Generated from protobuf field <code>string sip_status_description = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setSipStatusDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->sip_status_description = $var;

        return $this;
    }

    /**
     * SIP status before the change, for <code>VTSI_EVENT_CALL_SIP_STATUS_CHANGED</code>.
     *
     * Generated from protobuf field <code>optional .ondewo.sip.SipStatus.StatusType previous_sip_status_type = 8;</code>
     * @return int
     */
    public function getPreviousSipStatusType()
    {
        return isset($this->previous_sip_status_type) ? $this->previous_sip_status_type : 0;
    }

    public function hasPreviousSipStatusType()
    {
        return isset($this->previous_sip_status_type);
    }

    public function clearPreviousSipStatusType()
    {
        unset($this->previous_sip_status_type);
    }

    /**
     * SIP status before the change, for <code>VTSI_EVENT_CALL_SIP_STATUS_CHANGED</code>.
     *
     * Generated from protobuf field <code>optional .ondewo.sip.SipStatus.StatusType previous_sip_status_type = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setPreviousSipStatusType($var)
    {
        GPBUtil::checkEnum($var, \Ondewo\Sip\SipStatus\StatusType::class);
        $this->previous_sip_status_type = $var;

        return $this;
    }

    /**
     * The call the event is about or produced, where there is one.
     *
     * Generated from protobuf field <code>string call_name = 9;</code>
     * @return string
     */
    public function getCallName()
    {
        return $this->call_name;
    }

    /**
     * The call the event is about or produced, where there is one.
     *
     * Generated from protobuf field <code>string call_name = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setCallName($var)
    {
        GPBUtil::checkString($var, True);
        $this->call_name = $var;

        return $this;
    }

    /**
     * The campaign the event belongs to, where known.
     *
     * Generated from protobuf field <code>string campaign_name = 10;</code>
     * @return string
     */
    public function getCampaignName()
    {
        return $this->campaign_name;
    }

    /**
     * The campaign the event belongs to, where known.
     *
     * Generated from protobuf field <code>string campaign_name = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setCampaignName($var)
    {
        GPBUtil::checkString($var, True);
        $this->campaign_name = $var;

        return $this;
    }

    /**
     * Human-readable description, e.g. why something failed.
     *
     * Generated from protobuf field <code>string description = 11;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Human-readable description, e.g. why something failed.
     *
     * Generated from protobuf field <code>string description = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Further event-specific values, e.g. <code>caller_name</code>, <code>listener_name</code>,
     * <code>phone_number</code>, <code>container_name</code>, <code>attempt_number</code>,
     * <code>previous_status</code>. Keys are documented per event in the VTSI documentation.
     *
     * Generated from protobuf field <code>map<string, string> attributes = 12;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getAttributes()
    {
        return $this->attributes;
    }

    /**
     * Further event-specific values, e.g. <code>caller_name</code>, <code>listener_name</code>,
     * <code>phone_number</code>, <code>container_name</code>, <code>attempt_number</code>,
     * <code>previous_status</code>. Keys are documented per event in the VTSI documentation.
     *
     * Generated from protobuf field <code>map<string, string> attributes = 12;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setAttributes($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->attributes = $arr;

        return $this;
    }

    /**
     * Statistics of the campaign, on campaign events.
     *
     * Generated from protobuf field <code>.ondewo.vtsi.CampaignStatistics campaign_statistics = 13;</code>
     * @return \Ondewo\Vtsi\CampaignStatistics|null
     */
    public function getCampaignStatistics()
    {
        return $this->campaign_statistics;
    }

    public function hasCampaignStatistics()
    {
        return isset($this->campaign_statistics);
    }

    public function clearCampaignStatistics()
    {
        unset($this->campaign_statistics);
    }

    /**
     * Statistics of the campaign, on campaign events.
     *
     * Generated from protobuf field <code>.ondewo.vtsi.CampaignStatistics campaign_statistics = 13;</code>
     * @param \Ondewo\Vtsi\CampaignStatistics $var
     * @return $this
     */
    public function setCampaignStatistics($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Vtsi\CampaignStatistics::class);
        $this->campaign_statistics = $var;

        return $this;
    }

    /**
     * Increases with every change of <code>resource_name</code> that produced an event, so a
     * receiver can order events of one resource that arrived out of order. Defined (&gt; 0) for
     * call events (the call&apos;s status change number), campaign call events and campaign state
     * events; <code>0</code> where the resource has no such counter, then order by
     * <code>event_time</code>.
     *
     * Generated from protobuf field <code>int64 resource_sequence = 14;</code>
     * @return int|string
     */
    public function getResourceSequence()
    {
        return $this->resource_sequence;
    }

    /**
     * Increases with every change of <code>resource_name</code> that produced an event, so a
     * receiver can order events of one resource that arrived out of order. Defined (&gt; 0) for
     * call events (the call&apos;s status change number), campaign call events and campaign state
     * events; <code>0</code> where the resource has no such counter, then order by
     * <code>event_time</code>.
     *
     * Generated from protobuf field <code>int64 resource_sequence = 14;</code>
     * @param int|string $var
     * @return $this
     */
    public function setResourceSequence($var)
    {
        GPBUtil::checkInt64($var);
        $this->resource_sequence = $var;

        return $this;
    }

}

