<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/nlu/entity_type.proto

namespace Ondewo\Nlu\EntityTypeSorting;

use UnexpectedValueException;

/**
 * Structure of Entity type sorting field
 *
 * Protobuf type <code>ondewo.nlu.EntityTypeSorting.EntityTypeSortingField</code>
 */
class EntityTypeSortingField
{
    /**
     * No sorting applied
     *
     * Generated from protobuf enum <code>NO_ENTITY_TYPE_SORTING = 0;</code>
     */
    const NO_ENTITY_TYPE_SORTING = 0;
    /**
     * Sort by entity type name
     *
     * Generated from protobuf enum <code>SORT_ENTITY_TYPE_BY_NAME = 1;</code>
     */
    const SORT_ENTITY_TYPE_BY_NAME = 1;
    /**
     * Sort by creation date
     *
     * Generated from protobuf enum <code>SORT_ENTITY_TYPE_BY_CREATION_DATE = 2;</code>
     */
    const SORT_ENTITY_TYPE_BY_CREATION_DATE = 2;
    /**
     * Sort by last updated date
     *
     * Generated from protobuf enum <code>SORT_ENTITY_TYPE_BY_LAST_UPDATED = 3;</code>
     */
    const SORT_ENTITY_TYPE_BY_LAST_UPDATED = 3;
    /**
     * Sort by entity value count
     *
     * Generated from protobuf enum <code>SORT_ENTITY_TYPE_BY_ENTITY_VALUE_COUNT = 4;</code>
     */
    const SORT_ENTITY_TYPE_BY_ENTITY_VALUE_COUNT = 4;
    /**
     * Sort by synonym count
     *
     * Generated from protobuf enum <code>SORT_ENTITY_TYPE_BY_SYNONYM_COUNT = 5;</code>
     */
    const SORT_ENTITY_TYPE_BY_SYNONYM_COUNT = 5;

    private static $valueToName = [
        self::NO_ENTITY_TYPE_SORTING => 'NO_ENTITY_TYPE_SORTING',
        self::SORT_ENTITY_TYPE_BY_NAME => 'SORT_ENTITY_TYPE_BY_NAME',
        self::SORT_ENTITY_TYPE_BY_CREATION_DATE => 'SORT_ENTITY_TYPE_BY_CREATION_DATE',
        self::SORT_ENTITY_TYPE_BY_LAST_UPDATED => 'SORT_ENTITY_TYPE_BY_LAST_UPDATED',
        self::SORT_ENTITY_TYPE_BY_ENTITY_VALUE_COUNT => 'SORT_ENTITY_TYPE_BY_ENTITY_VALUE_COUNT',
        self::SORT_ENTITY_TYPE_BY_SYNONYM_COUNT => 'SORT_ENTITY_TYPE_BY_SYNONYM_COUNT',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

