<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/nlu/utility.proto

namespace Ondewo\Nlu\EntityTypeUpdate;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Stores updates applied to an entity
 *
 * Generated from protobuf message <code>ondewo.nlu.EntityTypeUpdate.EntityUpdate</code>
 */
class EntityUpdate extends \Google\Protobuf\Internal\Message
{
    /**
     * Updates made to the entity value
     *
     * Generated from protobuf field <code>.ondewo.nlu.StringUpdate entity_value_update = 1;</code>
     */
    protected $entity_value_update = null;
    /**
     * Updates made to the entity synonyms
     *
     * Generated from protobuf field <code>repeated .ondewo.nlu.StringUpdate entity_synonym_updates = 2;</code>
     */
    private $entity_synonym_updates;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Ondewo\Nlu\StringUpdate $entity_value_update
     *           Updates made to the entity value
     *     @type \Ondewo\Nlu\StringUpdate[] $entity_synonym_updates
     *           Updates made to the entity synonyms
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Nlu\Utility::initOnce();
        parent::__construct($data);
    }

    /**
     * Updates made to the entity value
     *
     * Generated from protobuf field <code>.ondewo.nlu.StringUpdate entity_value_update = 1;</code>
     * @return \Ondewo\Nlu\StringUpdate|null
     */
    public function getEntityValueUpdate()
    {
        return $this->entity_value_update;
    }

    public function hasEntityValueUpdate()
    {
        return isset($this->entity_value_update);
    }

    public function clearEntityValueUpdate()
    {
        unset($this->entity_value_update);
    }

    /**
     * Updates made to the entity value
     *
     * Generated from protobuf field <code>.ondewo.nlu.StringUpdate entity_value_update = 1;</code>
     * @param \Ondewo\Nlu\StringUpdate $var
     * @return $this
     */
    public function setEntityValueUpdate($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Nlu\StringUpdate::class);
        $this->entity_value_update = $var;

        return $this;
    }

    /**
     * Updates made to the entity synonyms
     *
     * Generated from protobuf field <code>repeated .ondewo.nlu.StringUpdate entity_synonym_updates = 2;</code>
     * @return RepeatedField<\Ondewo\Nlu\StringUpdate>
     */
    public function getEntitySynonymUpdates()
    {
        return $this->entity_synonym_updates;
    }

    /**
     * Updates made to the entity synonyms
     *
     * Generated from protobuf field <code>repeated .ondewo.nlu.StringUpdate entity_synonym_updates = 2;</code>
     * @param \Ondewo\Nlu\StringUpdate[] $var
     * @return $this
     */
    public function setEntitySynonymUpdates($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Ondewo\Nlu\StringUpdate::class);
        $this->entity_synonym_updates = $arr;

        return $this;
    }

}

