<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/nlu/intent.proto

namespace Ondewo\Nlu\Intent\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * The collection of simple response candidates. This message in <code>QueryResult.fulfillment_messages</code> and <code>WebhookResponse.fulfillment_messages</code> should contain only one <code>SimpleResponse</code>.
 *
 * Generated from protobuf message <code>ondewo.nlu.Intent.Message.SimpleResponses</code>
 */
class SimpleResponses extends \Google\Protobuf\Internal\Message
{
    /**
     * Required. The list of simple responses.
     *
     * Generated from protobuf field <code>repeated .ondewo.nlu.Intent.Message.SimpleResponse simple_responses = 1;</code>
     */
    private $simple_responses;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Ondewo\Nlu\Intent\Message\SimpleResponse[] $simple_responses
     *           Required. The list of simple responses.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Nlu\Intent::initOnce();
        parent::__construct($data);
    }

    /**
     * Required. The list of simple responses.
     *
     * Generated from protobuf field <code>repeated .ondewo.nlu.Intent.Message.SimpleResponse simple_responses = 1;</code>
     * @return RepeatedField<\Ondewo\Nlu\Intent\Message\SimpleResponse>
     */
    public function getSimpleResponses()
    {
        return $this->simple_responses;
    }

    /**
     * Required. The list of simple responses.
     *
     * Generated from protobuf field <code>repeated .ondewo.nlu.Intent.Message.SimpleResponse simple_responses = 1;</code>
     * @param \Ondewo\Nlu\Intent\Message\SimpleResponse[] $var
     * @return $this
     */
    public function setSimpleResponses($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Ondewo\Nlu\Intent\Message\SimpleResponse::class);
        $this->simple_responses = $arr;

        return $this;
    }

}

