<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/nlu/intent.proto

namespace Ondewo\Nlu\Intent\Message\ListSelect;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * An item in the list.
 *
 * Generated from protobuf message <code>ondewo.nlu.Intent.Message.ListSelect.Item</code>
 */
class Item extends \Google\Protobuf\Internal\Message
{
    /**
     * Required. Additional information about this option.
     *
     * Generated from protobuf field <code>.ondewo.nlu.Intent.Message.SelectItemInfo info = 1;</code>
     */
    protected $info = null;
    /**
     * Required. The title of the list item.
     *
     * Generated from protobuf field <code>string title = 2;</code>
     */
    protected $title = '';
    /**
     * Optional. The main text describing the item.
     *
     * Generated from protobuf field <code>string description = 3;</code>
     */
    protected $description = '';
    /**
     * Optional. The image to display.
     *
     * Generated from protobuf field <code>.ondewo.nlu.Intent.Message.Image image = 4;</code>
     */
    protected $image = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Ondewo\Nlu\Intent\Message\SelectItemInfo $info
     *           Required. Additional information about this option.
     *     @type string $title
     *           Required. The title of the list item.
     *     @type string $description
     *           Optional. The main text describing the item.
     *     @type \Ondewo\Nlu\Intent\Message\Image $image
     *           Optional. The image to display.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Nlu\Intent::initOnce();
        parent::__construct($data);
    }

    /**
     * Required. Additional information about this option.
     *
     * Generated from protobuf field <code>.ondewo.nlu.Intent.Message.SelectItemInfo info = 1;</code>
     * @return \Ondewo\Nlu\Intent\Message\SelectItemInfo|null
     */
    public function getInfo()
    {
        return $this->info;
    }

    public function hasInfo()
    {
        return isset($this->info);
    }

    public function clearInfo()
    {
        unset($this->info);
    }

    /**
     * Required. Additional information about this option.
     *
     * Generated from protobuf field <code>.ondewo.nlu.Intent.Message.SelectItemInfo info = 1;</code>
     * @param \Ondewo\Nlu\Intent\Message\SelectItemInfo $var
     * @return $this
     */
    public function setInfo($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Nlu\Intent\Message\SelectItemInfo::class);
        $this->info = $var;

        return $this;
    }

    /**
     * Required. The title of the list item.
     *
     * Generated from protobuf field <code>string title = 2;</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Required. The title of the list item.
     *
     * Generated from protobuf field <code>string title = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

    /**
     * Optional. The main text describing the item.
     *
     * Generated from protobuf field <code>string description = 3;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Optional. The main text describing the item.
     *
     * Generated from protobuf field <code>string description = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Optional. The image to display.
     *
     * Generated from protobuf field <code>.ondewo.nlu.Intent.Message.Image image = 4;</code>
     * @return \Ondewo\Nlu\Intent\Message\Image|null
     */
    public function getImage()
    {
        return $this->image;
    }

    public function hasImage()
    {
        return isset($this->image);
    }

    public function clearImage()
    {
        unset($this->image);
    }

    /**
     * Optional. The image to display.
     *
     * Generated from protobuf field <code>.ondewo.nlu.Intent.Message.Image image = 4;</code>
     * @param \Ondewo\Nlu\Intent\Message\Image $var
     * @return $this
     */
    public function setImage($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Nlu\Intent\Message\Image::class);
        $this->image = $var;

        return $this;
    }

}

